### ISSUE TITLE
Evince 관련, 실행이 늦어지는 문제.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#1]
1번인가요? ^^ 영광입니다.
모쪼록 발전하는 프로젝트가 되시길 기원합니다.

이전 다솜에서도 보고가 된 문제인데요.
https://github.com/dasom-im/dasom/issues/53

상황이 조금 다르기에 다시 한번 문의드려봅니다.
우분투  15.10/16.04(32/64)에서 evince 를 실행하면 다음과 같은 오류가 발생하면서 창이 뜨는데 상당한 시간이 걸립니다.
```
$ evince
(evince:7481): dasom-CRITICAL **: dasom-im.c:488: dasom_im_new: Could not connect: Permission denied
(evince:7481): dasom-CRITICAL **: dasom-im.c:488: dasom_im_new: Could not connect: Permission denied
(evince:7481): dasom-CRITICAL **: dasom-im.c:488: dasom_im_new: Could not connect: Permission denied
(evince:7481): dasom-CRITICAL **: dasom-im.c:488: dasom_im_new: Could not connect: Permission denied
```
일단 뜨고 나면 PDF 파일 내용을 보는 덴 문제가 없습니다.
그러나 종료했다가 다시 띄우면 같은 현상이 반복됩니다.

우분투 14.04 에선 이 현상이 없는데요. 14.04/15.10/16.04 에서 Evince 가 각각 3.10.3/3.16.1/3.18.2 인 걸 봤을 때, 적어도 3.16.1 부터 이런 모습을 보이는 것 같습니다.

fcitx 상황에선 이런 오류가 발생하지 않고 바로 실행됩니다.
우분투를 새로 설치 한 뒤, update/upgrade 를 하고 다솜만 추가(PPA)하여 시험해봤습니다.

아울러, 따로 이슈를 올릴까하다가 아주 작은 거라서 그냥 여기에 말씀드리겠습니다.
우분투 16.04부터 알리미 영역(App. Indicator)에 있는 다솜 아이콘 크기가 이전 판(14.04~15.10)에 비해서 작아졌습니다. 다른 아이콘들 크기와 달라서 그냥 살짝~ 좀 눈에 띄네요. (일부러 작게 하신 건지..?)

시간 되실 때 한번 살펴봐주시면 고맙겠습니다.

**Comment by cogniti** [comment]
1빠 축하드립니다.

1. evince 가동 문제 `dasom_im_new: Could not connect: Permission denied`
데비안 stretch evince 3.18.2 에서는 재현되지 않습니다.
나중에 시간 날 때 우분투 16.04 에서 해보겠습니다.

2. 접속 실패(Could not connect)할 경우, 시간이 오래 걸리는 문제는
https://github.com/dasom-im/dasom/issues/39 때문에 
https://github.com/cogniti/nimf/commit/a090f21fdda941cc811c9bc3e4331c37de5c56c7
1초 간격으로 5번을 시도(5초 소요됨)하도록 하였기 때문입니다.
위의 로그를 보면 dasom_im_new() 4개 * 5번 = 20초를 기다린 것으로 보입니다.
더 나은 알고리즘을 고안할 필요가 있습니다.

3. 우분투 16.04부터 알리미 영역에 아이콘 크기 문제
아이콘을 일부러 작게 하지는 않았습니다. 22, 24, 32 사이즈를 제공하고 있는데,
다른 사이즈의 아이콘도 필요한지, 아이콘 변환(svg to png)이 제대로 되었는지 확인해보겠습니다.

**Comment by cogniti** [comment]
1번은 원인 파악에 시간이 오래 걸릴 것 같습니다.

2번은, 접속 실패시 async 접속으로 전환하면 될 것 같고

3번은, 어떠한 이유로 아이콘 변환에 문제가 발생한 것 같습니다. 아마 패키징을 다시 하면 해결될 것으로 예상됩니다.

**Comment by cogniti** [comment]
1번 원인을 찾았습니다.
```
kern.log:Apr  5 11:32:28 hodong-desktop kernel: [   23.036294] audit: type=1400 audit(1459823548.936:22): apparmor="DENIED" operation="connect" profile="/usr/bin/evince" pid=1565 comm="evince" family="unix" sock_type="stream" protocol=0 requested_mask="send receive connect" denied_mask="send connect" addr=none peer_addr="@unix:abstract=nimf" peer="unconfined"
```
`apparmor` 때문입니다.

**Comment by cogniti** [comment]
다솜 입력기의 경우

root 권한으로 `/etc/apparmor.d/abstractions/dasom` 파일을 만들어 주시고 아래의 내용을 넣어주세요.

```
# vim:syntax=apparmor

  # Allow connecting to the dasom-daemon socket
  unix (send, receive, connect)
       type=stream
       peer=(addr="@unix:abstract=dasom"),
```

root 권한으로 `/etc/apparmor.d/usr.bin.evince` 파일을 연 후
`  #include <abstractions/ibus>` 다음 줄에 `  #include <abstractions/dasom>` 를 추가해주세요.

그 후 재부팅하면 됩니다.

님프 입력기의 경우

root 권한으로 `/etc/apparmor.d/abstractions/nimf` 파일을 만들어 주시고 아래의 내용을 넣어주세요.

```
# vim:syntax=apparmor

  # Allow connecting to the nimf-daemon socket
  unix (send, receive, connect)
       type=stream
       peer=(addr="@unix:abstract=nimf"),
```

root 권한으로 `/etc/apparmor.d/usr.bin.evince` 파일을 연 후
`  #include <abstractions/ibus>` 다음 줄에 `  #include <abstractions/nimf>` 를 추가해주세요.

그 후 재부팅하면 됩니다.

**Comment by nemonein** [comment]
고맙습니다!
적어도 다솜에선 해결이 되었습니다.
님프는 아직 빌드를 안해봤는데, 한번 해보고 결과 올리겠습니다.

**Comment by cogniti** [comment]
님프는 제가 확인했습니다.
`/etc/apparmor.d/usr.bin.evince` 파일에 ibus 가 두번 나타납니다.
`#include <abstractions/dasom>` 이 한줄 더 추가 되어야합니다. nimf 도 마찬가지.

**Comment by cogniti** [comment]
sync 접속 실패시 async 접속 코드 적용을 보류하겠습니다. async 접속할 경우 지연 현상이 사라지기 때문에 오작동을 인지하기 어렵기 때문입니다. 나중에 다시 고려하겠습니다.

> 2번은, 접속 실패시 async 접속으로 전환하면 될 것 같고

신규 설치할 때마다 매번 이런 식으로 파일을 직접 수정하기는 번거롭습니다. nimf 를 Debian 공식 저장소에 탑재해달라고 요청해야할 시점이 온 거 같습니다.

추후 Debian, im-config, evince, apparmor 프로젝트 쪽에 요청하겠습니다.

**Comment by nemonein** [comment]
님프를 빌드(41027a3) 해봤는데, 성공적으로 꾸러미가 만들어지긴 했으나, 살펴보니 실행파일(nimf-deamon ??)은 없네요.
제가 잘못한 건지~ ^^ (전 프로그래밍엔 거의 지식이 없습니다.)

아울러, debian/control 파일에 다음 2개가 더 포함되어야 할 것 같습니다.
```
libsunpinyin-dev
libanthy-dev
```
그래야 빌드 오류가 발생하지 않네요. 우분투 16.04 기준입니다.
제 블로그에도 해결방법을 올려놓도록 하겠습니다.

아울러, 공식저장소에 등재됨에 있어 사용자들 도움이 필요하시면 말씀해주시기 바랍니다. (어떤 식으로 이뤄지는 지 제가 알지 못하여.. 사용자들 동의가 필요하다거나 하다면 저도 동참하겠습니다.)

**Comment by cogniti** [comment]
패키지 제작용 debian 파일들을 아직 업데이트하지 않았습니다. 감사합니다.

**Comment by cogniti** [comment]
Added apparmor-abstractions https://github.com/cogniti/nimf/commit/c14a66e7a2fb2e5363a26d07a963cf9e911ea005

**Comment by cogniti** [comment]
Update debian files https://github.com/cogniti/nimf/commit/534b2ca8a67757e4dd562f34b9f9a23ad31aa657

패키지 제작용 debian 파일들을 업데이트했습니다.

**Comment by cogniti** [comment]
apparmor-abstractions 파일을 님프에 추가하였으므로 apparmor 에는 보고하지 않아도 상관 없을 것 같고,
우분투에 있는 evince 문제는 https://launchpad.net/evince 에 버그 리포트를 보내면 됩니다.
https://launchpad.net/evince 에서 수용해준다면 데비안 프로젝트에 패키지 탑재해달라고 버그 리포트를 보낼 필요가 없을 것 같습니다.

> 아울러, 공식저장소에 등재됨에 있어 사용자들 도움이 필요하시면 말씀해주시기 바랍니다. (어떤 식으로 이뤄지는 지 제가 알지 못하여.. 사용자들 동의가 필요하다거나 하다면 저도 동참하겠습니다.)

**Comment by cogniti** [comment]
Support nimf in evince debian/apparmor-profile
https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1569863

**Comment by cogniti** [comment]
위 버그 리포트 클릭하시면 This bug affects you 링크가 있습니다.
로그인 하신 후 `Yes, it affects me` 선택해주시면 되겠습니다.
https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1569863/+affectsmetoo

**Comment by cogniti** [comment]
제가 할 수 있는 부분은 다 한 것 같습니다.
이 문제는 우분투에 있는 evince 이슈입니다.
Nimf / Dasom 이슈가 아니므로 이슈를 닫겠습니다.

**Comment by cogniti** [comment]
RFP: nimf -- An input method framework
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=821790

**Comment by cogniti** [comment]
오늘 릴리즈했습니다.
https://github.com/cogniti/nimf/releases/tag/2016.04.26

PPA도 만들었습니다.
https://launchpad.net/~hodong/+archive/ubuntu/nimf

다음은 우분투 16.04 (Xenial) 에서 Nimf 를 설치하는 방법입니다.

다음의 명령으로 공식 님프 PPA 저장소를 추가합니다.

`sudo add-apt-repository ppa:hodong/nimf`

공식 님프 PPA 저장소 추가 후에 다음의 명령으로 패키지를 설치합니다.
```
sudo apt-get update
sudo apt-get install nimf
```
터미널에서 사용자 계정 권한으로 다음 명령을 실행합니다.

`im-config -n nimf`

_(주의: 관리자가 아닌 일반 사용자 계정으로 로그인하셨다면 관리자 권한으로 im-config 을 실행시키지 마십시오.)_

그리고 나서
```
로그아웃
로그인
```
합니다.

즐거운 리눅스 생활하시기 바랍니다.

**Comment by nemonein** [comment]
축하드립니다~!
그동안 고생많으셨습니다.
설치해보니 일본어/중국어도 포함된 것 같네요.

사용해보다가 궁금한 점 생기면 또 질문올리도록 하겠습니다.

다시 한번 감사드립니다!

**Comment by cogniti** [comment]
중국어는 입력이 가능하지만, 일본어는 껍데기 코드만 있는 것이라서 일본어는 입력 불가하며 일본어는 엔진은 비어 있는 상태라고 보시면 됩니다.
추후 `active-engines` 같은 이름으로 한국어, 중국어 엔진만 로딩되도록 할 것입니다. (일본어는 작업이 안 되어 있는 상태이며 그냥.. 껍데기만 있습니다.) 아직 부족한 부분이 많습니다. 시간 관계상 틈틈이 작업하고 있으며 서서히 개선 작업이 이루어 질 것 입니다.
감사합니다.
