### ISSUE TITLE
페도라에서도 사용 가능하도록 지원해 주셨으면 합니다.

### ISSUE THREAD

**Issue by workman729** [cogniti/nimf#10]
페도라에선 컴파일 후 im-config를 사용하지 않으므로 입력기 선택이 불가능 합니다. 페도라가 뭔가 xinput와의 궁합이 우분투와는 다른 것 같은 데 im-chooser로도 입력기 변경이 가능하였으면 하는 바램입니다.

그리고 더 이상 gnome-shell-extension은 지원 하지 않는 건가요?

**Comment by cogniti** [comment]
nimf.conf 파일을 추가했습니다.
컴파일 후에 make install 하시면 /etc/X11/xinit/xinput.d/nimf.conf 파일이 설치됩니다.
그리고 gnome-shell-extension 은 개발하지 않습니다.

**Comment by workman729** [comment]
음!! 메일이 잘 갈지 모르겠지만 rpm 제작을 완료 
하였습니다.

페도라 모임을 통해 배포할까 합니다만 로딩이 
제대로 안되는 문제는
master 버전과 release 버전의 차이에 있는 것 같습니다.

마스터 버전으로 제작하니 로딩에 이상이 없군요!

참고하시기 바랍니다. 도움을 주셔서 감사합니다.
개발에 도움에 될 수 있도록 노력 하겠습니다.

감사합니다.

**Comment by cogniti** [comment]
사실 이미 작년부터 아치리눅스, 페도라를 지원하고 있습니다.
gtk 모듈 로딩 문제는 master 버전과 release 버전 문제가 아닙니다.
아래처럼 설치하면 32비트, 64비트, 데비안, 우분투, 페도라 등에서 잘 되는 것을 알 수 있습니다.

```
    ./autogen.sh
    make
    sudo make install
    sudo ldconfig
    sudo make update-gtk-im-cache
    sudo make update-gtk-icon-cache
```
로그아웃, 로그인 후에 아래처럼 환경 변수 지정해주고
```
    export GTK_IM_MODULE="nimf"
    export QT4_IM_MODULE="nimf"
    export QT_IM_MODULE="nimf"
    export XMODIFIERS="@im=nimf"
```
gedit 또는 kate 를 실행하면 잘 됩니다.

**Comment by workman729** [comment]
소중한 답변 감사합니다.

제가 질문 드린 내용 중 gtk-immodule의 cache 문제는
제가 update-gtk-immodules 명령을 사용하면 되는 것으로 
착각한 탓 입니다.

컴파일상에선 update-gtk-im-cache 명령어를 이용하면 
되지만
rpmbuild 시에는 "gtk-query-immodules-버전" 명령을 이용해야 
하는 데
이것을 그냥 update-gtk-immodules를 이용하면 되는 줄 
착각하고 있었던 탓입니다.

물론 컴파일시에는 말씀 하신 대로 하면 잘 되지만
rpmbuild 상의 spec 파일에는 달리 해야 하기 때문입니다.

그리고 마스터 버전과 릴리스 버전에선 릴리즈 
버전에선 실제로 로딩시 셋팅이
제대로 표현되지 않고(글자가 보이지 않음) 트레이 
아이콘에서 엔진 내용이 나오지 않는 것을 직접 확인 
하였습니다.

제가 잘 못한 것인지 컴파일시에는 트레이 이아콘이 
잘 나왔었는데
rpm 이용시엔 나오지 않는 것으로 보아 뭔가 제가 rpm 
제작을 잘 못한 것인지
아직 잘 모르겠군요!

아하! 지금 보니 kstatus extension을 사용하면 패널에 
나오는 군요!
그러나 한글, 영어 아이콘 변경이 안되나 봅니다. 
계속 느낌표만 나오는 군요!

여하튼 관심을 가져 주셔서 감사드립니다.
번거롭게 해드린 것은 없는지 모르겠습니다.

배포는 페도라 사용자 모임의 자료실에 올려 
두었습니다.
http://fedoralinux.or.kr/board-index.do?part=index&poid=talkbox&rid=7&bid=bbs2,bbs3,talkbox,gallery&cid=6,6,5,5&tag=y&hl=0&tsiz=50&pid=&read=y&memo=y&tid=7&file=y&rate=y&star=y

다시 한번 감사의 말씀 드리며 좋은 주말 되시기 
바랍니다.

감사합니다.

**Comment by cogniti** [comment]
릴리즈 버전으로 했을 경우 im-chooser 했을 때 Nimf 가 안 나온다는 말씀이신지요.
Added nimf.conf for imsettings (issue #10)
https://github.com/cogniti/nimf/commit/11a449817e3070d556c64822b0f3533df6968cdd
`nimf/data/imsettings/nimf.conf.in` (nimf.conf) 파일을 오늘 추가했습니다.

> 그리고 마스터 버전과 릴리스 버전에선 릴리즈 버전에선 실제로 로딩시 셋팅이 제대로 표현되지 않고(글자가 보이지 않음) 트레이 아이콘에서 엔진 내용이 나오지 않는 것을 직접 확인 하였습니다.

nimf-indicator 에 느낌표(!)가 나오는 경우는 nimf-daemon 이 죽었거나 실행되지 않아서 접속이 끊긴 상태를 의미합니다. 그 경우 한글 입력이 되지 않습니다.

> 아하! 지금 보니 kstatus extension을 사용하면 패널에 나오는 군요! 그러나 한글, 영어 아이콘 변경이 안되나 봅니다. 계속 느낌표만 나오는 군요!

**Comment by workman729** [comment]
추가된 사항은 확인 하였으며 릴리즈 버전에선 제가 
임의의 파일을 만들어 해당 위치에 nimf.conf 파일을 
설치도록 하였습니다.
그렇게 해서 im-chooser에서 변경이 가능 하도록 조치 
하였습니다.

그러나 일전에 말씀 드린대로 로딩이 제대로 되지 
않고 셋팅에서 문제가 있어
마스터 버전으로 다시 재빌드 해보니 정상적으로 
로딩이 이루어졌습니다.

트레이 아이콘의 느낌표 문제는 페도라의 특징으로 
인해 그런 것 같습니다.
물론 이상황에서도 한글 입출력은 정상입니다.

페도라에서는 xinputrc 파일을 alternatives link 시켜 
사용하는 데
nimf.conf 파일이 install 되어 있지 않아 발생하는 것 
같습니다.

다음과 같은 조치후 재로그인 하니 아이콘이 
정상적으로 표현됩니다.

# sudo alternatives --install "/etc/X11/xinit/xinputrc" "xinputrc" 
"/etc/X11/xinit/xinput.d/nimf.conf" 100
# sudo alternatives --config xinputrc (nimf.conf 선택)

이후 모든 기능이 정상적이며 추후 spec 파일에 이 
부분을 추가할 예정입니다.

감사합니다.

**Comment by cogniti** [comment]
자꾸 로딩이 안 된다고 하시는데 gtk 모듈 로딩이 안 된다는 것을 의미하는지, 아니면 im-chooser 에 Nimf 라는 글자가 표시되지 않는 것을 의미하는지요?
2016.06.02 릴리즈 버전과 2016.06.12 버전은 별로 차이가 없으므로 2016.06.02 릴리즈 버전으로 gtk 모듈 로딩이 되지 않는다면 잠재적인 버그일 수도 있기 때문에 gtk 모듈 로딩 여부를 확인해보겠습니다.

> 그러나 일전에 말씀 드린대로 로딩이 제대로 되지 않고 셋팅에서 문제가 있어 마스터 버전으로 다시 재빌드 해보니 정상적으로 로딩이 이루어졌습니다.

nimf-daemon 실행 후에 nimf-indicator 가 실행되어야 합니다. 그래야만 nimf-indicator 가 nimf-daemon 에 접속할 수 있습니다.

> 트레이 아이콘의 느낌표 문제는 페도라의 특징으로 인해 그런 것 같습니다. 물론 이상황에서도 한글 입출력은 정상입니다.

**Comment by cogniti** [comment]
어제 설치했던 페도라를 이미 삭제하였으므로
Fedora-Live-Workstation-x86_64-23-10.iso 파일을 다시 버추얼박스에 설치하여 확인해보았습니다.
2016.06.02 릴리즈 버전으로 gtk 모듈 로딩에 문제가 없음을 확인하였습니다.
페도라 문제는 페도라 커뮤니티 또는 페도라 프로젝트에 문의하시기 바랍니다.
페도라 이슈로 인하여 15시간 가량이 무의미하게 소모되었으므로 이슈를 잠그겠습니다.

![screenshot from 2016-06-12 08 53 13](https://cloud.githubusercontent.com/assets/17453239/15988011/2ee8a4e2-307b-11e6-919f-4a1acfca4e67.png)
