### ISSUE TITLE
일본어 입력기 입력 절차 관련 건의

### ISSUE THREAD

**Issue by hajinhoe** [cogniti/nimf#102]
![1111](https://user-images.githubusercontent.com/26132425/39658817-1f9d35e6-5056-11e8-98cc-1fa7262fb9a1.png)

MS 및 구글 입력기에서 私は学生をやってます。를 입력하는 절차입니다.

1번의 최초 입력시 추천 목록은 클라우드에 기반된 것이므로 nimf에서는 구현이 필요없고, 문장 입력을 완료하고 스페이스 키를 누르면 전체 단어가 2번 처럼 자동으로 선택되게 하면 될 것 같습니다. (현행 님프에서는 로마자열 입력시 바로 변환이 되는데, 스페이스바를 입력시 한번에 변환이 되도록.)

2번의 자동 변환과정에서는 님프가 어떤 방식으로 구현을 했는지는 모르겠지만 조사 기준으로 끊어서 변환이 되고 있습니다. (님프 방식도 이용에 무리가 없고 최종적으로 조사에 맞춰서 끊어지고 있으므로 변경 없이 쓰면 될 것 같습니다.)

3번에서는 자동 변환후에 단어 선택의 커서가 제일 첫번째 단어로 이동됩니다. (님프에서도 단어 선택 커서가 있으므로, 제일 첫번째로 자동으로 옮겨주면 될 것 같음.) 사전창에서는 님프처럼 위아래 화살표로도 이동할 수 있고, 스페이스바는 아래 화살표와 같은 기능입니다. 이때 님프처럼 스페이스 키를 해당 한자에서 누르는 것이 아닌 사전 창의 강조된 단어가 바뀌는 것만으로도 입력한 문장의 단어의 한자가 바뀌게 됩니다. 또 그 상태에서 방향키 좌우를 누르면 단어 선택의 커서가 바뀝니다. 이런식으로 입력을 한 후에 엔터를 누르면 문장이 입력됩니다.

또한 님프와는 다르게 단어 선택의 커서 내에서도 별도의 | 모양의 커서를 옮길 수 있어서 (왼쪽 방향키를 두번 누르면 해당 단어 선택 커서 내에서 | 모양의 커서가 움직입니다.) 백스페이스키로 단어 제거 및 문자열 입력으로 글자를 추가하는 것이 가능한데, 개인적으로는 이것보다 위의 사용 방법차이가 더 적응하기 힘든 것 같습니다. (위의 절차는 MS, 구글 입력기 모두 동일합니다.)

| 모양 커서 입력은 님프에서는 간단하게 컨트롤+ 방향키로 한다거나 해서 구현을 해주시는 것도 좋을 것 같습니다.

의견을 읽어주셔서 감사합니다.

**Comment by cogniti** [comment]
nimf-anthy 는 anthy 라이브러리에 기반하고 있습니다.

### prediction

anthy 에 prediction 기능이 있는데 이 기능을 활성화시키고 사용하다보면 segmentation fault 가 발생하므로 그 기능을 nimf 에서는 사용하지 않습니다. nimf 에 적용할 수 있는 prediction 라이브러리가 존재한다면 그리고 그 기능이 실제로 요긴하게 사용된다면 적용 여부를 검토할 의사가 있습니다. 하지만, 시간 관계상 제가 적극적으로 prediction 라이브러리들을 조사하지는 않습니다.

### 변환키

기존 일본어 입력기들은 로마자를 입력하면 히라가나를 표시해주고 스페이스키를 누르면 변환이 되고 엔터키를 누르면 입력이 완료되는 것으로 알고 있습니다.
nimf 의 경우, 로마자를 입력하면 바로 변환을 시작해서 표시해주고, 히라가나도 동시에 표시해줍니다. 엔터키를 누르면 입력이 완료됩니다.
즉, 제가 하고 싶은 말은, nimf 의 경우 변환키를 누를 필요가 없어서 그 점에서 더 효율적이라는 것입니다.
문장을 입력할 때마다 스페이스, 엔터를 매번 누르는 것보다 엔터만 누르는 것이 좋지 않습니까.
![screenshot from 2018-05-05 23-50-50](https://user-images.githubusercontent.com/17453239/39664514-42106fc6-50bf-11e8-911d-4b8bf1adfb2e.png)
watasihagakuseiwoyattemasu. 를 입력하면 私は学生をやってます。 이렇게 표시됩니다. 거기서 엔터키만 누르면 되는데, 입력 과정 중 글자수도 변하니 혼동스러울 수도 있겠군요.
좋은 방법을 생각해보겠습니다.

## 후보 단어 선택

> 이때 님프처럼 스페이스 키를 해당 한자에서 누르는 것이 아닌 사전 창의 강조된 단어가 바뀌는 것만으로도 입력한 문장의 단어의 한자가 바뀌게 됩니다.

nimf 는 스페이스를 눌러서 단어를 선택하는데, 말씀하신 방법은 단지 커서키로 선택하면 되는 방법이군요. 이 부분은 도입 여부를 검토하겠습니다.

## 입력한 단어 수정

> 또한 님프와는 다르게 단어 선택의 커서 내에서도 별도의 | 모양의 커서를 옮길 수 있어서 (왼쪽 방향키를 두번 누르면 해당 단어 선택 커서 내에서 | 모양의 커서가 움직입니다.) 백스페이스키로 단어 제거 및 문자열 입력으로 글자를 추가하는 것이 가능한데

현재 nimf 에는 이러한 기능이 없는데 검토해보겠습니다.

**Comment by cogniti** [comment]
그런데 nimf 로 일본어 입력하면서 바로 자동 변환되는데  많이 혼란스러운가요?

**Comment by cogniti** [comment]
제가 시간이 없는 관계로 순차적으로 작업하려고 합니다.
우선, 히라가나를 보여주는 공간을 없애겠습니다.

**Comment by hajinhoe** [comment]
개인적인 의견이지만 현행 님프 방식은 개발자님께서 말씀하신 대로 키 입력이 최소화될 수 있겠지만, 매번 단어를 입력할 때마다 그게 맞는 한자를 선택해주었을 때 그런 효율이 나옵니다. 그런데, 개인적으로 사용하기에는 일단 가나를 다 쳐놓고 문장마다 처음부터 선택하는 것이 더 익숙하지만, 정답은 없긴 합니다.

> 그런데 nimf 로 일본어 입력하면서 바로 자동 변환되는데 많이 혼란스러운가요?
개인적으로 가장 혼동스러운 부분이 치고 있는 부분이 시시각각 변하는 부분이었습니다. 아무래도 님프 아래에 히라가나 공간하고 같이 봐야 하다보니 개인적으로는 오래치기에는 약간 정신이 없다는 생각이 듭니다....

> 우선, 히라가나를 보여주는 공간을 없애겠습니다.
아니면 히라가나를 보여주는 공간과 변환되는 공간만 서로 바꿔도 눈이 덜 아플 것 같긴합니다만, 그래도 현재 입력하고 있는 창이 두 개다 보면 헷갈리긴 하니 없애고 다른 방식으로 해주시면 사용자로서 감사합니다.

> 제가 시간이 없는 관계로 순차적으로 작업하려고 합니다.
좋은 프로그램 개발해 주셔서 감사합니다. 오래 걸려도 상관없습니다. ^^;; 본업이 우선이죠.

**Comment by cogniti** [comment]
예측 입력은 구현하지 않았습니다.

anthy 에 prediction 기능이 있는데 이 기능을 활성화시키고 사용하다보면 segmentation fault 가 발생하므로 anthy 에 있는 그 기능을 nimf 에서는 사용하지 않습니다. 제가 예측 입력 라이브러리를 조사할 시간이 없습니다. nimf 에 적용할 수 있는, 실제로 요긴하게 사용되는 prediction 라이브러리가 존재한다면 해당 라이브러리를 저에게 알려주시면 예측 입력 구현 여부 검토하겠습니다.


> 또한 님프와는 다르게 단어 선택의 커서 내에서도 별도의 | 모양의 커서를 옮길 수 있어서 (왼쪽 방향키를 두번 누르면 해당 단어 선택 커서 내에서 | 모양의 커서가 움직입니다.) 백스페이스키로 단어 제거 및 문자열 입력으로 글자를 추가하는 것이 가능한데, 개인적으로는 이것보다 위의 사용 방법차이가 더 적응하기 힘든 것 같습니다. (위의 절차는 MS, 구글 입력기 모두 동일합니다.)

> | 모양 커서 입력은 님프에서는 간단하게 컨트롤+ 방향키로 한다거나 해서 구현을 해주시는 것도 좋을 것 같습니다.

위에서 말씀하신 단어 편집은 적용하지 않았습니다.
말씀 들어보니 어떤 기능인지는 이해하겠는데, 커서키를 단어 조각을 선택하는데 이미 사용하고 있습니다.
제가 시간이 없고 nimf 에 신경쓸 때마다 직접적인 금전 손실이 발생하므로 생각하고 싶지 않습니다.
컨트롤+ 방향키로 하는 방법을 말씀하셨는데 UI 작동 과정을 구체적으로 말씀하시면 구현 여부 검토하겠습니다.

위에 두가지 제외하고 기존 입력 관행을 따르도록 수정했습니다.
다만, 테스트를 충분히 하지 않고 업데이트하니 문제 있으면 이슈 올려주세요.
(예측 입력 및 단어 조각 편집 기능에 관해서는, 이 글에 댓글을 올리지 마시고 별도로 이슈 만들어 올려주세요.)

**Comment by cogniti** [comment]
죄송합니다. 롤백하겠습니다.
