### ISSUE TITLE
일본어 입력기 단어 편집 기능

### ISSUE THREAD

**Issue by hajinhoe** [cogniti/nimf#103]
0. 새로 업데이트 하신 것으로 깔아서 실행해 봤습니다. 생각하는 대로 잘 동작하고, 특별한 문제는 없는 것 같습니다.

1. 단어 조각
https://youtu.be/at4fpmmmBiM
윈도우즈 용 일본어 입력기의 작동 동영상입니다.

[문서2.pdf](https://github.com/cogniti/nimf/files/1987495/2.pdf)

제가 제대로 설명을 한 것인지는 모르겠는데....
첨부한 PDF 문서와 같은 순서로 동작하고 있습니다.

2.  ん의 입력 방법에 관해
ん의 입력방법이 한차례 개선된 것으로 알고 있습니다.

> n을 입력하면 일단 ん를 출력합니다.
> 다음에 모음(a e i o u)이 오면 ん를 삭제하고
> na ne ni no nu 에 해당하는 글자를 출력합니다.
> 도깨비불 현상을 허용하는 방법입니다.

그런데 이런 경우에

なるべく
라는 단어를 쓴다면, 
ん
な
なｒ
なる
...
와 같은 순서로 입력이 됩니다.

혹시 크게 변경을 요하는 것이 아니라면, 로직을 이렇게 변경하는 것이 더 일반적일 것 같습니다. (n만 입력한 상태에서는 그냥 n이 출력)

n + 자음 => ん + 해당 자음 (특별히 n다음에 n 자음이 또 오는 경우에는 n을 지우고 ん으로 한다.)
n + 모음 => 나행의 글자

소중한 시간 내주셔서 감사합니다. (아직 단어 예측 라이브러리는 잘 모르겠습니다.)

**Comment by cogniti** [comment]
일본어 단어 편집 기능에 대하여 pdf 문서 봤는데 이해를 못하겠어요.

대신, 제가 생각한 방법이 있습니다.

첫번째 상태

로마자 입력하면 히라가나가 나오는데 커서키로 이동할 수 있도록 하여 중간 부분에서도 삽입, 삭제가 가능하도록 하겠습니다.

두번째 상태

스페이스를 누르면 변환이 되는데 그 상태에서 커서키를 누르면 녹색 표시가 되고 단어 조각들을 선택할 수 있고(기존 기능과 동일), ESC 키를 누르면 첫번째 상태로 전환되어 녹색 표시 사라지고 커서키로 글자들 사이로 이동할 수 있도록 하겠습니다.

ん입력 방법은 아래에 제안한대로 하면 되나요?
https://github.com/cogniti/nimf/issues/85

그리고 예측 기능은 있으면 좋겠지만 제가 시간이 없는 관계로 업데이트 하려면 회사를 며칠 씩 쉬어야 합니다. 반드시 필요한 것만 제안해 주세요.

**Comment by cogniti** [comment]
그런데 코드를 직접 고쳐주실 수는 없는 건가요? 제가 필요로 하는 기능도 아니고 하루 작업할 때마다 10~20만원씩 손해보는데 제가 완전 글로벌 호구죠. 이번 건까지만 무료로 해드리고 다음부터는 유상으로 해드리겠습니다.

**Comment by hajinhoe** [comment]
#85 도 동일한데, 내부적으로 어떤 식으로 구현이 된 건지는 모르겠네요.
예측 기능의 경우 님프에서 그냥 사용 빈도에 따라 현재 처럼 보여주는 것도 크게 불편하지 않다고 생각합니다.
편집 기능의 경우 제가 생각해도 기존 입력기들이 직관적이라고 생각되지는 않아서 개발자님 방안도 좋다고 생각해요.
제가 님프를 편집하려면 일단 공부를 좀 많이 해야 할 것 같네요.... 감사합니다.

**Comment by cogniti** [comment]
현재 버전의 nimf-anthy 는 예측 기능을 사용하지 않습니다.
예측 기능이 어떤 거냐면, 우리들이 핸드폰으로 한글 입력할 때 여러 단어가 목록에 나옵니다.
그게 예측 기능입니다. 제가 직접 구현할 수도 있는데 그 경우 변리사 통해서 관련 특허 여부 검색을 해야 됩니다.
비용이 많이 발생합니다. 그래서 라이브러리를 사용해야 합니다. 그 라이브러리가 LGPL 과 호환되는지 특허 문제는 없는지도 판단해야 합니다.

ん 입력 방법을 기존 관행대로 변경하면 또 다른 문제점이 발생합니다.
문장이 n 으로 끝났을 때 ん로 표시되지 않고 n 으로 표시됩니다. n 을 한번 더 누르거나 스페이스를 눌러야만 비로소 ん로 변환됩니다.

편집 기능의 경우, 제가 원하는 방식으로 구현하면 기존 입력 방식에 익숙하신 분들이 MS 입력기처럼, 구글 입력기처럼 바꿔달라고 하실 거고... 이게 끝이 없습니다. 정답이 없습니다. 이미 제가 원치 않는 방향으로 업데이트를 했는데... 사실 제가 원하는 방식으로 롤백하고 싶은 심정입니다.

**Comment by cogniti** [comment]
아무래도 업데이트 이전으로 롤백하는 것은 어떤가요?
손해보면서 제가 원치 않는 방향으로 업데이트를 한다는 것이 너무 비참하게 느껴집니다.
업데이트 한다고 해서 그게 끝이 아니고 이렇게 했으면 좋겠다 저렇게 했으면 좋겠다는 제안 계속 들어올 겁니다.
제가 이번에 바보짓 한 것 같고 롤백하겠습니다. 죄송합니다.
