### ISSUE TITLE
rpmbuild 에서 im-cache에서 prefix 경로를 따라오지 않습니다.

### ISSUE THREAD

**Issue by workman729** [cogniti/nimf#11]
rpmbuild에서 빌드시에 spec 파일에서 지정한 libdir 경로를 data/im-config/70_nimf.rc 파일에서 변경해 주지 않습니다. 소스를 보니 이미 /usr/lib로 지정하여 설정해 주셨는 데 페도라 또는 오픈수세의 libdir는 /usr/lib64 이므로 빌드 후 gtk-update-im-cache에서 에러가 발생하여 nimf가 제대로 로딩되지 않습니다.

따로 libdir에 대한 소스 변경이 필요할 것으로 보입니다. 현재 수 작업 중 입니다.

**Comment by cogniti** [comment]
data/im-config/70_nimf.rc 파일은 im-conifg 용 파일입니다.
https://github.com/cogniti/nimf/issues/10 에서 페도라에서는 im-config 을 사용하지 않는다고 하셨습니다.
데비안/우분투에서 `prefix=/usr/local` 로 설치하더라도 data/im-config/70_nimf.rc 파일은 정상적으로 작동합니다.
이 이슈의 내용이 잘 이해가 되지 않습니다.
문제점이 정확히 무엇인가요?
`# make gtk-update-im-cache` 할 때 에러가 난다는 것인가요?
페도라에서 에러가 발생하지 않습니다.

**Comment by workman729** [comment]
아! 저의 의도는 im-chooser 대신에 im-config를 사용할 때의 파일의 경로 문제를 말씀 드린 것 입니다. 의도를 정확히 전달하지 못한 점 사과의 말씀 드립니다.

immodule의 cache 문제는 명령어를 잘 못 알고 있었던 저의 실수인 것 같습니다. update-gtk-immodule로 알고 있었는 데 그것이 아니군요...^^

아래 spec 파일의 내용을 보여 드리고 빌드하여 사용할 때 에러가 발생하는 데 어느 부분이 잘 못 된 것인지 알 수 없군요. 로컬에서 컴파일 하여 사용할 때 는 이상이 없는 데 아리송 합니다.

번거롭지 않다면 고수님의 지적 부탁 드리겠습니다.

Name:           nimf
Version:        2016.06.02
Release:        1%{?dist}
Summary:        Input Method Framework
License:        LGPL-3+
URL:           https://github.com/cogniti/%{name}
Source0:        https://github.com/cogniti/%{name}/archive/%{name}-%{version}.tar.gz
Source1:        nimf.conf
#Patch0: 		im-config-fix-fedora.patch

BuildRequires:  libtool
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  glib2-devel
BuildRequires:  intltool
BuildRequires:  gtk2-devel
BuildRequires:  gtk3-devel
BuildRequires:  qt-devel
BuildRequires:  librsvg2-devel
BuildRequires:  librsvg2-tools
BuildRequires:  libappindicator-gtk3-devel
BuildRequires:  anthy-devel
BuildRequires:  libhangul-devel
BuildRequires:  sunpinyin-data
BuildRequires:  sunpinyin-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  google-noto-cjk-fonts
BuildRequires:  gobject-introspection

Requires:       glib2%{_isa} >= %{glib2_version}
Requires:       gsettings-desktop-schemas%{_isa} >= %{gsettings_desktop_schemas_version}
Requires:       hicolor-icon-theme

%description
Nimf is an input method framework which has a module-based client-server
architecture. An application acts as a client and communicates synchronously
with the Nimf server via a unix socket.

%package nimf
Summary: Input Method Framework

%description nimf
Nimf is an input method framework which has a module-based client-server
architecture. An application acts as a client and communicates synchronously
with the Nimf server via a unix socket.

%package devel
Summary: Input Method Framework development headers
Group: Development/Libraries
Requires: %{name} = %{version}-%{release}

%description devel
Nimf is an input method framework which has a module-based client-server
architecture. An application acts as a client and communicates synchronously
with the Nimf server via a unix socket.


%prep
%setup -q
#%patch0 -p1 -b im-config-fix-fedora.patch

%build
CCFLAGS="%{optflags}" \
./autogen.sh \
	--prefix="%{_prefix}" \
	--bindir="%{_bindir}" \
	--datadir="%{_datadir}" \
	--libdir="%{_libdir}" \
	--includedir="%{_includedir}" \
	--disable-static

make %{?_smp_mflags}

%install
mkdir -p %{buildroot}/etc/X11/xinit/xinput.d
%{__install} -m0644 %{SOURCE1} %{buildroot}/etc/X11/xinit/xinput.d/

make install DESTDIR=$RPM_BUILD_ROOT

%post
if [ $1 -eq 1 ] ; then
    gtk-query-immodules-2.0-%{__isa_bits} --update-cache &> /dev/null || :
    gtk-query-immodules-3.0-%{__isa_bits} --update-cache &> /dev/null || :
fi
touch --no-create %{_datadir}/icons/hicolor &>/dev/null || :

%postun
gtk-query-immodules-2.0-%{__isa_bits} --update-cache &> /dev/null || :
gtk-query-immodules-3.0-%{__isa_bits} --update-cache &> /dev/null || :
if [ $1 -eq 0 ] ; then
  touch --no-create %{_datadir}/icons/hicolor &>/dev/null
  gtk-update-icon-cache --quiet %{_datadir}/icons/hicolor &>/dev/null || :
  glib-compile-schemas %{_datadir}/glib-2.0/schemas >&/dev/null || :
fi

%posttrans
gtk-query-immodules-2.0-%{__isa_bits} --update-cache &> /dev/null || :
gtk-query-immodules-3.0-%{__isa_bits} --update-cache &> /dev/null || :
gtk-update-icon-cache --quiet %{_datadir}/icons/hicolor &>/dev/null || :
glib-compile-schemas %{_datadir}/glib-2.0/schemas >&/dev/null || :

%files
%{_bindir}/*
%{_libdir}/girepository-1.0/*
%{_libdir}/gtk-2.0/*
%{_libdir}/gtk-3.0/*
%{_libdir}/libnimf.so.*
%{_libdir}/nimf/*
%{_libdir}/qt4/*
%{_libdir}/qt5/*
%{_datadir}/glib-2.0/schemas/*
%{_datadir}/icons/*
%{_datadir}/im-config/data/*
%{_datadir}/locale/*
%{_sysconfdir}/X11/xinit/xinput.d/*
%{_sysconfdir}/apparmor.d/abstractions/*

%files devel
%{_libdir}/libnimf.la
%{_libdir}/libnimf.so
%{_libdir}/pkgconfig/*
%{_includedir}/*
%{_datadir}/gir-1.0/*

%changelog
* Sat Jun 11 2016 Bae Haezu <workman729@gmail.com> - 2016.06.02
- First build for fedora
- Removed dconf-editor from Recommends field
- Don't use gtk_switch_set_state() for backward compatibility

**Comment by cogniti** [comment]
오픈수세에서 컴파일 후에,
`# make update-gtk-im-cache` 가 정상적으로 동작하는 것을 확인하였습니다.
그런데 오픈수세에는 `im-chooser` 가 없어서 `im-chooser` 작동 여부를 테스트하지 못하였습니다.
각 배포판별 이슈는 각 배포판별 커뮤니티나 각 배포판 프로젝트에 문의하시기 바랍니다.
![screenshot from 2016-06-11 20 14 32](https://cloud.githubusercontent.com/assets/17453239/15984756/33056b24-3011-11e6-8b57-8a1ddb9bee14.png)

**Comment by cogniti** [comment]
페도라 문제는 페도라 커뮤니티 또는 페도라 프로젝트에 문의하시기 바랍니다.
페도라 이슈로 인하여 15시간 가량이 무의미하게 소모되었으므로 #10 과 마찬가지로 이슈를 잠그겠습니다.
