### ISSUE TITLE
일본 리눅스 사용자의 말에 의하면 anthy 보다 mozc를 더 이용한다고 합니다.

### ISSUE THREAD

**Issue by bagjunggyu** [cogniti/nimf#13]
1) Linux Mint에서
리눅스 민트 18.1에 있는 언어 & 입력기 도구를 다시 디자인하기 위해서 
현재 입력기 정보를 모으고 있습니다 - https://github.com/linuxmint/mintlocale/issues/39
그러던 중 일본인으로부터 알게 된 정보인데요, 일본에서는 anthy보다 mozc를 더 많이 이용한다고 합니다.
mozc와 anthy에 대한 의견은 어떠신가요

2) elementary OS Loki에 한, 중, 일 범용 기본 입력기로 nimf를 싣는 작업을 하고 있습니다.
님프 설치할 때 gnome-shell-common 과 gnome-tweak-tool이 기본으로 설치되던데
설치 후에 지워도 님프 작동에는 이상이 없더군요, 
기본 설치 패키지에서 제외해도 되는 것인가요

**Comment by cogniti** [comment]
1. 라이선스 문제 때문에 nimf 에 anthy 를 채택했습니다.

nimf-anthy 는 아직 개발이 되지 않은 상태이므로 nimf 로 일본어 입력이 불가합니다.

2. gnome-tweak-tool 을 삭제해도 nimf 작동에는 영향이 없습니다. 제외해도 됩니다.
2016. 6. 13. 오전 8:53에 "Jung-Kyu Park" <notifications@github.com>님이 작성:

**Comment by bagjunggyu** [comment]
elementary OS 의 PPA에 merging을 해서 우분투나 데비안에 아직 등록되지 않았지만
기본 apt install nimf로 설치되게 되었습니다.
패키지를 걸러내는 것은 어렵겠네요, 님프설치와 함께 설치되기 때문에 설치후에 지우게되면
연관 패키지들에 문제가 있는것으로 보입니다. 지우는 과정에서 보면 뜻밖의 패키지들이 함께 제거되는데요
님프에서 gnome-tweak-tool이 꼭 필요하다면, 다른 방법을 찾아 봐야겠지만
님프PPA에서 빼주실 수 있나요?

**Comment by cogniti** [comment]
deb 패키지는 아래의 파일들로 만들어집니다.
https://github.com/cogniti/nimf/blob/master/debian/

https://github.com/cogniti/nimf/blob/master/debian/control 에 의존성이 나와 있습니다.

gnome-tweak-tool 이 Recommends 항목으로 되어 있는데 Suggests 항목으로 옮기겠습니다. 그렇게 하여 패키지를
만들면 nimf 설치할 때 gnome-tweak-tool 이 함께 설치되지는 않을 겁니다.

다음 릴리즈에 반영됩니다.
감사합니다.
2016. 6. 14. 오전 11:14에 "Jung-Kyu Park" <notifications@github.com>님이 작성:

**Comment by bagjunggyu** [comment]
감사합니다 ^_^
