### ISSUE TITLE
텔레그램 리눅스용 네이티브 클라이언트에서 nimf 를 이용한 한글입력이 안됩니다.

### ISSUE THREAD

**Issue by 5HARK** [cogniti/nimf#16]

**Comment by cogniti** [comment]
아래 파일 보시면 telegram 에 fcitx 지원 패치가 들어 있습니다.
https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/Patches/qtbase_5_6_0.diff
그렇게 nimf 지원 패치를 추가하고 텔레그램을 컴파일하셔서 사용하셔야 됩니다.
패치 파일 작성은 간단합니다.
https://github.com/cogniti/nimf/tree/master/modules/clients/qt5 에 있는 im-nimf-qt5.cpp, nimf.json 파일과 nimf.pro 파일을 작성하여 qtbase_5_6_0.diff 에 넣어주면 됩니다.
telegram 컴파일 방법은
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=telegram-desktop
https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qmake.md
에 있습니다.

**Comment by 5HARK** [comment]
와우 감사합니다. 바로 답장해주시다니..

2016-07-28 22:12 GMT+09:00 Hodong Kim <notifications@github.com>:

**Comment by 5HARK** [comment]
죄송하지만 여쭤볼게 있습니다. 말씀해주신게 혹시 저 패치내용중에  telegram 이 fctix 를 어떻게 지원했는지에 대한 내용을
참고해서 nimf 에 대한 지원부분을 직접 추가하고 다시 빌드하라는 내용이신지요? 제가 맞게 이해했는지...

2016. 7. 28. 오후 10:12에 "Hodong Kim" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
네, 맞습니다. https://github.com/qt/qtbase/tree/5.6/src/plugins/platforminputcontexts 여기 보시면 ibus 보이시죠? 그런 식으로 nimf 디렉토리를 만들고, 그 안에
https://github.com/cogniti/nimf/blob/master/modules/clients/qt5/im-nimf-qt5.cpp
https://github.com/cogniti/nimf/blob/master/modules/clients/qt5/nimf.json
파일을 복사해서 넣고
nimf.pro 파일을 직접 작성하고
https://github.com/qt/qtbase/blob/5.6/src/plugins/platforminputcontexts/platforminputcontexts.pro 을 수정하여 컴파일하면 될 것 같습니다.

telegram 은 qt 5.6 을 다운받아서 스태택 링크를 하는 것 같습니다.
위의 작업은 qt 5.6 에 im-nimf-qt5 모듈을 추가해주는 작업입니다.

**Comment by cogniti** [comment]
`nimf.pro` 파일은
```
TARGET = im-nimf-qt5

PLUGIN_TYPE = platforminputcontexts
PLUGIN_EXTENDS = -
PLUGIN_CLASS_NAME = NimfInputContextPlugin
load(qt_plugin)

QT += gui-private
SOURCES += $$PWD/im-nimf-qt5.cpp
OTHER_FILES += $$PWD/nimf.json
DEFINES = QT_NO_KEYWORDS
INCLUDEPATH = /usr/local/include/nimf \
              /usr/include/glib-2.0 \
              /usr/lib/x86_64-linux-gnu/glib-2.0/include
```
이런 식으로 하시면 되고 `INCLUDEPATH` 경로를 적절하게 변경해 주세요.
```
$ pkg-config --cflags-only-I nimf | sed 's/\-I//g'
```
아래 결과를 `INCLUDEPATH` 경로로 지정하면 되겠습니다. 시스템마다 다르게 나옵니다.
```
/usr/local/include/nimf /usr/include/gio-unix-2.0/ /usr/include/gobject-introspection-1.0 /usr/include/glib-2.0 /usr/lib/x86_64-linux-gnu/glib-2.0/include
```

`platforminputcontexts.pro` 은 아래처럼 하면 됩니다.
```
TEMPLATE = subdirs

qtHaveModule(dbus) {
# Adding fcitx input context plugin to our static build.
!mac:!win32:SUBDIRS += ibus fcitx
}

!mac:!win32:SUBDIRS += nimf

contains(QT_CONFIG, xcb-plugin): SUBDIRS += compose
```

**Comment by 5HARK** [comment]
이렇게 친절하게 알려주시니 정말 많은 도움받는것 같습니다. 말씀하신대로 해서 잘쓰겠습니다 :-)
감사드립니다~~

2016. 7. 29. 오후 7:48에 "Hodong Kim" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
패치 파일을 작성했습니다.
[qtbase_5_6_0-with-nimf.txt](https://github.com/cogniti/nimf/files/390379/qtbase_5_6_0-with-nimf.txt)

`qtbase_5_6_0-with-nimf.txt` 파일의 이름을
`qtbase_5_6_0.diff`
이렇게 변경하고 https://github.com/cogniti/nimf/issues/16#issuecomment-236151233 을 참고하여 .diff 파일에 있는 `nimf.pro` 의 `INCLUDEPATH` 를 사용자분 시스템에 맞게 적절하게 수정하여
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=telegram-desktop
https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qmake.md
를 참고하여 컴파일하시면 되겠습니다.
qt 5.6 과 Telegram 컴파일하는데 수 시간이 소요될 겁니다.
사용자분들이 스스로 컴파일하여 사용하시면 되겠습니다.

**Comment by cogniti** [comment]
저는 cpp, qmake, qt, .pro 를 모릅니다.
qt 개발자 분들께서 `platforminputcontexts.pro` 에서
`pkg-config --print-errors nimf` 결과에 따라 서브 디렉토리인 nimf 를 컴파일할지 말지에 대한 코드를 추가해주시면 좋겠고,
`nimf.pro` 에서 `INCLUDEPATH` 값에 `pkg-config --cflags-only-I nimf | sed 's/\-I//g'` 명령 결과를 넣을 수 있게 고쳐서 Telegram 프로젝트에 https://github.com/telegramdesktop/tdesktop/pulls 패치를 제공해 주시면 좋겠습니다.
