### ISSUE TITLE
Will it support chewing, rime input method?

### ISSUE THREAD

**Issue by JulianLai** [cogniti/nimf#18]
It is a Traditional Chinese input method for Traditional Chinese users, will it have the chance to be in nimf?

**Comment by cogniti** [comment]
Thank you for your interest.
I will develop the wrapper for libchewing within 1 year.

**Comment by cogniti** [comment]
I have been developing nimf-chewing wrapper based on libchewing.
By the way, I feel the lack of nimf candidate.
Please note that I am going to redesign the appearance and API of the candidate window.

**Comment by cogniti** [comment]
I added nimf-chewing, but I don't know Chinese. Try it and then tell me what you want.

**Comment by osfans** [comment]
I test chewing and pinyin in Archlinux from aur, and they work.  Good job!

Will you port librime to nimf?
It supports Chinese, emoji and other languages. Now it has ibus-rime and fcitx-rime.

**Comment by cogniti** [comment]
I will develop the wrapper for librime within 6 months.

**Comment by cogniti** [comment]
I added nimf-rime.
The nimf-rime is under the LGPL, but librime 1.2 is under the GPL.
So, nimf-rime use librime >= 1.2.9 under the BSD.
To use nimf-rime appropriately, install librime-data (debian, ubuntu) or brise (arch, fedora).

**Comment by osfans** [comment]
So quick, I'll test it later. Thanks!

**Comment by osfans** [comment]
@cogniti It works! Thank you very much.
I'll submit some fix and Chinese translation later for nimf-rime.

**Comment by cogniti** [comment]
You can make `nimf.pot` using the following commands.
```
git clone https://github.com/cogniti/nimf.git
cd nimf
./autogen.sh
cd po
make nimf.pot
```
You can translate `nimf.pot` or `ko.po` to your own language.
Thank you.
