### ISSUE TITLE
hook-gdk-event-key 관련, CapsLock 이 눌렸을 때 Shift 로 동작하는 문제.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#2]
다솜은 1.2.2, 우분투 16.04, 주분투 15.10 에서 아래와 같은 현상이 나타납니다.

제목이 좀 복잡합니다만, 이런 현상입니다.
hook-gdk-event-key 이 설정되어 있고, CapsLock 이 켜져 있는 상황에서, -, [ 등을 입력하면 _, { 로 입력되는 현상이 나타납니다. 한국어 입력 상황이 아닌, 영문 입력상황일 때 이렇습니다. 바꿔 말하면, 한국어 상황에선 정상 입력됩니다.

시험해본 결과 Geany, Double Commander(gtk), Terminator(gnome-terminator; http://gnometerminator.blogspot.kr/p/introduction.html) 등 몇몇 프로그램에서 이런 현상이 나타납니다.
Nautilus, gedit, 그놈 터미널 등에선 또 괜찮습니다.

크게 불편한 것은 아니지만, 시간 되실 때 한번 살펴봐주시면 좋겠습니다.

**Comment by cogniti** [comment]
바쁘신 시간에 이렇게 열성적으로 테스트 해주시고 버그 보고 해주셔서 고맙습니다.
https://github.com/cogniti/nimf/blob/c14a66e7a2fb2e5363a26d07a963cf9e911ea005/modules/clients/gtk/im-nimf.c#L91 에 버그가 있음을 확인했습니다.
그리고,
https://github.com/cogniti/nimf/blob/c14a66e7a2fb2e5363a26d07a963cf9e911ea005/modules/clients/gtk/im-nimf.c#L135 에 문제가 있는 것을 확인했습니다.
조만간 고치도록 하겠습니다.
고맙습니다.

**Comment by nemonein** [comment]
도움이 되셨다니 저도 기분이 좋아지네요.
우분투를 사용하다보면 여러 프로그램에서 이런 저런 오작동을 필연적으로 겪게 됩니다.
그 중 Github 에 공개되어 있는 프로그램들은, 이렇게 제작자들과 호흡을 함께할 수 있다는 점이 일반 사용자인 제겐 또 다른 즐거움이라 할 수 있습니다. (소스포지나 런치패드는 버그 보고를 해도 별 반응이 없는 경우가 많았는데, 여기는 거의 대부분 답들을 주시기 편이더라구요.)

개발하시는 분들은 개발이, 저같은 사람들에게는 이런 저런 문제점을 찾는 것이 '재미'라고 할 수 있겠죠. ^^
님프도 조만간 Release 가 나오길 기대해 봅니다.

**Comment by cogniti** [comment]
geany, firefox 는 gtk2 어플입니다. 
https://github.com/cogniti/nimf/blob/c14a66e7a2fb2e5363a26d07a963cf9e911ea005/modules/clients/gtk/im-nimf.c#L135 의 `KeyPress`, `KeyRelease` 이벤트가 넘어오지만,
gedit, nautilus, gnome-terminal 등의 gtk3 어플은 `KeyPress`, `KeyRelease` 이벤트가 넘어오지 않는 것 같습니다.
아마 gtk2, gtk3 의 차이인 것 같습니다. 이 부분은 입력기에서 해결할 수 없는 부분입니다.
우선적으로 해야할 작업들이 많기 때문에 지금은 작업하지 않겠습니다.
미래에 다른 방법의 후킹을 고려하겠습니다.

> 시험해본 결과 Geany, Double Commander(gtk), Terminator(gnome-terminator; http://gnometerminator.blogspot.kr/p/introduction.html) 등 몇몇 프로그램에서 이런 현상이 나타납니다.
Nautilus, gedit, 그놈 터미널 등에선 또 괜찮습니다.

그리고 다솜 프로젝트에 Pull requests 를 보냈습니다. 아마 다음 다솜 릴리즈에 적용될 것입니다.
감사합니다.

**Comment by nemonein** [comment]
다솜 새로운 릴리즈로 빌드해서 확인해봤습니다.
이 이슈에서 말씀드렸던 부분 고쳐졌습니다.
또, 지난 번에 말씀드렸던 인디케이터 아이콘이 작아진 문제도 해결되었습니다.
고맙습니다.

그런데, change log 가 1.2.3 으로 반영되지 않았더군요. 다솜 gtk, 다솜 qt 도 마찬가지로 change log 에 변화가 없습니다. (이 글 쓰는 와중에 debian 파일들이 업데이트 되었다고 알림이 왔네요. 해결된 것일지?)
그리고.. 다솜은 1.2.3 으로 릴리즈 되었다곤 하지만, 다솜 표시기에 보이는 버전 정보는 여전히 1.2.2 입니다.
실행엔 전혀 영향을 주지 않는 것들이니.. ^^

**Comment by cogniti** [comment]
실수로 다솜에 configure.ac, changelog 파일에서 버전을 업데이지 하지 않았나 봅니다.
현재 다솜은 제 관리 영역 밖입니다. 제가 다솜 프로젝트 여러 저장소들에 대한 권한이 없으며 다솜 저장소가 여러 개라서 릴리즈 작업하려면 무척 번거로운 과정을 거쳐야 합니다. 버그는 패치되었으니 일단 그렇게 사용하시면 되겠습니다.
과거 '처녀가 임신했네... 알고보니 아니네요.. 죄송합니다..' 식의 여러 공격 때문에 의도치 않게 Dasom 저장소를 여러 개로 나누게 되었고, 그런 후에도 끝나지가 않아서 결국 Nimf 라고 프로젝트 이름을 변경하여 개발하고 있는 것입니다. Nimf 에는 중국어 엔진도 포함되어 있으므로, README 파일을 한글로 해달라는 지속적인 공격이나 음해, 또는 리눅스에서 한글 입력기 주제가 어렵다거나 개발자가 프로그래밍을 잘 몰라서 못해준다는 추측성 글 같은 것이 Nimf 프로젝트에는 통하지가 않습니다. 이런 사연이 있습니다.

오늘 nimf 에 있는 debian 파일들을 업데이트했습니다만 nimf 를 릴리즈하지 않아서 changelog 를 작성하지 않았습니다.
