### ISSUE TITLE
Some suggestions and questions.

### ISSUE THREAD

**Issue by laichiaheng** [cogniti/nimf#20]
- Press "shift" to switch between "English" and "Japanese/Chinese".

> If I set "left shift" and "right shift" as the trigger keys for switching Chinese and System, there will be some problem. For example, when I am trying to type a Colon, I press "shift+colon", but it will switch to Chinese input method.

- Press "Space" to choose words or vocabularies for the Anthy input method.
- What does `<Mod4>` in the Nimf Settings mean?

**Comment by cogniti** [comment]
I can't reproduce. Perform the following commands in the terminal, and then comment the output.

```
gsettings get org.nimf hotkeys
gsettings get org.nimf.nimf-chewing trigger-keys
```

I will do so.

> Press "Space" to choose words or vocabularies for the Anthy input method.

`<Mod4>` means Super key (Windows key).

**Comment by laichiaheng** [comment]
gsettings get org.nimf hotkeys

> ['<Control> space']

gsettings get org.nimf.engines.nimf-chewing trigger-keys

> ['<Mod4> c', '<Mod2> Shift_L', '<Mod2> Shift_R']

**Comment by cogniti** [comment]
This is correct because you set a left shift or right shift to switch between Chinese and System Keyboard.

> when I am trying to type a Colon, I press "shift+colon", but it will switch to Chinese input method.

Please set another key except for the shift key.

**Comment by laichiaheng** [comment]
It still switch to Anthy input method when I press Ctrl+Space in Chewing input method with this setting:
gsettings get org.nimf hotkeys
['`<Control> <Mod2>` Shift_L']
gsettings get org.nimf.engines.nimf-chewing trigger-keys
['`<Mod4>` c', '`<Control> <Mod2>` space']

Shouldn't it switch between Chewing and System Keyboard?

**Comment by cogniti** [comment]
I can't reproduce.
Confirm whether trigger-keys of nimf-anthy includes `['<Control> <Mod2> space']` or not.
```
gsettings get org.nimf.engines.nimf-anthy trigger-keys
```
If so, remove `['<Control> <Mod2> space']` in the trigger-keys of nimf-anthy.
