### ISSUE TITLE
Unity, Xfce 관련 문제.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#22]
안녕하세요.
제 블로그에서 말씀 나눴던 문제( http://nemonein.egloos.com/5306723 )를 이 쪽으로 옮겨왔습니다.
정식 이슈로 등록되는 편이 나을 것 같기도 하고, 블로그엔 답글 알림 기능이 없어서 제 때 답변을 드리기가 어려운 면도 있었구요.

먼저, https://launchpad.net/~hodong/+archive/ubuntu/testing/+files/nimf_2016.09.20_amd64.deb 이 파일은 09.16판과 동일한 결과를 보여줍니다. (Unity 구동 불가)
9월 3일 자(6ebd95f Commit) 판은 말씀하신대로 정상 작동합니다.

위에 있는 수정판(nimf_2016.09.20_amd64.deb)으로 nimf-daemon --no-daemon --debug 을 실행하고, 결과를 잠시 뒤에 올려드리도록 하겠습니다.

**Comment by nemonein** [comment]
```$ nimf-daemon --no-daemon --debug
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:757: nimf_server_new
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:731: nimf_server_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:585: nimf_server_init
(nimf-daemon:4026): nimf-DEBUG: nimf-candidate.c:492: nimf_candidate_new
(nimf-daemon:4026): nimf-DEBUG: nimf-candidate.c:239: nimf_candidate_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-candidate.c:139: nimf_candidate_init
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:505: nimf_server_load_engines
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:31: nimf_module_new
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:98: nimf_module_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:92: nimf_module_init
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:45: nimf_module_load
(nimf-daemon:4026): nimf-DEBUG: nimf-libhangul.c:843: module_register_type
(nimf-daemon:4026): nimf-DEBUG: nimf-libhangul.c:850: module_get_type
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:353: nimf_engine_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-libhangul.c:814: nimf_libhangul_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:260: nimf_engine_init
(nimf-daemon:4026): nimf-DEBUG: nimf-libhangul.c:711: nimf_libhangul_init
(nimf-daemon:4026): nimf-DEBUG: nimf-candidate.c:485: nimf_candidate_get_default
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:38: nimf_key_new_from_nicks
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:123: nimf_preedit_attr_new
(nimf-daemon:4026): nimf-DEBUG: nimf-libhangul.c:637: nimf_libhangul_update_transition_cb
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:39: nimf_engine_set_property
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:38: nimf_key_new_from_nicks
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:38: nimf_key_new_from_nicks
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:31: nimf_module_new
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:92: nimf_module_init
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:45: nimf_module_load
(nimf-daemon:4026): nimf-DEBUG: nimf-system-keyboard.c:111: module_register_type
(nimf-daemon:4026): nimf-DEBUG: nimf-system-keyboard.c:118: module_get_type
(nimf-daemon:4026): nimf-DEBUG: nimf-system-keyboard.c:92: nimf_system_keyboard_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:260: nimf_engine_init
(nimf-daemon:4026): nimf-DEBUG: nimf-system-keyboard.c:74: nimf_system_keyboard_init
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:39: nimf_engine_set_property
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:31: nimf_module_new
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:92: nimf_module_init
(nimf-daemon:4026): nimf-DEBUG: nimf-module.c:45: nimf_module_load
(nimf-daemon:4026): nimf-DEBUG: nimf-chewing.c:437: module_register_type
(nimf-daemon:4026): nimf-DEBUG: nimf-chewing.c:444: module_get_type
(nimf-daemon:4026): nimf-DEBUG: nimf-chewing.c:410: nimf_chewing_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:260: nimf_engine_init
(nimf-daemon:4026): nimf-DEBUG: nimf-chewing.c:350: nimf_chewing_init
(nimf-daemon:4026): nimf-DEBUG: nimf-candidate.c:485: nimf_candidate_get_default
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:123: nimf_preedit_attr_new
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:123: nimf_preedit_attr_new
(nimf-daemon:4026): nimf-DEBUG: nimf-engine.c:39: nimf_engine_set_property
(nimf-daemon:4026): nimf-DEBUG: nimf-types.c:38: nimf_key_new_from_nicks
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:311: nimf_server_initable_init
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:1266: nimf_server_start
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:1193: nimf_server_init_xims
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:1154: nimf_xevent_source_new
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:776: nimf_xevent_source_prepare
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:785: nimf_xevent_source_check
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:776: nimf_xevent_source_prepare
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:785: nimf_xevent_source_check
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:776: nimf_xevent_source_prepare
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:785: nimf_xevent_source_check
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:776: nimf_xevent_source_prepare
(nimf-daemon:4026): nimf-DEBUG: nimf-server.c:785: nimf_xevent_source_check
(nimf-daemon:4026): nimf-DEBUG: im-nimf.c:568: im_module_init
(nimf-daemon:4026): nimf-DEBUG: im-nimf.c:589: im_module_create
(nimf-daemon:4026): nimf-DEBUG: im-nimf.c:334: nimf_gtk_im_context_new
(nimf-daemon:4026): nimf-DEBUG: im-nimf.c:529: nimf_gtk_im_context_class_init
(nimf-daemon:4026): nimf-DEBUG: im-nimf.c:466: nimf_gtk_im_context_init
(nimf-daemon:4026): nimf-DEBUG: nimf-im.c:348: nimf_im_new
(nimf-daemon:4026): nimf-DEBUG: nimf-client.c:434: nimf_client_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-im.c:380: nimf_im_class_init
(nimf-daemon:4026): nimf-DEBUG: nimf-client.c:225: nimf_client_init
(nimf-daemon:4026): nimf-DEBUG: nimf-im.c:357: nimf_im_init
(nimf-daemon:4026): nimf-DEBUG: nimf-client.c:395: nimf_client_set_property
(nimf-daemon:4026): nimf-DEBUG: nimf-client.c:249: nimf_client_constructed
(nimf-daemon:4026): nimf-DEBUG: nimf-private.c:33: nimf_send_message: fd = 18
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:42: nimf_message_new_full
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:92: nimf_message_get_header
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:100: nimf_message_get_header_size
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:100: nimf_message_get_header_size
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:136: nimf_message_get_name
(nimf-daemon:4026): nimf-DEBUG: send: NIMF_MESSAGE_CREATE_CONTEXT, fd: 18
(nimf-daemon:4026): nimf-DEBUG: nimf-message.c:73: nimf_message_unref
(nimf-daemon:4026): nimf-DEBUG: nimf-private.c:218: nimf_result_iteration_until```

**Comment by cogniti** [comment]
nimf 2016.09.16 버전으로 몇가지 확인해본 결과,
데비안 Jessie, GNOME 환경에서는 문제가 없고, (물리적 컴퓨터)
우분투 16.04.1 Unity 환경에서 문제가 없습니다. (가상 컴퓨터)
Manjaro XFCE 환경에서 문제가 없습니다. (가상 컴퓨터)
Elementary OS 설치: elementaryos-0.4-stable-amd64.20160909.iso 를 가상 컴퓨터에 설치하여 테스트하였는데 문제가 없었습니다. 무슨 환경인지는 저도 모르겠고 우분투 16.04  xenial 기반입니다.

nimf 2016.09.18 (테스트용) 으로
우분투 16.04.1 Unity 환경에서 문제가 없습니다. (물리적 컴퓨터)

nimf 소스를 확인해보았는데,
https://github.com/cogniti/nimf/blob/200f985c5a3c8ba4a2176d928295e20fe40a04d0/libnimf/nimf-candidate.c#L147
`g_unsetenv ("GTK_IM_MODULE");`
이 부분이 있습니다.
이 부분이 어떠한 환경에서 효과가 나타나지 않는 것입니다.
그래서 테스트용 버전 2016.09.18 에 그 부분을 nimf-daemon.c 에 `main ()` 으로 옮겨놓았는데...
nemonein 님과 구글 플러스쪽으로 문의하신 분의 컴퓨터 환경에서 작동이 안 되고 있는 상태입니다.
그외 https://github.com/cogniti/nimf/issues/21#issuecomment-247858910 보고되어 있는데, nimf 문제인지 배포판 문제인지 정확하지 않습니다.

제가 직접 가상 머신이 아닌 물리적 컴퓨터에 우분투 16.04.1 을 설치한 후 nimf 2016.09.18 을 설치해보니 잘 됩니다. nimf 문제가 아닌 것 같습니다. 마땅히 nimf 에서 해결할 방법도 없습니다.
`g_unsetenv ("GTK_IM_MODULE");` 이 코드는 다른 프로그램에서도 일반적으로 사용되는 코드입니다.

nimf 가 왜 멈추는지를 설명드리겠습니다.

운영체제 환경에서 `GTK_IM_MODULE`가 `nimf`로 설정되어 있습니다.
로그인할 때, im-config 에서 nimf-daemon 을 실행시킵니다.
nimf-daemon 에서 candidate window 를 생성합니다. 화면에 바로 나타나지는 않지만 생성됩니다.
candidate window 는 `GtkEntry` 와 `GtkTreeView` 등으로 구성되어 있습니다.
`GtkEntry`는 nimf-rime 을 위해 9월 4일 추가되었습니다.
`GtkEntry`는 입력을 받는 위젯입니다. 따라서 입력기를 호출하게 됩니다.
그래서 nimf 에서 client 모듈이 작동하여 nimf-daemon 과 접속을 시도하게 되는데, nimf-daemon 은 준비가 되지 않은 상태라 client 모듈에 응답할 수 없습니다. 그래서 client 가 무한히 서버 응답을 기다리는 것입니다.

nimf-daemon 에서 candidate window 때문에 gtk (`GtkEntry`, `GtkTextView`)를 사용하게 되는데 그것이 client 모듈을 작동시키고 nimf-daemon 에 접속을 시도하고 응답을 기다리고 있는 상태입니다.
그렇다면 gtk 가 nimf 를 사용하지 않도록 해야 하는데, 그걸 하는 코드가...
`g_unsetenv ("GTK_IM_MODULE");`
입니다.
따라서 이 코드가 반드시 효과를 내타내야 합니다. 무슨 말이냐면 위 코드가 실행되었을 때 `GTK_IM_MODULE="nimf"` 가 내부적으로 없어져서 nimf-daemon 에 nimf 를 호출하는 상황을 방지하는 것인데... 어떠한 환경에서 그 코드가 효력이 없는 것입니다.

재현이 되지 않기 때문에 마땅히 해결할 수 있는 방법이 없습니다. 아마 배포판 문제나 시스템 설정 문제로 보입니다.

**Comment by cogniti** [comment]
위에 `2016.09.18` 을 `2016.09.20` 으로 수정했습니다.
물리적 컴퓨터에 설치한 것이 `nimf 2016.09.20` 테스트용 버전입니다.
![screenshot from 2016-09-20 22-24-46](https://cloud.githubusercontent.com/assets/17453239/18671912/e788cf3c-7f80-11e6-8796-bdadf7a354fb.png)

**Comment by cogniti** [comment]
아래처럼 **`GTK_IM_MODULE=none`** 을 추가하셔서 테스트해보시기 바랍니다.

```
cogniti@cogniti-All-Series:/usr/share/im-config/data$ more 70_nimf.rc 
if [ "$IM_CONFIG_PHASE" = 2 ]; then
    GTK_IM_MODULE=none nimf-daemon

    if ! test -z `which nimf-indicator`; then
        nimf-indicator
    fi
fi

if [ "$IM_CONFIG_PHASE" = 1 ]; then
    XMODIFIERS="@im=nimf"
    GTK_IM_MODULE=nimf
    QT4_IM_MODULE=nimf
    QT_IM_MODULE=nimf
    CLUTTER_IM_MODULE=xim
fi
```

**Comment by nemonein** [comment]
답변 주셔서 고맙습니다.
시키신 대로 `/usr/share/im-config/data/70_nimf.rc`파일에 추가해봤는데, 전혀 다른 점이 없네요.

제가 사용하는 어떤 것들과 충돌이 있나 하여, 몇몇 꾸러미를 지워봤으나(btsync, insync 등), 역시 마찬가지입니다.
그렇다면, 저런 프로그램들을 제외하고 제 데스크탑과 노트북이 어떤 부분을 공유하고 있는가를 생각해봤는데요.

기본값(?)과 다른 점이 있다면, 제가 btrfs 파일 형식을 사용한다는 점을 들 수 있겠는데요. 설마 이게 문제가 될까요?
그것 외엔 딱히 특별한 건 없는 것 같습니다. VBox 에는 Ext4 로 설치했었습니다.

제 나름대로 몇가지 경우를 시험해보고 다시 결과를 올려드리겠습니다.

고맙습니다.

**Comment by cogniti** [comment]
환경변수를 해제하는 코드를 넣었는데 그것이 작동되지 않는 것이라면,
nimf 뿐만 아니라 환경 변수를 다루는 다른 프로그램에서도 문제가 발생할 것입니다.
아무튼,
nimf 2016.09.16 릴리즈 버전으로 테스트해봤는데 문제가 없었습니다.
xubuntu 를 다운받아서 물리적 컴퓨터에 설치하여 테스트해보겠습니다.

nemonein 님께서도 시간이 가능하시면 우분투나 주분투를 물리적 컴퓨터에 새로 설치하여 테스트해보시기 바랍니다.

**Comment by cogniti** [comment]
xubuntu 를 설치할 필요가 없이 간단하게 nimf 버그가 아님을 확인하였습니다.
우선, 우분투 16.04.1 ( ubuntu-16.04.1-desktop-amd64.iso )을 물리적인 컴퓨터에 설치를 합니다.

https://github.com/cogniti/nimf/releases/tag/2016.09.16 릴리즈 버전을 다운받아서 rime 제거하고 debuild 로 컴파일하여 deb 패키지 만들어서 설치하면 정상적으로 작동됩니다.

아래부터 nimf 버그가 아님을 증명하겠습니다.

https://github.com/cogniti/nimf/blob/33f72292cfe7663a2e8b2525e80c3266020f9b60/libnimf/nimf-candidate.c#L147
이 라인은 nimf-daemon 에 있는 candidate (gtk entry) 가 nimf 를 호출하는 것을 막는 코드입니다.
따라서, 이 라인을 삭제하고, 컴파일하여 설치하면 nimf 가 멈추어 로그인을 못하는 상황이 발생됩니다.

그런데 그와 같은 역할을 하는 코드를 아래처럼 설정 파일에 넣을 수도 있습니다.
/usr/share/im-config/data/70_nimf.rc 
```
GTK_IM_MODULE=none nimf-daemon
```

```
cogniti@cogniti-All-Series:/usr/share/im-config/data$ more 70_nimf.rc 
if [ "$IM_CONFIG_PHASE" = 2 ]; then
    GTK_IM_MODULE=none nimf-daemon

    if ! test -z `which nimf-indicator`; then
        nimf-indicator
    fi
fi

if [ "$IM_CONFIG_PHASE" = 1 ]; then
    XMODIFIERS="@im=nimf"
    GTK_IM_MODULE=nimf
    QT4_IM_MODULE=nimf
    QT_IM_MODULE=nimf
    CLUTTER_IM_MODULE=xim
fi
```
이렇게 하면  C 소스에서 https://github.com/cogniti/nimf/blob/33f72292cfe7663a2e8b2525e80c3266020f9b60/libnimf/nimf-candidate.c#L147 을 삭제하고 컴파일하여도 nimf 는 정상적으로 작동합니다.
따라서 이 이슈는 nimf 버그가 아닙니다.

그런데 일부 사용자 분들의 시스템에서 `GTK_IM_MODULE=none nimf-daemon` 코드가 정상적으로 작동하지 않는다면 시스템 손상이 의심됩니다.
우분투 또는 주분투를 새로 설치하시면 해결될 것으로 보입니다.

**Comment by cogniti** [comment]
재현에 성공했습니다.

**Comment by cogniti** [comment]
XSETTINGS 와 관련 있습니다.

재현 방법
```
hodong@debian:~$ gsettings set org.gnome.desktop.interface gtk-im-module 'nimf'
hodong@debian:~/nimf$ dump_xsettings | grep IM
Gtk/IMStatusStyle "callback"
Gtk/IMModule "nimf"
Gtk/IMPreeditStyle "callback"
```

재현 안 되게 하는 방법
```
hodong@debian:~$ gsettings set org.gnome.desktop.interface gtk-im-module ''
hodong@debian:~/nimf$ dump_xsettings | grep IM
Gtk/IMStatusStyle "callback"
Gtk/IMModule ""
Gtk/IMPreeditStyle "callback"
```

곧 수정될 것입니다.

**Comment by nemonein** [comment]
원인이 밝혀졌나 보군요.
한가지 제가 알아낸 사실을 덧붙입니다.

문제가 되는 제 기기들(데스크탑-우분투/노트북-주분투)은 모두 언어가 '한국어'로 설정이 되어 있습니다.
이것을 영어로 바꾸면 Unity/Xfce 가 제대로 작동하지 않는 동작이 사라집니다.

또, 우분투/주분투 16.04.1 iso 이미지로 VBox 에 시험해본 바에 따르면..
우분투는 영어든 한국어든 관계없이 이상이 없는 것 같습니다.
주분투는 한국어로 설정되어 있으면 Xfce 작동 이상현상이 생깁니다. 영어일 때는 괜찮습니다.

혹시라도 이 문제를 겪고 있는 분들이 계시다면, 그리고 꼭 Nimf 최신판을 써야 한다면, 확실하게 원인 해결이 될 때까지는 언어설정(우분투 기준으로, '시스템 설정' - '언어 지원')을 영어로 바꾸고 쓰시면 될 것 같습니다.

**Comment by cogniti** [comment]
이 버그는 nimf 버그입니다. This bug is a nimf's bug.
 
gtk api 문서에 아래와 같은 내용이 있습니다. 제 불찰로 빚어진 버그입니다.

> GTK_IM_MODULE.  Specifies an IM module to use in preference to the one determined from the locale. If this isn't set and you are running on the system that enables XSETTINGS and has a value in Gtk/IMModule, that will be used for the default IM module. This also can be a colon-separated list of input-methods, which GTK+ will try in turn until it finds one available on the system. ﻿

nimf-daemon.c 에 main() 에 GTK_IM_MODULE 을 unset 하지 않고, "gtk-im-context-simple" 로 set 하면 해결되는 것 같습니다.
저녁 때 테스트하고 릴리즈하고 패키지 만들 예정입니다.
늦어도 내일까지는 해결됩니다.
이용에 불편을 끼쳐드린 점, 사용자 분 컴퓨터 환경을 탓한 점에 대해 죄송스럽게 생각합니다.
진심으로 죄송합니다.

**Comment by cogniti** [comment]
nimf 2016.09.22 버전을 다운로드할 수 있습니다.

우분투 16.04 용 바이너리 패키지를 준비했습니다.
의존성 때문에 nimf-rime 제거된 버전입니다.

사용해보시고 잘 되는지 안 되는지 꼭 알려주세요.

http://cogniti.github.io/nimf/download/

**Comment by nemonein** [comment]
기다리실 까봐 결과 먼저 알려드립니다.
좀 전에 글 올리셨을 때 제가 빌드 중이었었는데요.

(제가 빌드한 것으로는~) 잘 됩니다!! ^^ (전 한국어를 제외한 다른 엔진은 모두 제외하고 빌드했습니다.)
위의 것으로도 다시 해보고, 또 노트북(주분투)에서도 해보고 곧 다시 말씀드리겠습니다. (당연히 잘 되겠죠.)

정말 고생하셨습니다.
고맙습니다.

**Comment by nemonein** [comment]
올려주신 꾸러미로 우분투/주분투 모두 이상없이 잘 됩니다.

며칠 동안 정말 신경 많이 쓰셨겠네요.
다시 한번 감사드립니다.

**Comment by cogniti** [comment]
nemonein 님 덕분에 빨리 해결할 수 있었습니다.
제가 성격이 좀 거시기해서.. 감정이 상하셨을까봐 우려가 되는데 그냥 잊으세요. 그 부분에 대해서는 죄송합니다. 그건 제 성격 탓입니다.
nemonein 님 고맙습니다. nemonein 님은 정말 대단하신 분 같습니다.
고맙습니다.

**Comment by nemonein** [comment]
아~ 전 전혀 기분 상하지 않았습니다.
기분 상할 일은 전혀 없었는데요. ㅎㅎ
재현이 잘 안되는 것에서 문제점을 찾아내는 것이 결코 쉽지 않다는 것을 저도 잘 알고 있습니다.
그래도 끝까지 추적해주신 것에 놀랍고 감사드립니다.

부디 앞으로도, 너무 스트레스 받지 마시고, 천천히 즐겁게 개발하시길 기원하겠습니다.
아울러, 정말 큰 일하고 계시단 것에, 모든 리눅스 사용자를 대신하여 감사 인사올립니다. ^^

(이 이슈는 제가 시원하게 닫도록 하겠습니다.)
