### ISSUE TITLE
Some of the words can not be found when using anthy input method.

### ISSUE THREAD

**Issue by laichiaheng** [cogniti/nimf#23]
for example, I want to type "人", so I input "jin", I can't find this word.

**Comment by cogniti** [comment]
Thank you for reporting the bug.

**Comment by cogniti** [comment]
You can download a new version.

http://cogniti.github.io/nimf/download/

**Comment by laichiaheng** [comment]
Wow! You update so fast!

**Comment by cogniti** [comment]
You can download a new version.

http://cogniti.github.io/nimf/download/
