### ISSUE TITLE
Any plans to support Wayland?

### ISSUE THREAD

**Issue by sukso96100** [cogniti/nimf#25]
안녕하세요. 오늘 아치 리눅스에서 Gnome 3.22 가 Stable 저장소 쪽에 올라와서 업데이트를 했는데, Gnome 3.22 부터는 Wayland 가 기본값이고, 기존의 Xorg 는 선택사항 이더군요, 세션 선택을 보니. `그놈` 이 `그놈(Xorg)` 로, `그놈(Wayland)` 가 그냥 `그놈`으로 바뀌고 있고 이것이 가장 위로 가 있더군요. 아치가 업데이트가 빠른 편이고, 당장 님프에서 Wayland 를 지원하는 것을 무리라고 생각되서, 일단은 Xorg 로 계속 사용하겠습니다만. 곧 다른 배포판에서도 3.22 가 배포되면, Wayland 를 기본으로 쓰게 될 수도 있는 만큼. Wayland 지원 계획을 세우고, 지원 작업을 시작 하시면 좋을 것 같습니다. 감사합니다.

**Comment by cogniti** [comment]
언젠가 지원하겠지만 지금은 개인적인 사정으로 지원 계획이 없습니다.

**Comment by cogniti** [comment]
2017년 1월~2월에 Wayland 를 지원할 계획입니다. 참고하시기 바랍니다.

**Comment by sukso96100** [comment]
네. 기다리고 있겠습니다.

**Comment by cogniti** [comment]
XIM 을 모듈화하여 분리하였고 wayland 모듈을 만들었습니다. 다만, 충분한 테스트가 필요하여 코드를 업로드 하지 않았고 올해 내에 커밋하여 지원할 예정입니다.

**Comment by cogniti** [comment]
추후 작업을 위해 필요한 정보를 기록합니다.

wayland 버전에 따라 프로토콜에 차이가 있을 수 있습니다.
https://packages.debian.org/stretch/wayland-protocols

그리고 wayland 용 입력기를 만들기 위해서는,
simple-im.c 에 simple_im_key_handler 를 nimf 로 대체하면 됩니다.
https://github.com/freedesktop/wayland-weston/blob/master/clients/simple-im.c

nimf 에 보면 클라이언트 측에서 nimf_im_* 이 있는데 이걸 사용하면 간편하게 코딩할 수 있지만, 통신이 한 번 더 발생하는 단점이 있습니다.
따라서 서버측의 nimf_context_* 을 사용하여 바로 nimf 서버에서 처리하는 방법이 유리하지만, nimf_context_* 은 nimf 프로토콜, xim 프로토콜을 동시에 처리하고 있어서 wayland 를 추가할 경우 모듈화가 불편해지는 단점(의존성 문제)이 발생합니다.
그래서 nimf_server_im_* 등으로 개명하여 서버측 im context 를 처리하는 방법을 고려해 볼 수 있고,
아니면 nimf_xim_im_*, nimf_wayland_im_* 등의 (꼭 이 명칭이 아니더라도) 적절한 방법으로 재설계할 필요가 있습니다.

**Comment by cogniti** [comment]
데비안 Stretch 에서 GNOME 3.22 를 wayland 에서 돌리고 있는데 입력에 문제가 없습니다.
아마 아치 리눅스에서 GNOME 을 wayland 에서 돌려도 입력에는 문제가 없을 것 같습니다.
GTK 어플을 이용하면 gtk im 모듈을 사용하기 때문에 GTK 가 이미 wayland 를 지원하고 있으므로 님프에서 wayland 를 지원하지 않더러도 입력하는데 지장이 없을 것입니다.
X 애플리케이션이 XIM 을 이용하듯이, Wayland 애플리케이션이 wayland input method 를 이용한다고 보시면 되겠습니다.

> 안녕하세요. 오늘 아치 리눅스에서 Gnome 3.22 가 Stable 저장소 쪽에 올라와서 업데이트를 했는데, Gnome 3.22 부터는 Wayland 가 기본값이고, 기존의 Xorg 는 선택사항 이더군요, 세션 선택을 보니. 그놈 이 그놈(Xorg) 로, 그놈(Wayland) 가 그냥 그놈으로 바뀌고 있고 이것이 가장 위로 가 있더군요. 아치가 업데이트가 빠른 편이고, 당장 님프에서 Wayland 를 지원하는 것을 무리라고 생각되서, 일단은 Xorg 로 계속 사용하겠습니다만. 곧 다른 배포판에서도 3.22 가 배포되면, Wayland 를 기본으로 쓰게 될 수도 있는 만큼. Wayland 지원 계획을 세우고, 지원 작업을 시작 하시면 좋을 것 같습니다. 감사합니다.

**Comment by sukso96100** [comment]
감사합니다. 아치 리눅스 환경에서 곧 테스트 해 보겠습니다.

**Comment by cogniti** [comment]
weston 에서 돌려봤는데 gedit 에서 한글이 입력됩니다. qt 어플도 마찬가지로 잘 될 것으로 추측합니다.
님프의 wayland 지원 여부에 관계없이 응용 프로그램을 사용하시면 되겠습니다.

![screenshot from 2017-03-12 00-31-00](https://cloud.githubusercontent.com/assets/17453239/23824583/8389db52-06bc-11e7-93a9-cbd4d879b0ec.png)

**Comment by cogniti** [comment]
현 시점에서 wayland input method 를 사용하는 어플이 weston 밖에 없는 것 같고 wayland input method protocol 이 unstable 상태입니다. 그리고 기존 어플 입력에 문제가 없습니다.
따라서 wayland 모듈을 만드는 것은 시기상조라고 생각합니다. 미래에 지원 여부를 다시 검토하겠습니다.

**Comment by cogniti** [comment]
wayland-protocols 패키지가 Debian Jessie 에 없어서 wayland 를 추가할 경우 Debian Jessie 에서 의존성 문제를 풀 수 없어서 그것 때문에 망설였는데... 알아보니 Debian Stretch 가 2017-02-05: Full freeze 되었습니다. Debian Stretch 가 조만간 stable 가 된다는 의미입니다. 따라서 Debian Jessie 에서 신버전의 nimf 를 사용못하게 되더라도 wayland 모듈을 조만간 추가할 계획입니다. 더 이상 wayland 모듈 개발을 연기하지 않습니다. 확정입니다.

**Comment by cogniti** [comment]
일단, 만들기는 콜백을 제외하고 거의 다 만들었습니다. 그런데,

현재 버전의 weston 에서는, weston 이 시작하면서 weston 이 nimf-daemon 을 시작시켜야 되는데 문제가 좀 있습니다.

문제점 1
weston 이 시작하면서 input-method 를 시작시켜야 input-method 가 weston 에 바인딩됩니다.
weston 이 가동 중에 input-method 를 시작시키면 바인딩이 되지 않습니다.

문제점 2
weston 이 시작하면서 nimf-daemon 을 시작시키도록 하면, `wl_display_dispatch_pending()`할 때 에러가 납니다. `$HOME/.config/weston.ini` 에

```
[input-method]
#path=/home/hodong/wayland
#path=/home/hodong/Downloads/weston_1.12.0.orig/weston-1.12.0/weston-simple-im
path=/usr/local/bin/nimf-daemon
#path=/home/hodong/simple-im
```

이런 식으로 작성하면 path 에 있는 프로그램이 실행이 되는데... 인자(argument)를 전달할 수가 없습니다.
`nimf-daemon --no-daemon` 이런 식으로 `--no-daemon` 인자를 전달할 수 없습니다.
`nimf-daemon.c` 를 변경하여 항상 `--no-daemon` 으로 실행되도록 하였는데도...
바인딩이 되지만,  `wl_display_dispatch_pending()`할 때 에러가 납니다.

어떠한 이유인지는 잘 모르겠지만,
https://lists.freedesktop.org/archives/wayland-devel/2013-April/008546.html
위 링크에 있는 체크 코드 때문입니다.

결국 weston 에 있는 체크 코드를 아래처럼 주석 처리한 후에 시도해보니 바인딩이 되어 작동 되는군요.

```
/*
	if (text_backend->input_method.client != client) {
		wl_resource_post_error(resource,
				       WL_DISPLAY_ERROR_INVALID_OBJECT,
				       "permission to bind "
				       "input_method denied");
		return;
	}
*/
```
weston 외에 마땅히 테스트할 composite 가 없습니다.
실제로 weston 을 사용하시는 분이 계신지 모르겠습니다.
weston 에서 nimf 를 사용하기 위해서는
1. weston 소스코드를 위에처럼 주석 처리하거나
2. nimf-wayland-im 등의 적절한 이름의 클라이언트 실행형 파일을 만들어야 합니다.
무슨 말이냐면,
https://github.com/freedesktop/wayland-weston/blob/master/clients/simple-im.c
가 있는데 `main()` 함수가 있습니다. 컴파일하면 실행형 파일이 됩니다.
그 소스를 고쳐서 `nimf-im.h` 있는 클라이언트용 nimf 함수를 호출하도록 하면 nimf-daemon 과 통신하면서 입력할 수 있습니다. `nimf/modules/clients` 에 있는 gtk, qt 모듈이 클라이언트 모듈입니다.
단, weston 의 경우는 `main ()` 를 넣어서 실행형 파일을 만들어야 하는 것이 차이점이죠.

일단 며칠내로 nimf-wayland 모듈을 추가할 것입니다. 이 모듈은 weston 코드 수정 없이는 weston 에서 작동하지 않습니다만,
만약 또 다른 wayland compositor 가 존재한다면 nimf-wayland 가 잘 작동할 것으로 기대하고 있습니다.
nimf 를 weston 에서 작동시키기 위한 클라이언트 실행 파일을 원하시는 분은 별도로 이슈를 올려주시기 바랍니다.

**Comment by cogniti** [comment]
![screenshot from 2017-03-24 00-45-41](https://cloud.githubusercontent.com/assets/17453239/24258940/9826ef1c-1032-11e7-9f78-e2d78f9b354f.png)

**Comment by sukso96100** [comment]
Liri OS(https://liri.io/) 에 들어가는 데스크탑 셸이 Wayland 에 Greenisland 컴포지터 계승(?) 받아 개발하는 자체 컴포지터(https://github.com/lirios/wayland) 사용하는 것으로 알고 있어요, 작업에 참고 하시면 좋을 것 같습니다.

**Comment by cogniti** [comment]
xwayland 환경에서 오작동하는 문제가 해결되었습니다.

Forced GDK backend to x11 (issue #25)
https://github.com/cogniti/nimf/commit/1106b51ee196806eaad22d773ae6fc2d92fa94da
