### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by vaporize93** [cogniti/nimf#28]
my system is arch linux  / gnome3  / xorg
build fail with aura, source build both.

> ✘ harvey@lenovo  ~  sudo aura -A nimf-git
> aura >>= Determining dependencies...
> aura >>= AUR Packages:
> nimf-git
> 
> aura >>= Continue? [Y/n] Y 
> aura >>= Building `nimf-git`...
> aura >>= Well, building `nimf-git` failed.
> aura >>= Dumping makepkg output in 3.. 2.. 1..
> ==> Making package: nimf-git 2016.09.26.55363fd-1 (Fri Oct 28 18:08:50 KST 2016)
> ==> Checking runtime dependencies...
> ==> Checking buildtime dependencies...
> ==> Retrieving sources...
>   -> Cloning nimf git repo...
> Cloning into bare repository '/var/cache/pacman/pkg/nimf-git7934/nimf-git/nimf'...
> ==> Validating source files with md5sums...
>     nimf ... Skipped
> ==> Extracting sources...
>   -> Creating working copy of nimf git repo...
> Cloning into 'nimf'...
> done.
> ==> Starting pkgver()...
> ==> Updated version: nimf-git 2016.09.26.cc53a22-1
> ==> Starting build()...
> autoreconf: Entering directory `.'
> autoreconf: configure.ac: not using Gettext
> autoreconf: running: aclocal --force -I m4
> autoreconf: configure.ac: tracing
> autoreconf: configure.ac: creating directory build-aux
> autoreconf: running: libtoolize --copy --force
> autoreconf: running: /usr/bin/autoconf --force
> autoreconf: running: /usr/bin/autoheader --force
> autoreconf: running: automake --add-missing --copy --force-missing
> configure.ac:13: installing 'build-aux/ar-lib'
> configure.ac:13: installing 'build-aux/compile'
> configure.ac:42: installing 'build-aux/config.guess'
> configure.ac:42: installing 'build-aux/config.sub'
> configure.ac:9: installing 'build-aux/install-sh'
> configure.ac:9: installing 'build-aux/missing'
> Makefile.am: installing './INSTALL'
> daemon/Makefile.am: installing 'build-aux/depcomp'
> autoreconf: Leaving directory `.'
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/^(._)\${ <-- HERE ?([A-Z_]+)}?(._)$/ at /usr/bin/intltool-update line 1065.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1193.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1194.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1195.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1196.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_NAME}?/ at /usr/bin/intltool-update line 1222.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?PACKAGE}?/ at /usr/bin/intltool-update line 1223.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?AC_PACKAGE_VERSION}?/ at /usr/bin/intltool-update line 1224.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?VERSION}?/ at /usr/bin/intltool-update line 1225.
> Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ?\w+}?/ at /usr/bin/intltool-update line 1226.
> nimf-candidate.c: In function ‘nimf_candidate_show_window’:
> nimf-candidate.c:337:3: error: ‘gdk_screen_width’ is deprecated [-Werror=deprecated-declarations]
>    if (x + w > gdk_screen_width ())
>    ^~
> In file included from /usr/include/gtk-3.0/gdk/gdk.h:50:0,
>                  from /usr/include/gtk-3.0/gtk/gtk.h:30,
>                  from nimf-candidate.c:23:
> /usr/include/gtk-3.0/gdk/gdkmain.h:108:6: note: declared here
>  gint gdk_screen_width  (void) G_GNUC_CONST;
>       ^~~~~~~~~~~~~~~~
> nimf-candidate.c:338:5: error: ‘gdk_screen_width’ is deprecated [-Werror=deprecated-declarations]
>      x = gdk_screen_width () - w;
>      ^
> In file included from /usr/include/gtk-3.0/gdk/gdk.h:50:0,
>                  from /usr/include/gtk-3.0/gtk/gtk.h:30,
>                  from nimf-candidate.c:23:
> /usr/include/gtk-3.0/gdk/gdkmain.h:108:6: note: declared here
>  gint gdk_screen_width  (void) G_GNUC_CONST;
>       ^~~~~~~~~~~~~~~~
> nimf-candidate.c:340:3: error: ‘gdk_screen_height’ is deprecated [-Werror=deprecated-declarations]
>    if (y + h > gdk_screen_height ())
>    ^~
> In file included from /usr/include/gtk-3.0/gdk/gdk.h:50:0,
>                  from /usr/include/gtk-3.0/gtk/gtk.h:30,
>                  from nimf-candidate.c:23:
> /usr/include/gtk-3.0/gdk/gdkmain.h:110:6: note: declared here
>  gint gdk_screen_height (void) G_GNUC_CONST;
>       ^~~~~~~~~~~~~~~~~
> cc1: all warnings being treated as errors
> make[3]: **\* [Makefile:795: libnimf_la-nimf-candidate.lo] Error 1
> make[2]: **\* [Makefile:556: all] Error 2
> make[1]: **\* [Makefile:504: all-recursive] Error 1
> make: **\* [Makefile:436: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...

**Comment by cogniti** [comment]
I will solve the issue in January 2017.
