### ISSUE TITLE
Change input method for Vi editor?

### ISSUE THREAD

**Issue by junshoong** [cogniti/nimf#30]
Nimf를 사용하면서 vim을 사용하는 경우 한글을 입력하다가 입력모드에서 나오는 경우 한글 입력 상태가 유지됩니다.  
vi 에디터, 플러그인을 사용하는 한글 사용자의 경우에는 ESC 버튼을 누를 때 한글에서 영어로 바뀌는 기능이 유용합니다.  UIM 벼루를 사용할때 이런 기능이 편리했었는데 혹시 이런 기능이 설정에 있는지, 없으면 추가를 요청 드립니다.

**Comment by cogniti** [comment]
일단 `nimf-system-keyboard` 에 `trigger-keys` 옵션을 추가하여 기본값으로 `Escape`로 하였습니다.
그러나 `rime`에서 `Escape`를 사용하기 때문에 나중에 `nimf-system-keyboard` 에 `trigger-keys` 옵션의 기본값을 공백으로 둘 예정입니다. 그리고 `nimf-libhangul`에 적절한 옵션을 추가하겠습니다.

**Comment by vaporize93** [comment]
빠른 피드백 감사드립니다.  
`Trigger-keys`에 `Escape`를 두는 경우에는 한글 -> 영어 뿐 아니라 영어 -> 한글로도 변하게 되지 않을까요?  한글입력기 설정에서만 사용가능한 한글 -> 영어로만 전환될 수 있는 개별적인 Trigger 옵션을 주어야 하지 않을까요?

**Comment by cogniti** [comment]
`nimf-libhangul`이 아니라 `nimf-system-keyboard` 에 `trigger-keys` 옵션입니다.

**Comment by cogniti** [comment]
현재 코드를 컴파일하시면 원하시는 결과를 얻을 수 있을 것 같습니다. 그러나 `nimf-system-keyboard`에 `trigger-keys` 옵션을 추가하고 키값을 `Escape`로 할당할 경우, `nimf-rime`에서 `Escape` 키값을 사용하지 못하게 됩니다. 따라서 `nimf-libhangul`에 `switch-to-system-on-esc` 옵션을 추가하여 기본 키값으로 `Escape` 키를 할당하고 `nimf-libhangul`에서 `Escape` 키가 눌러졌을 경우, system keyboard 로 엔진을 전환시키고 `FALSE`를 리턴하면 될 것 같습니다. 간단한 작업이지만, 올해는 개인사정으로 인하여 처리가 불가하고 내년이나 내후년 명절에 처리하겠습니다.

**Comment by cogniti** [comment]
`Escape`를 할당할 경우, `FALSE`를 리턴해야 하는데 수정한 코드가 그렇지 않은 것 같고 `nimf-rime`에서 문제가 발생하므로 원래 코드로 되돌렸습니다.

**Comment by vaporize93** [comment]
저도 몇가지 테스트를 해보고 있었는데요,
`Escape`를 할당하는 경우 Terminal의 vim에서와 `pycharm`의 vim 플러그인에서 입력모드에서 일반모드로 ESC를 누르는 경우 정상적으로 동작하지 않아 입력모드에 머무르게 되는 현상이 있었습니다. `Eclipse`에서는 한글인 경우에만 `ESC`입력이 정상 작동했습니다. 그리고 `gnome`왼쪽 상단에 있는 `Activities`를 누른 뒤 전환되는 화면에서도 `Escape`로 나올 수 없었습니다.  
System Keyboard에서 `Escape`를 할당하는 경우 `Escape`가 정상적으로 작동하지 않는 문제가 있는 걸로 보입니다. 일단은 해당 부분 해제한 상태로 사용하도록 하겠습니다.  
늦은 시간에도 빠른 확인과 피드백 감사드립니다. :smiley:

**Comment by cogniti** [comment]
해당 기능을 다시 고러해봤는데요..
ESC 키를 눌렀을 때 시스템키보드(영문)으로 전환되게 하면 vi 뿐만 아니라 다른 여러 프로그램을 사용할 때도 ESC를 누르면 영문으로 전환되는데 이 옵션을 추가하면 오히려 불편해질 수 있습니다.
이 기능이 정말 필요한지 다시 묻고 싶습니다.
이 기능 추가에 부정적인 입장입니다.

**Comment by cogniti** [comment]
그리고 일반적인 경우 ESC를 누를 경우 영문으로 전환되지 않으므로 vi 사용하면서 ESC 를 누른 후에 영문으로 전환하여 사용하는데, 이 기능을 추가하여 켜 놓고 사용하면, 타 어플 사용하면서 ESC 를 눌러야 하는 경우가 상당히 발생하는데 ESC 누른 후에 다시 한글로 전환해야 하는 불편이 뒤따릅니다.
그래서 사용자 입장에서 vi 사용할 때와 타 어플 사용할 때의 동작을 신경써야 하는데 이게 오히려 헷갈릴 수 있습니다. 다른 분들의 생각은 어떻습니까?

**Comment by cogniti** [comment]
해당 기능을 다시 고려해봤는데,
약간의 코드 수정을 통하여 nimf gtk, nimf qt im 모듈에 실행 중인(또는 입력을 당하고 있는) 프로그램(프로세스)의 이름을 nimf 서버에 보낼 수 있는 방법이 있긴 있습니다.
그래서 특정 옵션이 특정 프로그램 돌릴 때만 작동되도록 하는 방법도 있긴 한데,
vi 입력의 경우, vi, vim 외에 kate 에서 vi 입력 모드 등이 있어서 특정 프로그램에서만 선택적으로 작동되도록 하면 kate 같은 경우에 의도하지 않게 작동하므로 그러한 점이 불편한 점으로 느껴지게 됩니다.

따라서 이러한 기능은 입력기에서 트릭을 이용하여 구현하는 것보다,
vi 관련 어플에서 구현하는 것이 올바르다고 생각합니다.

**Comment by cogniti** [comment]
기존 코드 다시 추가하고 ESC 일 때 체크해서 , return FALSE 해주면 될 것 같네요.
그런데 부작용 감안하고 사용하셔야 되요.
조만간 업데이트 하겠습니다.
