### ISSUE TITLE
특수문자 입력시 빈 창만 보이는 문제가 있습니다.(libhangul-data 관련)

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#31]
안녕하세요, 오랜만에 인사올립니다.
올 한해도 얼마 남지 않았네요. 건강 유의하시길 기원합니다.

Nimf 사용 시 한글 자음(ㄱ~ㅎ)을 입력하고 한자변환글쇠를 사용해서 특수 문자를 입력할 수 있는데요.
우분투 16.04/10 에서 Nimf 최신판을 사용해서 이 기능을 사용하면, 빈칸만 보이는 현상이 있습니다.

이리저리 실험해보니 제가 보기엔 libhangul-data 와 관련된 문제인 것 같은데요.
우분투 저장소에서 제공하는 libhangul-data 는 0.1.0-3 인데, 이것과 Nimf 를 사용했을 경우엔 이런 문제가 있습니다.

Floor PPA(https://launchpad.net/~createsc/+archive/ubuntu/3beol) 에는 0.1.0-3.6 이 제공되고 있는데요, 이 꾸러미만 수동으로 설치했을 경우 이 문제가 없어졌습니다.

좀 애매한 것은, fcitx 에선 libhangul-data 0.1.0-3 과도 문제가 없었다는 점인데요.
시간 되실 때 한번 살펴봐주시면 좋겠습니다.

차가운 날씨, 감기 조심하시길~

**Comment by cogniti** [comment]
아래의 명령으로 `mssymbol.txt` 파일이 시스템에 설치되어 있는지 확인하세요.
`ls /usr/share/libhangul/hanja/mssymbol.txt`

만약 없다면 아래의 명령으로 `mssymbol.txt` 파일을 복사해주세요.

```
wget https://raw.githubusercontent.com/choehwanjin/libhangul/master/data/hanja/mssymbol.txt

sudo mv mssymbol.txt /usr/share/libhangul/hanja/
```
