### ISSUE TITLE
의존성 문의 드립니다.

### ISSUE THREAD

**Issue by YoungHoonZo** [cogniti/nimf#34]
안녕하세요. 
mint18 KDE를 설치하고 nimf를 설치 하려고 시도 했더니 qtbase-abi-5-5-1 이 패키지의 의존성을 도무지 해결을 하지 못하고 있습니다. 
apt-get install qtbase-abi-5-5-1 를 하게 되면 

qtbase-abi-5-5-1 패키지는 다음이 제공하는 가상 패키지입니다:
  libqt5core5a 5.5.1+dfsg-16ubuntu7.2[후보 버전 아님]
  libqt5core5a 5.5.1+dfsg-16ubuntu7[후보 버전 아님]

E: 'qtbase-abi-5-5-1' 패키지는 설치할 수 있는 후보가 없습니다

이렇게 나오면서 진행이 되지 않고 있습니다.

**Comment by cogniti** [comment]
안녕하세요.
`libqt5core5a`(5.5.1) 을 설치하면 되지 않나요?

**Comment by YoungHoonZo** [comment]
그것도 해봤는데요
libqt5core5a is already the newest version (5.6.1+dfsg-3ubuntu7~~xenialoverlay1~2).
다음 패키지가 자동으로 설치되었지만 더 이상 필요하지 않습니다:
  oxygen5-icon-theme qtdeclarative5-xmllistmodel-plugin xsane-common

상위버전은 설치되어 있는데, 설치가 되지 않습니다.

**Comment by cogniti** [comment]
시스템 마다 차이가 있는 것 같은데..
제가 타인의 시스템이 맞게 패키지를 만들어 드리는 것은 시간적, 금전적 손실이 발생하기 때문에 매우 곤란합니다.

http://cogniti.github.io/nimf/support/ 에 패키지 만드는 방법이 있습니다.
직접 패키지를 만드시거나 Mint 프로젝트에 nimf 를 패키지 달라고 요청하시는 것이 좋겠습니다.

도움이 못 되어서 죄송합니다.

**Comment by YoungHoonZo** [comment]
아닙니다. 
만들어 주신것만도 
감사 합니다.

알겠습니다.
패키지를 만들던가 해볼게요. ^^
