### ISSUE TITLE
wine 을 이용한 카카오톡 실행시 한글 입력에 문제가 있습니다.

### ISSUE THREAD

**Issue by 5HARK** [cogniti/nimf#35]
https://ask.ubuntu-kr.org/?qa=240/wine%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-line%EC%9D%84-%EC%82%AC%EC%9A%A9%EC%A4%91%EC%9D%B8%EB%8D%B0-%ED%95%9C%EA%B8%80%EC%9D%B4-%EC%A0%9C%EB%8C%80%EB%A1%9C-%EC%9E%85%EB%A0%A5%EC%9D%B4-%EC%95%88%EB%90%A9%EB%8B%88%EB%8B%A4

 위 링크 글에서와 증상이 유사한데요.

`동해물과백두산이`
라고 입력하면,

![image](https://cloud.githubusercontent.com/assets/12772303/22192719/acb7a09e-e179-11e6-95e9-830389458f09.png)

이런식으로 입력됩니다. 여러가지 설정도 바꿔보고 했는데 도무지 감이 안잡히네요. 어딜 살펴봐야 문제를 해결할 수 있을지

**Comment by cogniti** [comment]
전에 제가 테스트했을 때 정상적으로 작동했습니다.
카카오톡 버전이 올라가면서 발생하는 문제인가요?
wine 에 notepad.exe 있을거에요. 그 프로그램으로는 어떤가요?

**Comment by chiwanpark** [comment]
Arch Linux / Wine 2.0 (32bit) / KakaoTalk 2.5.2.1427에서는 정상적으로 한글 입력이 가능합니다.

**Comment by sukso96100** [comment]
Arch Linux (64bit) / Wine 2.0 (64bit) / KakaoTalk 2.5.2.1427 에서도 동일한 현상이 발생합니다.
![2017-01-26 17-28-16](https://cloud.githubusercontent.com/assets/1916739/22324475/dad79112-e3ec-11e6-9919-2f7673857749.png)

**Comment by cogniti** [comment]
wine 에 notepad.exe 있을거에요. 그 프로그램으로는 어떤가요?

**Comment by sukso96100** [comment]
`notepad` 에서는 별 다른 문제 없이 잘 입력 됩니다.
![2017-01-26 17-35-38](https://cloud.githubusercontent.com/assets/1916739/22324648/e137b770-e3ed-11e6-9533-a846b9b8bfc0.png)

**Comment by cogniti** [comment]
하나만 더 확인해주세요.
fcitx 로 kakaotalk 했을 때, 어떤가요?

**Comment by sukso96100** [comment]
저는 지금 fcitx 설치가 지금 안 되어 있는 상태라, 오늘 안으로 확인 후 알려드리겠습니다.

**Comment by sukso96100** [comment]
조금 전에 Fcitx 로 카카오톡과 notepad 에서 입력해 봤는데, 잘 입력됩니다. 다만 글자 조합 상자가 커서 아래에 나타나서 상자 안에서 만들어진 글자가 입력됩니다.
![2017-01-27 11-01-53](https://cloud.githubusercontent.com/assets/1916739/22358194/8e1a604a-e480-11e6-8ac3-036125ea9511.png)

**Comment by cogniti** [comment]
wine 사용하여 입력할 때, fcitx 처럼 조합 중인 글자를 나타내는 작은 창이 떠야하는 것이 정상입니다. 그것을 아직 구현하지 않았습니다.
Debian Jessie 에 카카오톡을 설치하였는데 한글 폰트 설정을 하지 못하여 Debian Stretch 출시 이후로 미루겠습니다.

**Comment by cogniti** [comment]
카카오톡 실행시에 에러가 발생하여 어떻게 하지를 못하겠습니다.
Wine에서 실행한 카카오톡을 제외한, XIM 을 사용하는 다른 애플리케이션(예, LibreOffice, Android Studio, 우분투 런처 등)에서는 문제가 없습니다.
시간 관계상 카카오톡 문제는 확인하지 않겠습니다.

![screenshot_2017-03-14-01-27-20](https://cloud.githubusercontent.com/assets/17453239/23864419/d5128d26-0855-11e7-8896-366273ccea5d.png)

![screenshot from 2017-03-14 01-26-43](https://cloud.githubusercontent.com/assets/17453239/23864345/8fb30a26-0855-11e7-840c-78e5925c7ed2.png)

**Comment by cogniti** [comment]
@5HARK 님 사용 환경이 어떻게 되나요? 배포판과 wine 버전을 알고 싶습니다.

**Comment by cogniti** [comment]
다시 확인해봤는데 재현이 되지 않습니다.
님프 문제가 아닌 것 같습니다. 아마 다른 부분에 문제가 있을 겁니다.
참고로 ibus, fcitx, nimf 는 XIM 기능을 위해 IMdkit 라는 라이브러리를 사용하고 있습니다.
ibus, fcitx, nimf 프로젝트 마다 약간의 상이한 패치가 적용되었지만 그로 인하여 발생하는 문제는 아닐 것입니다.
그리고 과거 다솜(Dasom)에서 와인에 카카오톡 이용시에 글자가 뒤죽박죽된다는 얘기가 있었던 것 같은데...
그 당시 데비안에서 테스트해본 결과 아무 문제가 없었습니다. 지금도 nimf 문제가 없고요.

다만, 입력할 때 조합 중인 글자가 표시되지 않는 것은... nimf 에 그 부분을 덜 구현했기 때문입니다.
그 부분은 따로 이슈를 올려주시거나 제가 시간날 때 천천히 구현하도록 하겠습니다.

유튜브 입력 영상 https://youtu.be/20uiu_EmVBY

```
hodong@debian:~$ wine --version
wine-2.0 (Debian 2.0-3)

hodong@debian:/etc$ cat os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

PlayOnLinux 4.2.10
카톡 버전 Ver. 2.5.4.1479
![2017-03-26 01-12-44](https://cloud.githubusercontent.com/assets/17453239/24323969/5ee4f5b0-11c1-11e7-9765-d9d58f96487b.png)

**Comment by cogniti** [comment]
혹시나 싶어서 wine64 에 설치해봤는데 입력 잘 됩니다.
![screenshot from 2017-04-07 22-09-31](https://cloud.githubusercontent.com/assets/17453239/24801403/0f619886-1bdf-11e7-9867-b99ba757f649.png)

**Comment by cogniti** [comment]
Debian Stretch stable 출시 후에 다시 테스트해봤는데 잘 됩니다.
wine-2.0.1
![2017-07-10 22-25-07](https://user-images.githubusercontent.com/17453239/28020260-a6ba62b6-65be-11e7-96ef-770591864be7.png)

![2017-07-10 22-22-45](https://user-images.githubusercontent.com/17453239/28020223-853de4d2-65be-11e7-95de-2d8f41133bff.png)

**Comment by cogniti** [comment]
아치 리눅스와 유사한 만자로(manjaro) 리눅스에서도 잘 되네요.

```
[hodong@Manjaro ~]$ wine --version
wine-2.11
```
![screenshot_20170712_081703](https://user-images.githubusercontent.com/17453239/28094922-8fe7f89c-66da-11e7-9263-1fa361d5a248.png)

**Comment by cogniti** [comment]
어제, 오늘 아치 리눅스 설치하여 테스트를 했습니다.
GNOME, xorg 환경입니다. wayland 기반에서는 nimf 뿐만 아니라, 파이어폭스, GNOME 몇몇 프로그램 등이 정상적으로 작동하지 않았습니다.

아래는 GNOME, xorg 환경에서 테스트한 것입니다.
결론은 잘 됩니다.
wine 이 win64 모드로 돌아가도록 playonlinux 설치할 때 64비트 선택하여 카카오톡을 설치하였습니다.
참고로 카카오톡 exe 파일은 32비트 밖에 없습니다. 그러니까.. 64비트 Windows 에서 카카오톡을 돌린 겁니다.
잘 됩니다. nimf 문제가 아닙니다.

데비안, 우분투, 만자로, 아치 리눅스에서 정상적으로 작동하는 것을 확인하였습니다.
모두 가상 머신이 아닌, 물리적인 컴퓨터에 직접 설치하여 테스트하였습니다.

![screenshot from 2017-07-14 00-10-18](https://user-images.githubusercontent.com/17453239/28173591-ddeeb1e8-6829-11e7-8fec-49fcf408af87.png)

```
[hodong@archlinux ~]$ wine --version
wine-2.12

[hodong@archlinux ~]$ playonlinux --version
PlayOnLinux 4.2.10
```

**Comment by cogniti** [comment]
fcitx 는 wayland 에서도 잘 되는군요..
nimf 에서.. 입력할 때 조합 중인 글자가 표시되는 창을 재구현하도록 하겠습니다.

**Comment by cogniti** [comment]
로케일을 한글로 했을 때 문제가 발생하는군요. 재현했습니다.
조만간 수정될 예정입니다.

**Comment by cogniti** [comment]
`XIMPreeditCallbacks을 무시합니다(Ignore XIMPreeditCallbacks)`라는 옵션을 만들었습니다.
wine 사용할 때 그 옵션을 켜고 사용하세요. 그외에 사용할 때는 도로 끄시면 되겠습니다.
wine 버그입니다.

![2017-07-15 23-32-19](https://user-images.githubusercontent.com/17453239/28240176-3618f43a-69b7-11e7-933a-a02616df8e88.png)

![2017-07-15 23-39-19](https://user-images.githubusercontent.com/17453239/28240157-f556846c-69b6-11e7-823a-f884e1acfeda.png)

입력 스타일 참고 자료
https://www-archive.mozilla.org/projects/intl/input-method-spec.html

**Comment by cogniti** [comment]
xwayland 환경에서 오작동하는 문제가 해결되었습니다.

Forced GDK backend to x11 (issue #25)
https://github.com/cogniti/nimf/commit/1106b51ee196806eaad22d773ae6fc2d92fa94da

**Comment by cogniti** [comment]
XIM 옵션 이름을 변경했습니다. 이용에 참고 바랍니다.
```
Always draw preedit string on the server-side
항상 서버 측에서 사전 편집 문자열을 그립니다
```
![2018-01-10 07-31-57](https://user-images.githubusercontent.com/17453239/34746710-6569a65a-f5d8-11e7-80f9-14130e2b5a41.png)
