### ISSUE TITLE
xterm이나 urxvt 에서 한글입력은 안되나요?

### ISSUE THREAD

**Issue by queenmedley** [cogniti/nimf#36]
Archlinux 사용하고 있구요
ibus 같은 경우  .Xresource에
URxvt.inputMethod: ibus
URxvt.preeditType: OverTheSpot 
 하면 한글입력이 된다고 되어 있는데 nimf는 안되네요...

**Comment by cogniti** [comment]
데비안 Jessie 에 xterm, urxvt 설치하여 한글을 입력해 보았는데, 별다른 설정없이 한글 입력이 됩니다.
제가 아치리눅스를 사용하지 않는 관계로 아치리눅스 커뮤니티쪽에 문의하시기 바랍니다.
감사합니다.
![screenshot from 2017-01-27 19 53 17](https://cloud.githubusercontent.com/assets/17453239/22358035/783c3182-e47f-11e6-9e4e-9806d6a0639a.png)
![screenshot from 2017-01-27 19 56 22](https://cloud.githubusercontent.com/assets/17453239/22358037/7c6141c6-e47f-11e6-8c86-86b3c9405424.png)
