### ISSUE TITLE
Support multi-user environment

### ISSUE THREAD

**Issue by yueunseon** [cogniti/nimf#37]
본 계정에 세벌식 서브계정에 두벌식을 설정했습니다.

본 계정으로 로그인한 상태에서 서브 계정으로 사용자 전환을 하면

본 계정의 입력기 상태 (그냥 한국어 상태냐 한국어 101/104키 호환 상태냐) 그리고 입력기 설정 (두벌식이냐 세벌식이냐)를 그대로 따릅니다.

본계정에서 세벌식 쓰고 있으면 서브계정으로 전환 후에도
서브계정은 설정이 두벌식으로 되어 있지만 세벌식으로 써지구요.

반대로 본 계정을 로그아웃 하고 
서브 계정에 먼저 로그인 후에 
본 계정으로 사용자 전환을 하면
본계정에서는 기본 설정과 상관없이 서브계정의 두벌식이 써집니다.

최초 로그인한 계정을 로그아웃하지 않고 사용자전환을 하면 
최초 계정의 설정을 전환한 사용자 계정에서 그대로 써 집니다.

하나를 로그아웃 하지 않으면 하나의 입력기로 두벌식과 세벌식을 따로 쓸 수가 없고,
전환된 사용자가 최초 로그인한 계정 설정을 따름으로 인한 최초 계정 중간 로그아웃 후 오류도 있는것같아요.

우분투의 사용자전환의 특성으로 인한 필연적인 오류인가요?

**Comment by yueunseon** [comment]
설명이 이상한가요 ㅜ.ㅜ
로그아웃 하고 다른 계정 로그인시에는 아무 문제 없는데요.
그냥 사용자전환을 하면 설정이 꼬이나봐요.

**Comment by cogniti** [comment]
버그 제보 감사합니다.
무슨 말씀인지 이해했습니다.
nimf 버그입니다.

**Comment by cogniti** [comment]
님프 서버에 사용자 세션을 생성하도록 하고 부팅시에 서버를 실행시키면 좋은데 그렇게 변경하려면 시간이 오래 걸립니다.
그래서 사용자 별로 서버가 실행되도록 변경하겠습니다. unix abstract 주소만 바꾸면 되는 간단한 작업이기 때문에 3월까지는 해결될 것입니다.

**Comment by yueunseon** [comment]
감사합니다. 좋은 하루되시길 바랍니다 ^^
