### ISSUE TITLE
우분투 16.04 PPA 한글 입력 안 됨.

### ISSUE THREAD

**Issue by parkmino** [cogniti/nimf#42]
오랜만에 확인해 보니 우분투 PPA에 올려 놓으셨더라구요.
반가운 마음에 설치해 보았는데, 시스템이 느려지면서 한글 입력이 안되네요.
일단 이전에 쓰던 Elementary OS PPA 버전으로 돌려 놓았습니다.

```
$ nimf-daemon --no-daemon --debug
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:755: nimf_server_new
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:729: nimf_server_class_init
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:583: nimf_server_init

(nimf-daemon:11166): GLib-GIO-ERROR **: Settings schema 'org.nimf' does not contain a key named 'disable-fallback-filter-for-xim'
Trace/breakpoint trap (core dumped)
```

**Comment by cogniti** [comment]
`disable-fallback-filter-for-xim`이 키는 2017.01.27 에 삭제되었습니다.

https://github.com/cogniti/nimf/commit/0490398486784f447bc15d7478c5e115003c6ccc#diff-2565d47739c5212077e6f73c47befc35

아마 설치가 잘못된 듯합니다.
아래 파일로 설치해보세요.

https://launchpad.net/~hodong/+archive/ubuntu/nimf/+files/nimf_2017.03.27.1~xenial_amd64.deb
https://launchpad.net/~hodong/+archive/ubuntu/nimf/+files/nimf_2017.03.27.1~xenial_i386.deb

**Comment by parkmino** [comment]
저도 관련 키가 없는 것은 확인했는데, 위 파일을 설치해도 계속해서 오류가 나네요.
일단 nimf_2016.08.06-0+r495-daily-ubuntu0.4.1_amd64.deb 파일은 문제가 없어서 사용하고 있습니다.
기존 설치에서 잔재(?)가 남아서인지는 모르겠지만 똑 같은 증상이네요.

**Comment by cogniti** [comment]
위 파일을 설치한 후에

`nimf-daemon --version` 해보시고 출력되는 버전을 알려주세요.

**Comment by cogniti** [comment]
위 파일 설치 후에 아래처럼 나와야 정상입니다.

```
hodong@debian:~/Downloads$ nimf-daemon --version
nimf-daemon 2017.03.27
hodong@debian:~/Downloads$ 
```

**Comment by parkmino** [comment]
넵, 정상입니다.
nimf-daemon은 실행되지 않고, 전반적으로 시스템 반응이 느려지네요.

**Comment by cogniti** [comment]
우분투 16.04 에서 확인해 봤는데, 잘 됩니다.

![screenshot from 2017-04-07 22-34-34](https://cloud.githubusercontent.com/assets/17453239/24802484/2b7780cc-1be3-11e7-8f4d-c60b9198d086.png)

기존에 설치한 파일들이 삭제가 되지 않았을 것 같은데 모두 삭제 후에 다시 설치하시면 잘 될 것 같습니다.

```
sudo apt-get --purge remove nimf
sudo find / | grep nimf
sudo find / | grep Nimf
nimf 관련 파일들을 수동으로 모두 삭제하셔야 합니다.
```

그리고, `2017.03.27` 을 설치하였는데 아래처럼 나오면... 설치가 잘못 되었다고 볼 수 있습니다.

```
$ nimf-daemon --no-daemon --debug
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:755: nimf_server_new
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:729: nimf_server_class_init
(nimf-daemon:11166): nimf-DEBUG: nimf-server.c:583: nimf_server_init

(nimf-daemon:11166): GLib-GIO-ERROR **: Settings schema 'org.nimf' does not contain a key named 'disable-fallback-filter-for-xim'
Trace/breakpoint trap (core dumped)
```

nimf-daemon 2017.03.27 버전에서는 `disable-fallback-filter-for-xim` 키를 읽지 않습니다.
`disable-fallback-filter-for-xim`이 키는 이미 2017.01.27 에 삭제되었습니다.

https://github.com/cogniti/nimf/commit/0490398486784f447bc15d7478c5e115003c6ccc#diff-2565d47739c5212077e6f73c47befc35

nimf 2017.03.27 소스코드에 그 키가 없으며 읽지도 않습니다.

```
hodong@debian:~$ ls
backup   Documents  Music  Pictures                      Public     Videos
Desktop  Downloads  nimf   PlayOnLinux's virtual drives  Templates
hodong@debian:~$ cd nimf
hodong@debian:~/nimf$ grep fallback -R
hodong@debian:~/nimf$ 
```

**Comment by parkmino** [comment]
감사합니다.
말씀해주신 방법으로 해결하였습니다!

**Comment by cogniti** [comment]
다행이군요... 즐거운 리눅스 생활되세요
