### ISSUE TITLE
Evince 최신 버전에서 늦게 뜸.

### ISSUE THREAD

**Issue by parkmino** [cogniti/nimf#43]
Evince가 최신 3월27일 날짜로 업데이트한 이후로 너무 늦게 뜨네요.
이전 이슈는 해결된 걸로 나오는데, 뭐가 바뀌어서 그런가요?
https://github.com/cogniti/nimf/issues/1
위 이슈에서의 해결책은 적용이 된 걸로 보입니다만.

$ evince

(evince:5192): nimf-CRITICAL **: nimf-client.c:252: nimf_client_constructed: Could not connect: Permission denied

(evince:5192): nimf-CRITICAL **: nimf-client.c:252: nimf_client_constructed: Could not connect: Permission denied

(evince:5192): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed

(evince:5192): nimf-WARNING **: socket is closed

(evince:5192): nimf-CRITICAL **: nimf-client.c:252: nimf_client_constructed: Could not connect: Permission denied

(evince:5192): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed

(evince:5192): nimf-WARNING **: socket is closed

(evince:5192): nimf-CRITICAL **: nimf-client.c:252: nimf_client_constructed: Could not connect: Permission denied

(evince:5192): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed

(evince:5192): nimf-WARNING **: socket is closed

(evince:5192): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed

(evince:5192): nimf-WARNING **: socket is closed

그리고 관리자 권한에서는 아예 실행이 되지 않는데, 이게 정상인가요?

$ sudo evince
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
Cannot parse arguments: Cannot open display:

**Comment by cogniti** [comment]
우분투에서 evince 늦게 뜨는 문제는
`/etc/apparmor.d/usr.bin.evince` 파일을 [usr.bin.evince.txt](https://github.com/cogniti/nimf/files/906733/usr.bin.evince.txt) 로 교체하면 됩니다. 파일 이름을 `usr.bin.evince` 로 해주셔야 합니다.
https://wiki.debian.org/Adding%20and%20removing%20diversions
방법을 적용하려고 했는데 `usr.bin.evince` 라이선스가 GPL 로 추정되어 nimf 저장소에 넣지를 못합니다.

그리고 root 권한으로 실행하면 늦는 문제는, 버그입니다.
`getuid()` 함수 대신에 `audit_getloginuid()` 함수를 사용할 예정입니다.

**Comment by parkmino** [comment]
네, 예전 다솜이 흔적이 남아서인 것 같더군요.
다솜 관련 파일을 깨끗하게 지우고, usr.bin.evince에도 다솜을 지우고, 시스템을 재시작하니 정상적으로 뜹니다.
거듭 감사합니다.

**Comment by cogniti** [comment]
데비안에서 su 명령으로 root 권한을 획득한 후에,
root 권한으로 gedit, evince 를 실행후 한글을 입력하면 잘 입력됩니다.
또한, 표시기(indicator)에 한글/시스템 전환 표시도 잘 됩니다.
데비안에서 sudo 명령으로 확인해보지는 않았습니다만, 아마 잘 될 것으로 기대하고 있습니다.
그러나, 우분투에서 sudo evince, sudo gedit 하면 한글 입력이 안 되던데, 그것은 우분투 문제인 것 같습니다.
imhangul-gtk2, imhangul-gtk3을 설치하여 테스트해봐도 root 권한에서 한글이 입력이 안 되는군요.
그 부분은 우분투 프로젝트에 말씀해주세요.
아무튼, nimf 버그를 고쳤습니다.
즐거운 리눅스 생활하세요.
