### ISSUE TITLE
레티나 디스플레이에서 특수문자 입력창 생성 위치

### ISSUE THREAD

**Issue by reckus** [cogniti/nimf#44]
Mint - Cinnamon 구성으로 3200*1800 모니터를 HiDPI(Double) 모드로 사용하고 있습니다.
한자 키를 이용한 특수문자 입력시 선택창이 커서 위치와 상당히 떨어진 곳에 나타나서, 
일부 프로그램에서는 제일 아래 행 등 화면 끝부분에서 호출 시 선택창이 화면을 벗어난 곳에 생성됩니다.
프로그램에 따라 선택창 생성 위치는 다르지만 커서 위치와 떨어진 곳에 생성되는 증상은 동일합니다.
 DPI를 Double이 아닌 Normal로 하면 문제 없이 작동하구요.

2017년 4월 8일 버전 사용중입니다.

확인 부탁드립니다.

감사합니다.

**Comment by cogniti** [comment]
안녕하세요.
재현을 하기 위해 필요한 정보가 있습니다.

디스플레이 모델명을 알려 주세요. 혹시 노트북이라면 노트북 모델명을 알려주세요.
왜냐하면 LCD 모니터를 검색해봤는데, 3200 * 1800 이 없어서 그렇습니다.

그리고 어떤 프로그램에서 문제가 발생하는지, 프로그램 이름을 알려주세요.

**Comment by reckus** [comment]
안녕하세요.

기종은 ASUS 노트북 UX330입니다.

프로그램별 증상은 좀 더 자세히 확인을 해 봤는데요,

xed / Firefox : 정상작동
Chrome : 생성 위치 이상 / 커서 위치에 무관하게 화면 내 여기저기 생성
LibreOffice : 생성 위치 이상 / 커서 위치에 따라 화면 밖 생성
Nemo : 생성 위치 이상 / 커서 위치와 무관하게 화면 우측 상단에 고정 생성

정도입니다.

감사합니다.

**Comment by cogniti** [comment]
fcitx 는 어떤지 확인 좀 해주실 수 있나요?

**Comment by cogniti** [comment]
Chrome 는 확인하지 않았습니다.
그러나 Chromium 에 버그가 있습니다. 따라서 Chrome 은 따로 확인하지 않겠습니다.

 The coordinates send to input method on Hi-DPI Linux environment are not scaled 
https://bugs.chromium.org/p/chromium/issues/detail?id=475718

LibreOffice 의 경우
https://wiki.documentfoundation.org/Development/HiDpi#OS_.2F_HiDPI_detection_issues
를 참고하시기 바랍니다.

Nemo 의 경우도 어플로 추정됩니다.

**Comment by cogniti** [comment]
HiDPI 모니터가 없어서 1366 * 768, nemo 3.2.2, debian stretch, nimf 2017.04.08 에서 테스트했습니다.

https://youtu.be/e7Aey88Jbn0

`gnome-terminal` 열은 후에 `gsettings set org.gnome.desktop.interface scaling-factor 2` 명령을 하였습니다.

1366 * 768 를 두 배로 확대하여 약 638 * 384 크기에서 프로그램이 작동하는 것이라,
후보창(한자창)의 세로 좌표가 384 보다 크면 위로 올라가게끔 되어 있습니다. 그래서 윗부분이 짤리는 것인데, 아래로 내려가게끔 하면 아래가 짤립니다. 해상도가 너무 낮아서 어쩔 수가 없습니다.
해상도 2048 * 1536 이상에서 테스트하면 윗부분이 짤리는 문제는 발생하지 않을 것입니다.

한자 입력할 때 말씀하신 문제는 발견되지 않았습니다, 다만 중국어 입력할 때 후보창 위치에 문제가 있습니다.
미래에 다시 확인하겠습니다.

**Comment by reckus** [comment]
확인 감사합니다.
