### ISSUE TITLE
Android Studio 에서 한글 입력이 되지 않습니다.

### ISSUE THREAD

**Issue by muzeye** [cogniti/nimf#45]
Ubuntu 16.04.2 LTS에서 PPA설치 하였으며, 터미널이나 VSCODE에서도 정상적으로 한글입력이 됩니다만 Android Studio에서 한글 입력이 되지 않습니다.

**Comment by cogniti** [comment]
안녕하세요.
터미널 열은 후에

```
export | grep XMODIFIERS
```

결과를 올려주세요.

**Comment by muzeye** [comment]
declare -x XMODIFIERS="@im=nimf"

로 표시됩니다.

**Comment by cogniti** [comment]
제가 알기로는 Android Studio 는 XIM 어플입니다.
터미널 열은 후에

```
export XMODIFIERS="@im=nimf"
```

하신 후, 터미널에서 안드로이드 스튜디오를 실행하는 명령을 수행해보시기 바랍니다.
https://askubuntu.com/questions/843543/how-to-launch-android-studio-using-terminal

혹시 `sudo` 명령을 사용하셨다면 `sudo` 명령이 아닌 일반 사용사 권한으로 실행해 보세요.

**Comment by cogniti** [comment]
다른 분들은 어떤가요?

**Comment by muzeye** [comment]
export XMODIFIERS="@im=nimf"
    ./studio.sh

여전히 되지 않습니다.
환경에 차이가 있을까 싶어 아예 우분투를 재설치하고 실행해보았으나 역시 마찬가지입니다.

Ubuntu GNOME 16.04.2 LTS
Android Studio 2.3.1
openjdk-8-jdk 8.121.b13 환경입니다.

**Comment by dante2k** [comment]
안녕하세요.
Xubuntu 16.04.2 LTS x64
Android Studio 2.3.1
Oracle JDK 1.8.0_112
이상의 환경입니다.

@muzeye 님과 동일하게 테스트하였으나 한글입력으로 변환되지 않습니다.
사용한 nimf 버전은 hodong repository 의 2017.04.08.1~xenial 입니다.
일단 2월 21일자로 빌드했던 버전으로 롤백하였습니다.

**Comment by iyagicom** [comment]
저도 한글로 바꾸기가 안되어서 영어만 줄기차게 써져요.
제 환경은 
ubuntu 17.04 x64
Android Studio 2.3.2 입니다.

아직 되게하는법 없나요?

**Comment by iyagicom** [comment]
Android Studio 2.3.2 끝문자 에러 없이 uim-byeoru로 아주 잘써지네요.
 uim-byeoru로 해결될때까지는 써야 겠네요
설정이 쫌 복잡하네요.
벼루깐후 uim 띄어서 값 바꾸면 되요.

**Comment by cogniti** [comment]
@dante2k nimf 2월 21일자로 빌드했던 버전은 잘 되나요?

**Comment by dante2k** [comment]
@cogniti 네, 지금도 2월 21일자 버전으로 계속 사용 중 입니다.

**Comment by cogniti** [comment]
원인을 찾았으며 곧 해결될 예정입니다.

```
hodong@debian:~/nimf$ git diff
diff --git a/modules/services/xim/nimf-xim.c b/modules/services/xim/nimf-xim.c
index 23d3194..0f39108 100644
--- a/modules/services/xim/nimf-xim.c
+++ b/modules/services/xim/nimf-xim.c
@@ -456,6 +456,12 @@ static gboolean nimf_xim_start (NimfService *service)
   }
 
   XIMStyle im_styles [] = {
+    XIMPreeditPosition  | XIMStatusNothing,
+    XIMPreeditCallbacks | XIMStatusNothing,
+    XIMPreeditNothing   | XIMStatusNothing,
+    XIMPreeditPosition  | XIMStatusCallbacks,
+    XIMPreeditCallbacks | XIMStatusCallbacks,
+    XIMPreeditNothing   | XIMStatusCallbacks,
     XIMPreeditCallbacks | XIMStatusNone, /* on-the-spot */
     XIMPreeditNothing   | XIMStatusNone, /* on-root-window */
     XIMPreeditNone      | XIMStatusNone, /* do not anyhing */
```

**Comment by search5** [comment]
@cogniti 아, nimf의 버그였었나요? intellij에 계속 문제제기 하던 중이었는데... 일단 추이를 지켜보겠습니다. 패치되면 확인해볼게요.
