### ISSUE TITLE
Can't build using yaourt in GCC 7.

### ISSUE THREAD

**Issue by pinkrespect** [cogniti/nimf#46]
yaourt -S nimf-git을 실행하면 이런 메세지가 뜹니다..

```Making all in xim
make[4]: Entering directory '/tmp/yaourt-tmp-didee/aur-nimf-git/src/nimf/modules/services/xim'
  CC       libnimf_xim_la-nimf-xim.lo
  CC       libnimf_xim_la-nimf-xim-im.lo
  CC       IMdkit/libnimf_xim_la-FrameMgr.lo
  CC       IMdkit/libnimf_xim_la-i18nAttr.lo
  CC       IMdkit/libnimf_xim_la-i18nClbk.lo
  CC       IMdkit/libnimf_xim_la-i18nIc.lo
  CC       IMdkit/libnimf_xim_la-i18nIMProto.lo
  CC       IMdkit/libnimf_xim_la-i18nMethod.lo
  CC       IMdkit/libnimf_xim_la-i18nOffsetCache.lo
  CC       IMdkit/libnimf_xim_la-i18nPtHdr.lo
  CC       IMdkit/libnimf_xim_la-i18nUtil.lo
  CC       IMdkit/libnimf_xim_la-i18nX.lo
IMdkit/i18nX.c: In function ‘Xi18nXSend’:
IMdkit/i18nX.c:281:25: error: ‘%d’ directive writing between 1 and 11 bytes into a region of size between 3 and 7 [-Werror=format-overflow=]
              "_server%d_%d",
                         ^~
IMdkit/i18nX.c:281:14: note: directive argument in the range [-2147483648, 20]
              "_server%d_%d",
              ^~~~~~~~~~~~~~
IMdkit/i18nX.c:280:5: note: ‘sprintf’ output between 11 and 25 bytes into a destination of size 16
     sprintf (atomName,
     ^~~~~~~~~~~~~~~~~~
              "_server%d_%d",
              ~~~~~~~~~~~~~~~
              connect_id,
              ~~~~~~~~~~~
              ((sequence > 20)  ?  (sequence = 0)  :  sequence++));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:698: IMdkit/libnimf_xim_la-i18nX.lo] Error 1
make[4]: Leaving directory '/tmp/yaourt-tmp-didee/aur-nimf-git/src/nimf/modules/services/xim'
make[3]: *** [Makefile:439: all-recursive] Error 1
make[3]: Leaving directory '/tmp/yaourt-tmp-didee/aur-nimf-git/src/nimf/modules/services'
make[2]: *** [Makefile:439: all-recursive] Error 1
make[2]: Leaving directory '/tmp/yaourt-tmp-didee/aur-nimf-git/src/nimf/modules'
make[1]: *** [Makefile:501: all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-didee/aur-nimf-git/src/nimf'
make: *** [Makefile:433: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build nimf-git.
```

확인 해 주시면 감사하겠습니다. 언제나 잘 쓰고 있습니다.

**Comment by toto1444** [comment]
Arch linux
also too

`
==> Building and installing package
==> Making package: nimf-git 2017.01.28.aa61961-1 (Sat Jun 10 15:31:05 KST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning nimf git repo...
Cloning into bare repository '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/nimf'...
remote: Counting objects: 4218, done.
remote: Total 4218 (delta 0), reused 0 (delta 0), pack-reused 4218
Receiving objects: 100% (4218/4218), 1.15 MiB | 808.00 KiB/s, done.
Resolving deltas: 100% (2848/2848), done.
==> Validating source files with md5sums...
    nimf ... Skipped
==> Extracting sources...
  -> Creating working copy of nimf git repo...
Cloning into 'nimf'...
done.
==> Starting pkgver()...
==> Updated version: nimf-git .aa61961-1
==> Starting build()...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: configure.ac: creating directory build-aux
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:13: installing 'build-aux/ar-lib'
configure.ac:13: installing 'build-aux/compile'
configure.ac:42: installing 'build-aux/config.guess'
configure.ac:42: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing './INSTALL'
daemon/Makefile.am: installing 'build-aux/depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for ar... ar
checking the archiver (ar) interface... ar
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether NLS is requested... yes
checking for intltool >= 0.50.1... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.26.0
checking for XML::Parser... ok
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... (cached) /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... (cached) /usr/bin/msgfmt
checking for xgettext... (cached) /usr/bin/xgettext
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit gtk+-3.0... yes
checking for glib-2.0... yes
checking for gtk+-2.0... yes
checking for chewing glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for libhangul >= 0.0.12 glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for rime >= 1.2.9 glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for sunpinyin-2.0 glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for /usr/lib/sunpinyin/data/lm_sc.t3g... no
checking for /usr/lib/sunpinyin/data/pydict_sc.bin... no
checking for /usr/share/sunpinyin/lm_sc.t3g... yes
checking for /usr/share/sunpinyin/pydict_sc.bin... yes
checking for anthy glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit... yes
checking for /var/lib/anthy/anthy.dic... no
checking for /usr/share/anthy/anthy.dic... yes
checking for QtGui... yes
checking for Qt5Core Qt5Gui Qt5Widgets... yes
checking for /usr/include/qt/QtGui/5.9.0/QtGui/qpa/qplatforminputcontext.h... yes
checking for /usr/include/qt/QtGui/5.9.0/QtGui/qpa/qplatforminputcontextplugin_p.h... yes
checking for moc-qt5... /usr/bin/moc-qt5
checking for gtk+-3.0 gdk-x11-3.0... yes
checking for gtk-query-immodules-3.0... /usr/bin/gtk-query-immodules-3.0
checking for gtk-query-immodules-2.0... /usr/bin/gtk-query-immodules-2.0
checking for gtk-update-icon-cache-3.0... no
checking for gtk-update-icon-cache... /usr/bin/gtk-update-icon-cache
checking for rsvg-convert... /usr/bin/rsvg-convert
checking for glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit
                                     wayland-client wayland-server
                                     wayland-protocols xkbcommon... yes
checking for glib-2.0 gio-2.0 gio-unix-2.0 gmodule-2.0 xkbcommon >= 0.5.0 audit x11 gtk+-3.0... yes
checking for glib-2.0 gobject-2.0 audit... yes
checking for glib-2.0 gio-2.0 gio-unix-2.0 x11
                                        gtk+-3.0 appindicator3-0.1... yes
checking for gtk+-3.0 gio-2.0 gmodule-2.0... yes
checking for pkg-config... (cached) /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating daemon/Makefile
config.status: creating data/Makefile
config.status: creating data/apparmor-abstractions/Makefile
config.status: creating data/icons/Makefile
config.status: creating data/im-config/Makefile
config.status: creating libnimf/Makefile
config.status: creating libnimf/nimf.pc
config.status: creating modules/Makefile
config.status: creating modules/clients/Makefile
config.status: creating modules/clients/gtk/Makefile
config.status: creating modules/clients/qt4/Makefile
config.status: creating modules/clients/qt5/Makefile
config.status: creating modules/engines/Makefile
config.status: creating modules/engines/nimf-anthy/Makefile
config.status: creating modules/engines/nimf-chewing/Makefile
config.status: creating modules/engines/nimf-libhangul/Makefile
config.status: creating modules/engines/nimf-rime/Makefile
config.status: creating modules/engines/nimf-sunpinyin/Makefile
config.status: creating modules/engines/nimf-system-keyboard/Makefile
config.status: creating modules/services/Makefile
config.status: creating modules/services/indicator/Makefile
config.status: creating modules/services/wayland/Makefile
config.status: creating modules/services/xim/Makefile
config.status: creating po/Makefile.in
config.status: creating settings/Makefile
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing default-1 commands
config.status: executing libtool commands
config.status: executing po/stamp-it commands
make  all-recursive
make[1]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf'
Making all in libnimf
make[2]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/libnimf'
  GEN      nimf-enum-types.h
  GEN      nimf-enum-types.c
  GEN      nimf-marshalers.h
  GEN      nimf-marshalers.c
make  all-am
make[3]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/libnimf'
  CC       libnimf_la-nimf-client.lo
  CC       libnimf_la-nimf-private.lo
  CC       libnimf_la-nimf-im.lo
  CC       libnimf_la-nimf-types.lo
  CC       libnimf_la-nimf-events.lo
  CC       libnimf_la-nimf-engine.lo
  CC       libnimf_la-nimf-module.lo
  CC       libnimf_la-nimf-key-syms.lo
  CC       libnimf_la-nimf-message.lo
  CC       libnimf_la-nimf-candidate.lo
  CC       libnimf_la-nimf-connection.lo
  CC       libnimf_la-nimf-server.lo
  CC       libnimf_la-nimf-server-im.lo
  CC       libnimf_la-nimf-service.lo
  CC       libnimf_la-nimf-service-im.lo
  CC       libnimf_la-nimf-enum-types.lo
  CC       libnimf_la-nimf-marshalers.lo
  CCLD     libnimf.la
  GEN      org.nimf.gschema.valid
make[3]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/libnimf'
make[2]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/libnimf'
Making all in modules
make[2]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules'
Making all in engines
make[3]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines'
Making all in nimf-anthy
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-anthy'
  CC       libnimf_anthy_la-nimf-anthy.lo
  CCLD     libnimf-anthy.la
  GEN      org.nimf.engines.nimf-anthy.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-anthy'
Making all in nimf-chewing
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-chewing'
  CC       libnimf_chewing_la-nimf-chewing.lo
  CCLD     libnimf-chewing.la
  GEN      org.nimf.engines.nimf-chewing.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-chewing'
Making all in nimf-libhangul
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-libhangul'
  CC       libnimf_libhangul_la-nimf-libhangul.lo
  CCLD     libnimf-libhangul.la
  GEN      org.nimf.engines.nimf-libhangul.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-libhangul'
Making all in nimf-rime
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-rime'
  CC       libnimf_rime_la-nimf-rime.lo
  CCLD     libnimf-rime.la
  GEN      org.nimf.engines.nimf-rime.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-rime'
Making all in nimf-sunpinyin
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-sunpinyin'
  CXX      libnimf_sunpinyin_la-nimf-sunpinyin.lo
  CXXLD    libnimf-sunpinyin.la
  GEN      org.nimf.engines.nimf-sunpinyin.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-sunpinyin'
Making all in nimf-system-keyboard
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-system-keyboard'
  CC       libnimf_system_keyboard_la-nimf-system-keyboard.lo
  CCLD     libnimf-system-keyboard.la
  GEN      org.nimf.engines.nimf-system-keyboard.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines/nimf-system-keyboard'
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines'
make[3]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/engines'
Making all in clients
make[3]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients'
Making all in gtk
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/gtk'
  CC       im_nimf_gtk2_la-im-nimf.lo
  CCLD     im-nimf-gtk2.la
  CC       im_nimf_gtk3_la-im-nimf.lo
  CCLD     im-nimf-gtk3.la
  GEN      org.nimf.clients.gtk.gschema.valid
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/gtk'
Making all in qt4
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt4'
  GEN      im-nimf-qt4.moc
make  all-am
make[5]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt4'
  CXX      libqt4im_nimf_la-im-nimf-qt4.lo
  CXXLD    libqt4im-nimf.la
make[5]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt4'
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt4'
Making all in qt5
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt5'
  GEN      im-nimf-qt5.moc
make  all-am
make[5]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt5'
  CXX      libqt5im_nimf_la-im-nimf-qt5.lo
  CXXLD    libqt5im-nimf.la
  GEN      org.nimf.clients.qt5.gschema.valid
make[5]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt5'
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients/qt5'
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients'
make[3]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/clients'
Making all in services
make[3]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services'
Making all in indicator
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/indicator'
  CC       libnimf_indicator_la-nimf-indicator.lo
  CCLD     libnimf-indicator.la
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/indicator'
Making all in wayland
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/wayland'
  GEN      input-method-unstable-v1-client-protocol.h
  GEN      input-method-unstable-v1-protocol.c
make  all-am
make[5]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/wayland'
  CC       libnimf_wayland_la-nimf-wayland.lo
  CC       libnimf_wayland_la-nimf-wayland-im.lo
  CC       libnimf_wayland_la-input-method-unstable-v1-protocol.lo
  CCLD     libnimf-wayland.la
make[5]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/wayland'
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/wayland'
Making all in xim
make[4]: Entering directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/xim'
  CC       libnimf_xim_la-nimf-xim.lo
  CC       libnimf_xim_la-nimf-xim-im.lo
  CC       IMdkit/libnimf_xim_la-FrameMgr.lo
  CC       IMdkit/libnimf_xim_la-i18nAttr.lo
  CC       IMdkit/libnimf_xim_la-i18nClbk.lo
  CC       IMdkit/libnimf_xim_la-i18nIc.lo
  CC       IMdkit/libnimf_xim_la-i18nIMProto.lo
  CC       IMdkit/libnimf_xim_la-i18nMethod.lo
  CC       IMdkit/libnimf_xim_la-i18nOffsetCache.lo
  CC       IMdkit/libnimf_xim_la-i18nPtHdr.lo
  CC       IMdkit/libnimf_xim_la-i18nUtil.lo
  CC       IMdkit/libnimf_xim_la-i18nX.lo
IMdkit/i18nX.c: In function 'Xi18nXSend':
IMdkit/i18nX.c:281:25: error: '%d' directive writing between 1 and 11 bytes into a region of size between 3 and 7 [-Werror=format-overflow=]
              "_server%d_%d",
                         ^~
IMdkit/i18nX.c:281:14: note: directive argument in the range [-2147483648, 20]
              "_server%d_%d",
              ^~~~~~~~~~~~~~
IMdkit/i18nX.c:280:5: note: 'sprintf' output between 11 and 25 bytes into a destination of size 16
     sprintf (atomName,
     ^~~~~~~~~~~~~~~~~~
              "_server%d_%d",
              ~~~~~~~~~~~~~~~
              connect_id,
              ~~~~~~~~~~~
              ((sequence > 20)  ?  (sequence = 0)  :  sequence++));
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [Makefile:698: IMdkit/libnimf_xim_la-i18nX.lo] Error 1
make[4]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services/xim'
make[3]: *** [Makefile:439: all-recursive] Error 1
make[3]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules/services'
make[2]: *** [Makefile:439: all-recursive] Error 1
make[2]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf/modules'
make[1]: *** [Makefile:501: all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-ahhyeon/aur-nimf-git/src/nimf'
make: *** [Makefile:433: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build nimf-git.
==> Restart building nimf-git ? [y/N]
==> ---------------------------------
`

**Comment by ChangJoeRim** [comment]
저는 일단 간단하게 modules/services/xim/IMdkit/i18nX.c에 있는 MakeNewAtom 함수를 살짝 바꾸는 걸로 해결했습니다.
static char *MakeNewAtom (CARD16 connect_id, char *atomName)
{
    static int sequence = 0;
    
    sprintf (atomName,
             "_server%d_%d",
             connect_id,
             ((sequence > 20)  ?  (sequence = 0)  :  sequence++)); //여기 삼항연산자가 문제가 되는것 같음.
    return atomName;
}
해당 부분을 밖으로 끌어내서 if문으로 바꾸면 컴파일 잘 됩니다.
사실 makefile에서 옵션만 바꿔주면 될것 같은데, 바꿔도 error가 떠서 이런 극단적인 방법을 사용했습니다.
static char *MakeNewAtom (CARD16 connect_id, char *atomName)
{
	static int sequence = 0;
	
	if(sequence > 20) //수정 후
		sequence = 0;
	else
		sequence++;
	
	sprintf (atomName,
		     "_server%d_%d",
		     connect_id, sequence); //수정 후
	return atomName;
}

yaourt로 설치 후 mate에서 쓰고 있는데, 문제없이 잘 됩니다.

**Comment by cogniti** [comment]
바이트 수를 확인해봤는데, 오버플로우 문제는 발생하지 않습니다.
atomName 이 16 바이트
"_server%d_%d" NULL 포함하여 9 바이트
connect_id 2 바이트 변수, 최대값 65535,  최대 5바이트 문자열
sequence 범위, 0 에서 20, 또는 21, 최대 2바이트 문자열
9 + 5 + 2 = 16 (NULL 포함)
따라서 sequence 변수를 unsigned 8비트 변수로 변경하면 될 것 같습니다.

**Comment by cogniti** [comment]
MakeNewAtom 함수에서..

static int sequence = 0; 이 부분을

static unsigned char = 0;

로 변경한 후에 테스트 해보시고 잘 되면 Pull Request 올려주세요
