### ISSUE TITLE
데비안 9에서 java 기반 에디터에서 한글 입력 및 키보드의 오동작

### ISSUE THREAD

**Issue by search5** [cogniti/nimf#48]
훌륭한 입력기가 있어서 늘 감사하면서 사용하고 있습니다.

최근 우분투 16.04 LTS 그놈 버전과, 데비안 9 KDE 버전을 새롭게 설치해서 사용하고 있는데 좀 특이한 현상을 발견해서 이슈 보고합니다.

근데 이게 이슈인지는 잘 모르겠습니다. ㅠ.ㅠ

현재는 데비안 9 KDE 플라즈마 5.8을 사용하고 있습니다. 사용하고 있는 nimf 버전은 github에 별도 패키징된 것을 사용하고 있습니다.

현상은 이렇습니다.

kde 및 gnome의 기본 프로그램 및 크롬 등에서도 정상적으로 한글 입력 및 한영 전환이 잘 되는데, 이상하게 intellij 등의 자바 gui 프로그램에서만 한영 전환도 안되고 억지로 한영 변환된 상태에서 입력을 해도 한글 입력이 이루어지지 않고 있습니다.

그리고 프로그램을 처음 가동하면 키 입력의 기본 상태가 글자 덮어쓰기 모드로 변경됨은 물론 shift key + arrow 키가 글자 선택으로 사용되지 않고 조금 이상하게 동작합니다. 기계식 키보드를 따로 사용하고 있어서 기계식 키보드를 초기화하였으나 intellij 등에서만 이상하게 동작하고 있었습니다.

왜 이런지 도통 알 수가 없습니다. 회사에서 사용중인 민트 리눅스에서는 이런 현상이 없었는데 알 수가 없네요 ㅠ.ㅠ 혹시 입력기의 문제인가 싶어서 일단 이슈는 보고합니다만, 호동님도 생업이 있으신데 이슈를 보고하는게 맞나 싶습니다.

사용된 자바 버전은 oracle java jdk 1.8.0_131 이고, intellij 는 2017.1 버전을 사용하고 있습니다. 회사에서 입력이 잘되는 버전은 oracle java jdk 1.8.0_112 이고, intellij 는 2017.1 버전을 사용하고 있습니다.

회사에서 사용중인 리눅스와 별도로 사용중인 리눅스는 커널 버전을 비롯하여 배포본 버전이 다릅니다. 왜 이런 현상이 발생하는지 알았으면 좋겠습니다 ㅠ.ㅠ

일단 이슈는 올립니다. 괜한데 이슈 올리는 것이 아닌가.. 죄송스럽게 생각합니다.. 고맙습니다.

**Comment by cogniti** [comment]
안녕하세요. 아래 링크 참고해 보세요.
https://m.clien.net/service/board/kin/9547601?
![screenshot_2017-07-05-12-27-23](https://user-images.githubusercontent.com/17453239/27848094-755fc8cc-617d-11e7-9f6d-60b160f49b64.png)

**Comment by search5** [comment]
안그래도 이런저런 해결책을 다 써봤는데 마찬가지였습니다. 그래서 인텔리제이쪽에 문의해두었습니다.

**Comment by cogniti** [comment]
님프 버그입니다. 버그를 제보해주셔서 감사합니다.
