### ISSUE TITLE
Add automatic import for translations

### ISSUE THREAD

**Issue by fabiozaramella** [cogniti/nimf#51]
It seems that there isn't a clear way to translate nimf into other languages without manually updating pot files. Instead, it would be nice to be able to translate nimf into your language using translation services, such as Weblate.

**Comment by cogniti** [comment]
Thank you for the information.
Nimf has a few text to translate. Web-based translation tools are not required.

**Comment by fabiozaramella** [comment]
Thank you for the response. So should i propose a PR with the strings translated into my language?

**Comment by cogniti** [comment]
Of course.
