### ISSUE TITLE
nimf indicator for polybar

### ISSUE THREAD

**Issue by hshin23** [cogniti/nimf#52]
먼저 좋은 프로그램 만들어 주셔서 감사합니다.

따로 데스크톱 환경이 없이 x에서 돌리고 있는데요,
혹시 xkb 등을 통해서 현재 사용 되고 있는 인풋 언어를 보여줄수 있는 방법이 있을까요?

I'm running it on X without any specific DE.
Is there a way to show the current language input through xkb, or etc?

**Comment by cogniti** [comment]
안녕하세요. 원하시는게 무엇인지 정확하게 이해가 되지 않습니다. 스크린샷을 올려주시면 제가 이해하는데 도움이 될 것 같습니다.
아마... nimf indicator 가 표시되지 않는 환경 같습니다. 그리고 사용 중인 window manager 가 무엇인지 알고 싶습니더.

**Comment by hshin23** [comment]
@cogniti [i3wm](https://github.com/i3/i3) 에 [polybar](https://github.com/jaagr/polybar) 을 사용중입니다. nimf indicator 가 자동으로 표시가 안되서 xkb등을 사용해서 표시하려고 합니다.

**Comment by hshin23** [comment]
![2017-07-12-215415_1913x18_scrot](https://user-images.githubusercontent.com/8732646/28147174-bee1f40a-674c-11e7-8ca0-170b7708b162.png)

오른쪽 상단에 us 라고 적혀있는 부분이 xkb에서 현재 언어를 긁어오는데요,
nimf를 사용중일때는 `setxkbmap -query` 등 명령을 터미널에서 실행시 입력 언어가 안뜹니다.

**Comment by cogniti** [comment]
nimf 에서 한글로 전환할 때 xkb 를 kr 로 변경하도록 코드를 수정하면,
영문 dvorak 과 kr 을 함께 사용할 수 없게 됩니다. 무슨 말이냐면, kr 로 변경하면 영문이 qwerty 자판으로 되어 버립니다. 따라서 xkb 변경 코드를 추가하지 않겠습니다.

poly 프로젝트에 appindicator 를 지원해달라고 요청해보시는 걸 어떨까요.

**Comment by cogniti** [comment]
여기에 polybar 모듈이 나와 있습니다.
https://github.com/jaagr/polybar/wiki/User-contributed-modules
polybar 용 인디케이터를 만드는 방법에 대해 고려해 보겠습니다.

**Comment by hshin23** [comment]
@cogniti 우선 해결 했습니다.
polybar 매뉴얼을  차근차근 읽어보니, config 에 tray-position 을 넣어주면 시스템 트레이가 들어갑니다.

![2017-07-13-144252_253x23_scrot](https://user-images.githubusercontent.com/8732646/28182277-981b6792-67d9-11e7-8ea2-e7530a57eccc.png)

**Comment by cogniti** [comment]
아.... 제가, nimf indicator 가 1개만 생성되도록 설계했습니다.
nimf indicator 가 2개 이상이 필요하다면 별로도 이슈를 만들어주시기 바랍니다.
아무튼, 해결되었어 다행입니다.
즐거운 리눅스 생활하세요.
