### ISSUE TITLE
님프를 사용할 경우 마메에서 움직임이 원활하게 동작하지 않습니다.

### ISSUE THREAD

**Issue by GabBong** [cogniti/nimf#53]
우분투 그놈 17.04 사용자 입니다.
가끔씩 마메로 옛 게임을 즐겨하는 편인데
님프를 사용하면은 움직임이 원활하지가 않습니다.
그러니까 게임내에서 방향키로 움직일시 멈칫멈칫 거리면서 움직이는 현상이 발생합니다.

**Comment by cogniti** [comment]
안녕하세요. 버벅거리는 것을 확인했습니다.
해결점을 찾아보겠습니다.

**Comment by cogniti** [comment]
이 문제는 dispatcher 문제 같은데... 해결하는데 시간이 좀 오래 걸릴 것 같습니다.

**Comment by cogniti** [comment]
원인을 찾았습니다. dispatcher 문제입니다.
i18nMethod.c 에

```
    _XRegisterFilterByType (dpy,
                            i18n_core->address.im_window,
                            SelectionRequest,
                            SelectionRequest,
                            WaitXSelectionRequest,
                            (XPointer)ims);
```

있는데, `XRegisterFilterByType` 함수는 xlib 내부 함수인데 내부적으로 키이벤트를 처리를 하여 nimf-xim 의 dispatcher 내에 `XPending`, `XNextEvent` 에 키이벤트가 나타나지 않습니다.

`WaitXSelectionRequest` 함수가 nimf-xim 의 dispatcher 에서 돌아가도록 변경해야 합니다. 해결하는데 시간이 오래 걸릴 것 같습니다.

**Comment by cogniti** [comment]
애초 디스패쳐(dispatcher) 문제로 생각했었는데, 장시간 테스트를 해보니, mame 버그입니다.
IMdkit 에는 sampleIM.c 이 있습니다.
https://github.com/choehwanjin/nabi/blob/master/IMdkit/doc/Xi18n_sample/sampleIM.c
```
    case XIM_FORWARD_EVENT:
```
`IMForwardEvent()` 를 이용하여 키이벤트를 그대로 mame 로 돌려보내면 mame 캐릭터 움직임이 버벅거립니다.

반면, `return 1` 하여 입력기가 아무것도 하지 않으면,  mame 캐릭터 움직임이 자연스럽습니다. 이 경우 mame 캐릭터가 움직이지 않아야 제대로 구현한 것입니다. 반면, libreoffice-gnome, libreoffice-gtk 를 제거하여 libreoffice 가 XIM 을 사용하도록 하면, libreoffice --writer 에는 아무것도 입력할 수 없습니다. libreoffice 처럼 아무것도 입력되지 않아야 정상입니다.


mame 은 사용자가 키를 누르면 그 키이벤트를 mame 자체에서 처리하고, 그 키이벤트를 또다시 XIM 입력기로 보내서 XIM 은 그 키이벤트를 mame 에 또 보냅니다. 1개의 키이벤트에 대하여 mame 이 2번 처리를 하므로 mame 이 버벅거리는 겁니다.

sample-xim, nabi, gcin, nimf 에서 동일 현상이 발생됩니다. 입력기가 빠르다 보니까... 단위 시간에 mame 에 보내는 키이벤트 갯수가 많아서 그렇습니다.
fcitx 는 mame 캐릭터 움직임이 아주 약간 버벅거리는 것을 볼 수 있으며,
ibus 의 경우, 캐릭터의 움직임이 버벅거린다기 보다는, 부드럽기는 한데, 대체적으로 움직임이 약간 느린 느낌이 듭니다.

nimf 에서 이 현상을 피하려면,
nimf-xim 의 dispatcher 에 딜레이를 줘서 오히려 nimf 가 느려지도록 만들면, mame 이 버벅거리지 않습니다.
또는 `XIM_FORWARD_EVENT` 를 무시하는 옵션을 만들 수 있는데, 그 경우 정상적으로 구현한 X 프로그램(예, libreoffice)에 입력을 못하게 됩니다.
피할 수 있는 방법은 있으나 그 방법은 매우 부적절해 보입니다. 그래서 nimf 에 mame 버그 회피법을 만들지 않겠습니다.

mame 프로젝트에 버그 리포트를 보내시거나, 느린 입력기를 사용하시면 mame 캐릭터 움직임이 덜 버벅거리게 됩니다. 터미널 열고,

```
export XMODIFIERS="@im=none"
```

그 후 터미널에서 mame 을 작동시키면 mame 이 XIM 을 사용하게 않게 됩니다.
이 방법을 사용하시길 바랍니다.
