### ISSUE TITLE
im-chooser needs to select nimf in Fedora 26 (gnome)

### ISSUE THREAD

**Issue by hshin23** [cogniti/nimf#54]
페도라 26에서
export 및 설정이 모두 되어있어도 한글이 안나왔는데요.
터미널에서 `imsettings-switch /etc/X11/xinit/xinput.d/nimf.conf` 혹은
im-chooser 앱을 실행 후 다시 로그인 하면 됩니다.

기본 페도라 그놈 환경이 아닌, gdm 위에서 기타 window manager 를 사용할 때 필요한 설정 같습니다.

**Comment by cogniti** [comment]
제가 페도라 사용자가 아니라서  이해가 잘 안 되는데요.. 문제점이 해결되었다는 말씀이신가요?

**Comment by hshin23** [comment]
@cogniti 네 저도 페도라/그놈 처음 사용자여서 몇 시간 동안 헤메다가 보니 이렇게 설정(?)을 해줘야 되더라구요.
