### ISSUE TITLE
nimf creates an issue for evince

### ISSUE THREAD

**Issue by aviramj** [cogniti/nimf#56]
I know this bug will sound bizarre, but installing nimf somehow creates a problem for evince(!). Not sure where the problem lies. Here's the strace of starting evince:

connect(11, {sa_family=AF_LOCAL, sun_path=@"unix:abstract=nimf-1000"}, 26) = -1 EACCES (Permission denied)
futex(0x7f4ffb749e08, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f4ffb749e08, FUTEX_WAKE_PRIVATE, 2147483647) = 0
close(11)                               = 0
nanosleep({1, 0}, 0x7fff56134700)       = 0
socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 11
fcntl(11, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(11, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(11, {sa_family=AF_LOCAL, sun_path=@"unix:abstract=nimf-1000"}, 26) = -1 EACCES (Permission denied)
close(11)                               = 0
nanosleep({1, 0}, 0x7fff56134700)       = 0
socket(AF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 11
fcntl(11, F_GETFL)                      = 0x2 (flags O_RDWR)
fcntl(11, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
connect(11, {sa_family=AF_LOCAL, sun_path=@"unix:abstract=nimf-1000"}, 26) = -1 EACCES (Permission denied)
close(11)                               = 0

This repeats for quite a few times, causing evince to hang for several seconds. It happens every time evince starts and thus delays the opening by 4-5 seconds. It started only when I installed nimf and seems to be directly related to nimf. Any ideas what could be the problem or how to resolve it?

Thanks for your assistance!

**Comment by cogniti** [comment]
Hello.
See below.

https://github.com/cogniti/nimf/blob/master/data/apparmor-abstractions/nimf
https://bugs.launchpad.net/ubuntu/+source/evince/+bug/1569863

https://github.com/cogniti/nimf/issues/43
https://github.com/cogniti/nimf/issues/1

**Comment by aviramj** [comment]
감사합니다!



- Aviram
