### ISSUE TITLE
segfault on libxkbcommon 0.7.2

### ISSUE THREAD

**Issue by hshin23** [cogniti/nimf#57]
I don't know if this is from `libxkbcommon` or `nimf`, but `nimf-daemon` gets segfaulted upon launch.

Running on Archlinux, Kernel version 4.12.4.

Here is the relevant dmesg log:
`[38140.922988] nimf-daemon[13308]: segfault at 0 ip 00007f1954c812c3 sp 00007fff385696e8 error 6 in libxkbcommon.so.0.0.0[7f1954c79000+3e000]
`

**Comment by cogniti** [comment]
Please tell me how to reproduce.

**Comment by hshin23** [comment]
I don't know how to reproduce this, but the issue got resolved by doing god knows what.
I tried building it from the source and the AUR  where both generated the same log.

**Comment by cogniti** [comment]
I can reproduce it.

```
hodong@debian:~/nimf$ git diff
diff --git a/modules/engines/nimf-system-keyboard/nimf-system-keyboard.c b/modules/engines/nimf-system-keyboard/nimf-system-keyboard.c
index 530158e..b30151c 100644
--- a/modules/engines/nimf-system-keyboard/nimf-system-keyboard.c
+++ b/modules/engines/nimf-system-keyboard/nimf-system-keyboard.c
@@ -90,13 +90,7 @@ nimf_system_keyboard_init (NimfSystemKeyboard *keyboard)
   keyboard->preedit_attrs[1] = NULL;
   keyboard->xkb_context = xkb_context_new (XKB_CONTEXT_NO_FLAGS);
 
-  const gchar *locale = g_getenv ("LC_ALL");
-  if (!locale)
-    locale = g_getenv ("LC_CTYPE");
-  if (!locale)
-    locale = g_getenv ("LANG");
-  if (!locale)
-    locale = "C";
+  const gchar *locale = setlocale (LC_CTYPE, NULL);
 
   keyboard->xkb_compose_table =
     xkb_compose_table_new_from_locale (keyboard->xkb_context, locale,
```

**Comment by hshin23** [comment]
The issue got resolved by editing locale.conf then.
Initially my locale was only set to LANG="en_US.UTF-8",
and setting the locale options resolved the issue for me.
