### ISSUE TITLE
Segfault when running nimf-daemon 

### ISSUE THREAD

**Issue by ezaurum** [cogniti/nimf#58]
Segfault when running nimf-daemon in arch linux, LXDE
Cannot get logs in /var/log/daemon.log
```
uname -r
4.12.6-1-ARCH

```
nimf-daemon[15571]: segfault at 0 ip 00007f685d11f2c3 sp 00007ffe75af4f78 error 6 in libxkbcommon.so.0.0.0[7f685d117000+3e000]

**Comment by cogniti** [comment]
Please tell me how to reproduce.

**Comment by ezaurum** [comment]
```
git clone git@github.com:cogniti/nimf.git
pushd nimf/
./autogen.sh 
make
sudo make install
nimf-daemon
dmesg
```

Thanks

**Comment by ezaurum** [comment]
I'm sorry. I missclicked close.

**Comment by cogniti** [comment]
See https://github.com/cogniti/nimf/issues/57
