### ISSUE TITLE
rxvt-unicode (urxvt) 한글 조합 상자 숨김 / 표시 설정

### ISSUE THREAD

**Issue by x86kernel** [cogniti/nimf#59]
현재 Archlinux 과 i3-wm 를 사용중이며 터미널로 urxvt 를 사용중에 있습니다.

gtk, qt 어플리케이션들에서는 나타나지 않는데 urxvt 에서만 한글입력시 좌측하단에 현재 타이핑하는 한글이 조합되는 텍스트 박스가 나타납니다. 

혹시 이것을 숨길 수 있는 방법이 있나요?

**Comment by cogniti** [comment]
안녕하세요.
아래처럼 실행하시면 되겠습니다.

```
urxvt -pt OnTheSpot -pe xim-onthespot
```

**Comment by x86kernel** [comment]
감사합니다. 본의아니게 urxvt 에 관한 질문을 드려버렸네요 

제가 좀더 찾아봤어야 했는데 감사합니다!

**Comment by cogniti** [comment]
아니에요.. 괜찮아요.
즐거운 리눅스 시간 되세요

**Comment by x86kernel** [comment]
헛 urxvt 에 저 인자를 주고 실행해봐도 
여전히 조합상자가 나옵니다.

**Comment by x86kernel** [comment]
아 해결했습니다. 저 인자와 함께 설정에서 

Ignore XIMPreeditCallbacks 옵션을 해제하니 입력상자가 나오지 않네요~

감사합니다!.
