### ISSUE TITLE
님프를 여러 패키지로 분리하는 것에 대해 여러분들의 의견을 듣고 싶습니다. I would like to hear your opinions on split the Nimf into multiple packages.

### ISSUE THREAD

**Issue by cogniti** [cogniti/nimf#60]
한 가지 언어로만 입력하기를 원하는 사용자분들이 계십니다.
님프를 여러 패키지로 분리하는 것에 대해 여러분들의 의견을 듣고 싶습니다.

There are users who want to input in only one language.
I would like to hear your opinions on split the Nimf into multiple packages.

@sukso96100 @workman729 @bagjunggyu @nemonein

**Comment by sukso96100** [comment]
각 언어별 엔진(nimf-libhangul, nimf-rime 등)만 분리하여 별도 패키지로 제공하고, 나머지 ui 툴킷별 클라이언트(nimf-gtk, nimf-qt4, nimf-qt5 등)와 설정 앱 (nimf-settings), 표시기 등은 분리하지 않는것이 좋다고 생각합니다.

언어별 입력 엔진은 사람마다 쓰는것만 선택적으로 사용하지만. 설정 앱, 표시기, UI 툴킷별 클라이언트 나머지 구성요소는 대부분의 사용자가 공통적으로 쓰기 때문입니다.

**Comment by cogniti** [comment]
영빈님 의견에 동의합니다.

**Comment by NEONKID** [comment]
저도 언어별 패키지 분리를 원하고 툴킷별 클라이언트는 통합되었으면 좋겠습니다.

**Comment by nemonein** [comment]
다들 말씀해주신대로, 원하는 언어만 선별하여 설치할 수 있으면 더 좋겠습니다.
지난 번에 알려주신 방법대로 이미 한국어만 선택하여 컴파일해서 사용하고 있긴 하지만, 매번 소스를 고쳐야 하니 고치다가 행여 실수가 있지 않을까 좀 걱정이 되기도 했었습니다.
아예 분리가 되면 좀 더 사용이 편하겠습니다.

아울러, 언젠가부터 Release 발표를 안하시던데, 특별한 이유가 있으신건지 궁금하네요.

**Comment by cogniti** [comment]
전에는 릴리즈 커밋과 tag 를 붙였었는데, 2017.02.21 이후 2017.03.15 부터 제가 커밋을 올릴 때마다 바로 릴리즈를 하고 있습니다.
그러다보니 tag 를 붙일 경우 tag 가 너무 많아집니다.
그리고 피곤한 상태에서 밤에 작업을 하다보니 실수하는 경우가 발생할까봐 너무 신경을 쓰니 잠을 못자게 되므로 릴리즈 tag 를 붙이지 않고 있습니다.
tag 만 붙이지 않았을 뿐, 릴리즈가 되고 있습니다. merge 커밋 제외하고 제가 올린 마지막 커밋이 릴리즈 커밋입니다. 버전 이름이 릴리즈 날짜이므로 릴리즈 tag를 붙이지 않는다고 하여 불편한 점은 없을 것이라 생각합니다.
릴리즈 정보는 다음 파일에 있습니다.
https://github.com/cogniti/nimf/blob/master/debian/changelog
https://github.com/cogniti/nimf/blob/master/configure.ac

**Comment by bagjunggyu** [comment]
전자 장비 없이 지내서 인터넷도 오랜만이네요
저는 통합 입력기에 한표를 더해드립니다.
다만, 처음 설치후에 모든 입력기들에 사용 체크 되도록 되어 있는 것을
region이나 langugae에 따라 하나만 실행 체크 되도록 하고
나머지 사용하려는 입력기는 그때 사용자가 체크하도록 하면 어떨까 합니다.
건강한 한가위들 맞이 하세요

2017년 9월 15일 금요일, Hodong Kim<notifications@github.com>님이 작성한 메시지:

**Comment by cogniti** [comment]
다음 업데이트 때 패키지를 나누겠습니다.
