### ISSUE TITLE
inkscape에서 한글쓰기 끝문자에러 나요

### ISSUE THREAD

**Issue by iyagicom** [cogniti/nimf#61]
inkscape는 그래픽하는사람이라면 필수앱인데요.
"안"이라고 치면 안이 안보이고 "녕"을 쓰면 안이보이고 녕이 안보여요.
그리고, 
Krita는 한글자체가 안써지는데 이건 Krita에서 지원안해주는건가요?

**Comment by cogniti** [comment]
안녕하세요.
제가 테스트를 할 수 없는 상황입니다.
다른 입력기로는 어떤가요?

**Comment by iyagicom** [comment]
벼루는 끝문자 에러 없어요.

**Comment by cogniti** [comment]
fcitx 로 krita 에 입력할 수 있습니다.

**Comment by cogniti** [comment]
제가 `gtk_im_context_set_use_preedit()` 함수를 잘못 이해하고 있었네요.
추후 수정하겠습니다.

**Comment by cogniti** [comment]
nimf 로 krita 입력 됩니다.
![screenshot from 2017-12-27 17-24-48](https://user-images.githubusercontent.com/17453239/34375654-f81d3f06-eb2a-11e7-9041-13a082237ae2.png)

**Comment by iyagicom** [comment]
17.10에서 님프설정 띄우는 방법을 모르겠어요.
한영키로 바꾸기안되어서 한글을 쓸수가 없어요.
제가 중국어도 써야 되는데 중국어바꾸것도 알아야 되고요.

**Comment by cogniti** [comment]
인디케이터(표시기) 클릭하면 설정 메뉴 나와요. 그거 클릭하시면 되요.
또다른 방법으로는 터미널에서 nimf-settings 실행하시면 됩니다.
중국어 사용하시려면 nimf-rime 설치하시고 nimf-settings 에서 언어 전환 단축키 확인/변경하시면 됩니다.

**Comment by iyagicom** [comment]
한글키로 되어 있어도 17.10에서 한/영키로 안바끼네요.
한영키가 기본설정으로 되어 있던데요.
지우고 다시 잡아줘도 한영키가 안먹어요.

**Comment by cogniti** [comment]
터미널 열어서 `export | grep nimf` 명령하시고
```
declare -x GTK_IM_MODULE="nimf"
declare -x QT4_IM_MODULE="nimf"
declare -x QT_IM_MODULE="nimf"
declare -x XMODIFIERS="@im=nimf"
```
이런 결과가 나오는지 확인해보세요.

**Comment by iyagicom** [comment]
![2017-12-29 13-00-07](https://user-images.githubusercontent.com/15052400/34429223-8e648bea-ec98-11e7-879a-1da8a27e39c2.png)
그렇게 되어 있어요.

**Comment by cogniti** [comment]
nimf-libhangul 설치하세요
```
sudo apt install nimf-libhangul
```
그리고 위에 설정하신 키는 입력 엔진간 전환키입니다.
nimf-libhangul 설치하시면 메뉴가 하나 더 생길 거고 거기서 설정하세요.
![screenshot from 2017-12-29 13-18-47](https://user-images.githubusercontent.com/17453239/34429377-df74732c-ec9a-11e7-9e9c-cbb500a6b494.png)

**Comment by iyagicom** [comment]
https://cogniti.github.io/nimf/download.html 에 libhangul도 넣어되야 겠네요~
이제 한글은 써져요
하지만,
krita에서 님프,벼루 전부 끝문자 에러나요...

**Comment by iyagicom** [comment]
inkscape에서도 끝문자 에러가 잡히지 않았어요.
ms윈도우처럼 박스가 하나 뜨더니 그곳에 글씨가 먼저 써지고 다음글자쓸때 도화지에 글이 써져요
작업하는 새작업 도화지에는 끝문자 에러가 나요.

**Comment by cogniti** [comment]
inkscape 관련해서는 입력기에서 할 수 있는 부분을 다 했습니다.
나머지는 inkscape 프로젝트에 말씀해 주세요.
nimf 버그가 아닙니다.

**Comment by cogniti** [comment]
qt 문서 확인해봤는데,
gtk 의 `gtk_im_context_set_use_preedit()` 또는 XIM 의 input style 관련된 방법이 없는 것 같습니다.
fcitx 로 해보니 krita 에서 끝글자 버그 나기는 마찬가지고요.
원하시면 inkscape 사용할 때처럼 조합 중인 글자를 표시하는 작은 창을 나타내는 옵션을 추가해 드릴 수 있습니다. 필요하시면 이슈를 새로 작성해주세요. https://github.com/cogniti/nimf/issues/new
그리고 krita 끝글자 관련 버그는 nimf 버그가 아니니 krita 프로젝트에 말씀해주세요.
