### ISSUE TITLE
안드로이드 스튜디오 xml 편집시 글씨가 순간이동해요.

### ISSUE THREAD

**Issue by iyagicom** [cogniti/nimf#62]
[https://drive.google.com/open?id=0B_mYNdRpJkUuRnhQdWtIR2NsTGM](url)
글씨가 순간이동해요.
이건 벼루로 했을때도 그러네요.

**Comment by cogniti** [comment]
nimf-settings 에서 Use singleton 모드 옵션을 off 로 하세요

**Comment by iyagicom** [comment]
싱글톤모드 큼으로 해도 안되요.

**Comment by cogniti** [comment]
그러면 Android Studio 버그 같으니 그쪽에 말씀해 주세요

**Comment by cogniti** [comment]
동영상을 지금 확인했습니다.
XIM 사용할 때, 같은 창 내에서 마우스 클릭시 끝글자가 커밋되지 않는 건데 그것은 응용 프로그램 버그입니다. XIM 에서는 마우스 클릭을 후킹할 방법도 없는 것 같습니다.
