### ISSUE TITLE
Wine으로 Battle.net 어플리케이션 및 블리자드 게임 상에서 한글채팅 문제

### ISSUE THREAD

**Issue by alswg1994** [cogniti/nimf#63]
안녕하세요. 기존에 fcitx 사용하다 이걸로는 위에 프로그램들에선 아예 한영 전환이 안되서 nimf로 바꿨는데,
notepad.exe 에서는 정상적으로 입력되나 위의 프로그램들에서는 역시 문제가 있네요...

한영 전환은 됩니다. 다만 각 입력마다 문제가 있는데, 안녕하세요 를 입력한다고 가정하고 설명하겠습니다.

처음 안을 입력하면 텍스트 블록 상에서 입력됩니다. 안이 입력된 상태에서 ㄴ을 치면 ㄴ은 무시되고 안이 원래 텍스트창에 입력됩니다. 즉 한글자(최대 자음+모음+자음(밑받침)) 포맷을 넘는 입력이 들어오면 그 입력은 무시됩니다. 즉 안녕하세요를 입력하면 안ㅕ하요 가 입력됩니다.

Ignore XIMPreeditCallbacks를 키든 끄든 결과는 같습니다.

winecfg 에서 운영체제 설정은 Windows XP, WINEARCH는 win32로 되어있습니다.
사용 운영체제는 Xubuntu 17.04 이고 wine 버전은 winehq ppa의 wine-stable(2.0.2~zesty)입니다.

**Comment by cogniti** [comment]
안녕하세요.
`Ignore XIMPreeditCallbacks` 옵션을 켜면(on) 입력할 때 조합 중인 글자를 표시해주는 작은 창이 나타납니다. 거기에는 정상적으로 표현되나요?

**Comment by cogniti** [comment]
input style  문제일 수도 있으니 확인해보겠습니다.
그런데.. 제가 어떻게 재현해야 되나요?
게임을 하지 않아서 무슨 프로그램을 설치해야 하는지 모릅니다. 좀 알려주세요.

**Comment by alswg1994** [comment]
XIMPreeditCallbacks 설정씨 뜨는 임시 창에 글자는 제대로 뜹니다. 문제는 한 글자가 완성된 후 다음 자음/모음 입력시엔 무시되고 창도 그냥 사라집니다.

하단에 제가 쓰고있는 모든 환경을 적었습니다. 프로그램은 kr.battle.net에서 Blizzard Application만 구동해봐도 될 것 같습니다.

#업데이트
제가 뭘 건드렸는지 모르겠으나 재부팅하고 나니 이제 fcitx때 처럼 아예 한영 전환이 안되네요. fcitx 처럼 notification icon에 한/영 상태표시도 안됩니다. 일반 리눅스 프로그램상예서 텍스트 윈도우에 포커스 안되어있을때 처럼 그냥 빈칸으로 표시되네요.

**Comment by alswg1994** [comment]
업데이트 합니다. 한영 전환이 아예 안되는, 정확히는 와인 프로그램 상에서 nimf 가 입력에 아예 개입하지 않는 문제는 와인 프로그램을 ko_KR.UTF-8 로케일로 실행할때 발생하는거 같습니다. en_US.UTF-8 에서는 nimf를 통해 입력됩니다.

하지만 여전히 처음 문의했던 문제는 남아있고, directx 9 기반 게임인 히어로즈 오브 더 스톰을 실행해 본 결과 채팅은 한글 모드일때 한글 키들이 아예 입력되지 않습니다.

**Comment by cogniti** [comment]
ko_KR.UTF-8 일 때와 en_US.UTF-8 일 때 다르게 동작하는 데 그것은 wine 소스코드에 그렇게 되어 있기 때문입니다.

https://github.com/wine-mirror/wine/blob/master/dlls/winex11.drv/xim.c

```
    /* use complex and slow XIC initialization method only for CJK */
    if (langid != LANG_CHINESE &&
        langid != LANG_JAPANESE &&
        langid != LANG_KOREAN)
    {
        xic = XCreateIC(xim,
                        XNInputStyle, XIMPreeditNothing | XIMStatusNothing,
                        XNClientWindow, win,
                        XNFocusWindow, win,
                        XNDestroyCallback, &destroy,
                        NULL);
        data->xic = xic;
        return xic;
    }
```

**Comment by alswg1994** [comment]
네. en_US.UTF-8 로케일 사용도 괜찮으니 그 문제는 괜찮습니다. 지금 상황에선 en_US.UTF-8 로케일 상에서도 발생하는 문제들만 해결되었으면 좋겠습니다.

**Comment by cogniti** [comment]
Battle.net-Setup.exe 설치하여 실행했는데 에러가 계속 나서 확인할 수 없습니다.
Battle.net-Setup.exe 프로그램 제외하고 다른 어떤 프로그램으로 테스트하면 될까요?
![screenshot from 2017-12-28 07-58-16](https://user-images.githubusercontent.com/17453239/34395629-33470b00-eba5-11e7-8fae-77126008e674.png)

**Comment by cogniti** [comment]
Heroes-of-the-Storm-Setup.exe 설치하였습니다.
에러가 계속 나서 확인할 수 없었습니다.
wine 프로젝트에 문의하시기 바랍니다.
![screenshot from 2017-12-28 08-06-35](https://user-images.githubusercontent.com/17453239/34395731-32b615ae-eba6-11e7-81cc-85d9ec514750.png)
