### ISSUE TITLE
한자창이 빈 흰색창으로만 떠요.

### ISSUE THREAD

**Issue by iyagicom** [cogniti/nimf#64]
한자입력을 어떻게 해야 되나요?

**Comment by cogniti** [comment]
무슨 글자가 빈 흰색창으로 뜨나요?

**Comment by cogniti** [comment]
"한"에 해당하는 한자를 입력하기 위해서는
"한"이라는 글자를 친 상태에서 한자키를 누르시면 한자 목록이 뜹니다.
만약 해당하는 한자가 없을 경우 흰색창만 뜹니다.
현재는 조합 중이 글자가 없을 때에도 한자키를 눌렀을 때, 창이 뜹니다. 그 경우 매칭되는 한자가 없기 때문에 창에 아무 글자도 나오지 않습니다.
사람들이 MS 입력에 익숙하기 때문에 조합 중일 때 한자키를 누르면 한자 목록이 뜨도록 구현했습니다.

원래는 다음처럼 구현하려고 했었습니다.
한자키를 누르면 한자창이 뜨는데 거기에 한글을 입력하면 해당하는 한자 목록이 뜨도록 하려고 했습니다.
중국어 입력하는 방법처럼 변경하고 싶지만 그렇게 하면 불편하다는 분이 계실까봐 현행 유지(MS방식)하고 있습니다.

**Comment by cogniti** [comment]
한자 입력 방법 변경을 원하시면 따로 이슈를 만들어 주시기 바랍니다. 추석 잘 보내세요

**Comment by iyagicom** [comment]
지금은 잘 되네요.
아마도 중국어로 바꾸고 중국어쓰고 한글으로 바꾸고 한글쓰고 하는 과정에서 꼬인것 같아요.
그리고,
중국어 입력하고 한글입력할려고 한글키누르고 그러다 보면 nimf가 뜅겨요.

**Comment by cogniti** [comment]
무슨 말씀이신지 이해가 안 되요

**Comment by cogniti** [comment]
nimf-settings 를 실행하여
중국어 엔진 (nimf-rime) 전환 단축키, 한국어 엔진 (nimf-libhangul) 단축키를 등록하신 후 사용하세요.
말씀을 들어보니 이미 한국어 엔진 전환 단축키로 한글키가 등록되어 있는거 같으니 중국어 엔진 전환키만 등록하시면 되겠네요
그리고 제가 이해할 수 있도록 설명해 주세요.
설명하기 어려우면 스크린샷이라도 올려주시던가요.
제 시간도 소중하답니다.
저를 존중해 주세요.
