### ISSUE TITLE
nimf-daemon does not auto-start on Ubuntu 17.10 xwayland

### ISSUE THREAD

**Issue by 5HARK** [cogniti/nimf#66]
Ubuntu 17.10 Desktop 64bit 버전 설치 직후 cogniti PPA 통해서 nimf 설치시 여러가지 필요한 패키지와 함께 nimf 가 설치되는데 설치 이후 시스템이 극도로 느려지고 nimf-daemon 이 im-config 통해서 실행되지 않는 문제가 있습니다.
우분투 설치직후 아무 작업도 하지 않은채 nimf 만 설치했을때도 같은 증상입니다.
수동으로 nimf-daemon 을 실행시켜 주면 nimf 를 통한 한글입력은 잘 되나 시스템이 전체적으로 느려진 현상은 그대로 였습니다.

nimf 설치시 apt-get 로그와 gedit 실행시 표준 출력으로 출력되는 nimf 관련 에러 로그도 첨부하였습니다.

> Log started: 2017-10-21  01:22:15
> Selecting previously unselected package anthy-common.
> (데이터베이스 읽는중 ...
> (데이터베이스 읽는중 ...5%
> (데이터베이스 읽는중 ...10%
> (데이터베이스 읽는중 ...15%
> (데이터베이스 읽는중 ...20%
> (데이터베이스 읽는중 ...25%
> (데이터베이스 읽는중 ...30%
> (데이터베이스 읽는중 ...35%
> (데이터베이스 읽는중 ...40%
> (데이터베이스 읽는중 ...45%
> (데이터베이스 읽는중 ...50%
> (데이터베이스 읽는중 ...55%
> (데이터베이스 읽는중 ...60%
> (데이터베이스 읽는중 ...65%
> (데이터베이스 읽는중 ...70%
> (데이터베이스 읽는중 ...75%
> (데이터베이스 읽는중 ...80%
> (데이터베이스 읽는중 ...85%
> (데이터베이스 읽는중 ...90%
> (데이터베이스 읽는중 ...95%
> (데이터베이스 읽는중 ...100%
> (데이터베이스 읽는중 ...현재 127915개의 파일과 디렉터리가 설치되어 있습니다.)
> Preparing to unpack .../00-anthy-common_9100h-25ubuntu1_all.deb ...
> Unpacking anthy-common (9100h-25ubuntu1) ...
> Selecting previously unselected package libmng2:amd64.
> Preparing to unpack .../01-libmng2_2.0.2-0ubuntu3_amd64.deb ...
> Unpacking libmng2:amd64 (2.0.2-0ubuntu3) ...
> Selecting previously unselected package libdouble-conversion1:amd64.
> Preparing to unpack .../02-libdouble-conversion1_2.0.1-4ubuntu1_amd64.deb ...
> Unpacking libdouble-conversion1:amd64 (2.0.1-4ubuntu1) ...
> Selecting previously unselected package libqt5core5a:amd64.
> Preparing to unpack .../03-libqt5core5a_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking libqt5core5a:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package libqt5dbus5:amd64.
> Preparing to unpack .../04-libqt5dbus5_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking libqt5dbus5:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package libqt5network5:amd64.
> Preparing to unpack .../05-libqt5network5_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking libqt5network5:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package libxcb-xinerama0:amd64.
> Preparing to unpack .../06-libxcb-xinerama0_1.12-1ubuntu1_amd64.deb ...
> Unpacking libxcb-xinerama0:amd64 (1.12-1ubuntu1) ...
> Selecting previously unselected package libqt5gui5:amd64.
> Preparing to unpack .../07-libqt5gui5_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking libqt5gui5:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package libqt5widgets5:amd64.
> Preparing to unpack .../08-libqt5widgets5_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking libqt5widgets5:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package libqt5svg5:amd64.
> Preparing to unpack .../09-libqt5svg5_5.9.1-2_amd64.deb ...
> Unpacking libqt5svg5:amd64 (5.9.1-2) ...
> Selecting previously unselected package libanthy0:amd64.
> Preparing to unpack .../10-libanthy0_9100h-25ubuntu1_amd64.deb ...
> Unpacking libanthy0:amd64 (9100h-25ubuntu1) ...
> Selecting previously unselected package anthy.
> Preparing to unpack .../11-anthy_9100h-25ubuntu1_amd64.deb ...
> Unpacking anthy (9100h-25ubuntu1) ...
> Selecting previously unselected package libboost-regex1.62.0:amd64.
> Preparing to unpack .../12-libboost-regex1.62.0_1.62.0+dfsg-4build3_amd64.deb ...
> Unpacking libboost-regex1.62.0:amd64 (1.62.0+dfsg-4build3) ...
> Selecting previously unselected package libchewing3-data.
> Preparing to unpack .../13-libchewing3-data_0.5.1-1_all.deb ...
> Unpacking libchewing3-data (0.5.1-1) ...
> Selecting previously unselected package libchewing3:amd64.
> Preparing to unpack .../14-libchewing3_0.5.1-1_amd64.deb ...
> Unpacking libchewing3:amd64 (0.5.1-1) ...
> Selecting previously unselected package libgflags2.2.
> Preparing to unpack .../15-libgflags2.2_2.2.1-1_amd64.deb ...
> Unpacking libgflags2.2 (2.2.1-1) ...
> Selecting previously unselected package libunwind8.
> Preparing to unpack .../16-libunwind8_1.1-4.1ubuntu2_amd64.deb ...
> Unpacking libunwind8 (1.1-4.1ubuntu2) ...
> Selecting previously unselected package libgoogle-glog0v5.
> Preparing to unpack .../17-libgoogle-glog0v5_0.3.5-1_amd64.deb ...
> Unpacking libgoogle-glog0v5 (0.3.5-1) ...
> Selecting previously unselected package libleveldb1v5:amd64.
> Preparing to unpack .../18-libleveldb1v5_1.20-1_amd64.deb ...
> Unpacking libleveldb1v5:amd64 (1.20-1) ...
> Selecting previously unselected package mysql-common.
> Preparing to unpack .../19-mysql-common_5.8+1.0.2ubuntu1_all.deb ...
> Unpacking mysql-common (5.8+1.0.2ubuntu1) ...
> Selecting previously unselected package libmysqlclient20:amd64.
> Preparing to unpack .../20-libmysqlclient20_5.7.19-0ubuntu1_amd64.deb ...
> Unpacking libmysqlclient20:amd64 (5.7.19-0ubuntu1) ...
> Selecting previously unselected package libopencc2-data.
> Preparing to unpack .../21-libopencc2-data_1.0.4-5_all.deb ...
> Unpacking libopencc2-data (1.0.4-5) ...
> Selecting previously unselected package libopencc2:amd64.
> Preparing to unpack .../22-libopencc2_1.0.4-5_amd64.deb ...
> Unpacking libopencc2:amd64 (1.0.4-5) ...
> Selecting previously unselected package qtcore4-l10n.
> Preparing to unpack .../23-qtcore4-l10n_4%3a4.8.7+dfsg-7ubuntu1_all.deb ...
> Unpacking qtcore4-l10n (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqtcore4:amd64.
> Preparing to unpack .../24-libqtcore4_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqtcore4:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-xml:amd64.
> Preparing to unpack .../25-libqt4-xml_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-xml:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqtdbus4:amd64.
> Preparing to unpack .../26-libqtdbus4_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqtdbus4:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package qtchooser.
> Preparing to unpack .../27-qtchooser_63-g13a3d08-1_amd64.deb ...
> Unpacking qtchooser (63-g13a3d08-1) ...
> Selecting previously unselected package qdbus.
> Preparing to unpack .../28-qdbus_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking qdbus (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-dbus:amd64.
> Preparing to unpack .../29-libqt4-dbus_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-dbus:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-network:amd64.
> Preparing to unpack .../30-libqt4-network_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-network:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-script:amd64.
> Preparing to unpack .../31-libqt4-script_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-script:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-sql:amd64.
> Preparing to unpack .../32-libqt4-sql_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-sql:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-xmlpatterns:amd64.
> Preparing to unpack .../33-libqt4-xmlpatterns_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-xmlpatterns:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqtgui4:amd64.
> Preparing to unpack .../34-libqtgui4_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqtgui4:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-declarative:amd64.
> Preparing to unpack .../35-libqt4-declarative_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-declarative:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libqt4-sql-mysql:amd64.
> Preparing to unpack .../36-libqt4-sql-mysql_4%3a4.8.7+dfsg-7ubuntu1_amd64.deb ...
> Unpacking libqt4-sql-mysql:amd64 (4:4.8.7+dfsg-7ubuntu1) ...
> Selecting previously unselected package libsunpinyin3v5:amd64.
> Preparing to unpack .../37-libsunpinyin3v5_3.0.0~git20160910-1_amd64.deb ...
> Unpacking libsunpinyin3v5:amd64 (3.0.0~git20160910-1) ...
> Selecting previously unselected package libyaml-cpp0.5v5:amd64.
> Preparing to unpack .../38-libyaml-cpp0.5v5_0.5.2-4ubuntu1_amd64.deb ...
> Unpacking libyaml-cpp0.5v5:amd64 (0.5.2-4ubuntu1) ...
> Selecting previously unselected package libmarisa0:amd64.
> Preparing to unpack .../39-libmarisa0_0.2.4-8build10_amd64.deb ...
> Unpacking libmarisa0:amd64 (0.2.4-8build10) ...
> Selecting previously unselected package librime1.
> Preparing to unpack .../40-librime1_1.2.9+dfsg1-1build1_amd64.deb ...
> Unpacking librime1 (1.2.9+dfsg1-1build1) ...
> Selecting previously unselected package sunpinyin-data.
> Preparing to unpack .../41-sunpinyin-data_0.1.22+20170109-1_amd64.deb ...
> Unpacking sunpinyin-data (0.1.22+20170109-1) ...
> Selecting previously unselected package nimf.
> Preparing to unpack .../42-nimf_2017.08.20.1~artful_amd64.deb ...
> Unpacking nimf (2017.08.20.1~artful) ...
> Selecting previously unselected package qt-at-spi:amd64.
> Preparing to unpack .../43-qt-at-spi_0.4.0-5_amd64.deb ...
> Unpacking qt-at-spi:amd64 (0.4.0-5) ...
> Selecting previously unselected package qt5-gtk-platformtheme:amd64.
> Preparing to unpack .../44-qt5-gtk-platformtheme_5.9.1+dfsg-10ubuntu1_amd64.deb ...
> Unpacking qt5-gtk-platformtheme:amd64 (5.9.1+dfsg-10ubuntu1) ...
> Selecting previously unselected package qttranslations5-l10n.
> Preparing to unpack .../45-qttranslations5-l10n_5.9.1-1_all.deb ...
> Unpacking qttranslations5-l10n (5.9.1-1) ...
> Selecting previously unselected package librime-bin.
> Preparing to unpack .../46-librime-bin_1.2.9+dfsg1-1build1_amd64.deb ...
> Unpacking librime-bin (1.2.9+dfsg1-1build1) ...
> Selecting previously unselected package librime-data-cangjie5.
> Preparing to unpack .../47-librime-data-cangjie5_0.35-1_amd64.deb ...
> Unpacking librime-data-cangjie5 (0.35-1) ...
> Selecting previously unselected package librime-data-luna-pinyin.
> Preparing to unpack .../48-librime-data-luna-pinyin_0.35-1_amd64.deb ...
> Unpacking librime-data-luna-pinyin (0.35-1) ...
> Selecting previously unselected package librime-data.
> Preparing to unpack .../49-librime-data_0.35-1_all.deb ...
> Unpacking librime-data (0.35-1) ...
> libanthy0:amd64 (9100h-25ubuntu1) 설정하는 중입니다 ...
> libxcb-xinerama0:amd64 (1.12-1ubuntu1) 설정하는 중입니다 ...
> librime-data-cangjie5 (0.35-1) 설정하는 중입니다 ...
> Processing triggers for libgtk2.0-0:amd64 (2.24.31-2ubuntu1) ...
> libgflags2.2 (2.2.1-1) 설정하는 중입니다 ...
> libopencc2-data (1.0.4-5) 설정하는 중입니다 ...
> libdouble-conversion1:amd64 (2.0.1-4ubuntu1) 설정하는 중입니다 ...
> qtcore4-l10n (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> Processing triggers for libglib2.0-0:amd64 (2.54.1-1ubuntu1) ...
> mysql-common (5.8+1.0.2ubuntu1) 설정하는 중입니다 ...
> update-alternatives: using /etc/mysql/my.cnf.fallback to provide /etc/mysql/my.cnf (my.cnf) in auto mode
> libboost-regex1.62.0:amd64 (1.62.0+dfsg-4build3) 설정하는 중입니다 ...
> qtchooser (63-g13a3d08-1) 설정하는 중입니다 ...
> anthy-common (9100h-25ubuntu1) 설정하는 중입니다 ...
> sunpinyin-data (0.1.22+20170109-1) 설정하는 중입니다 ...
> libmng2:amd64 (2.0.2-0ubuntu3) 설정하는 중입니다 ...
> Processing triggers for libgtk-3-0:amd64 (3.22.24-0ubuntu1) ...
> libleveldb1v5:amd64 (1.20-1) 설정하는 중입니다 ...
> libsunpinyin3v5:amd64 (3.0.0~git20160910-1) 설정하는 중입니다 ...
> libmarisa0:amd64 (0.2.4-8build10) 설정하는 중입니다 ...
> libopencc2:amd64 (1.0.4-5) 설정하는 중입니다 ...
> libunwind8 (1.1-4.1ubuntu2) 설정하는 중입니다 ...
> Processing triggers for libc-bin (2.26-0ubuntu2) ...
> libqtcore4:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libgoogle-glog0v5 (0.3.5-1) 설정하는 중입니다 ...
> libchewing3-data (0.5.1-1) 설정하는 중입니다 ...
> qttranslations5-l10n (5.9.1-1) 설정하는 중입니다 ...
> Processing triggers for man-db (2.7.6.1-2) ...
> libmysqlclient20:amd64 (5.7.19-0ubuntu1) 설정하는 중입니다 ...
> libyaml-cpp0.5v5:amd64 (0.5.2-4ubuntu1) 설정하는 중입니다 ...
> anthy (9100h-25ubuntu1) 설정하는 중입니다 ...
> Updating anthy.dic...file name prefix=[./] you can change this by -p option.
>   copying .///mkworddic/anthy.wdic (word_dic)
>   copying .///depgraph/anthy.dep (dep_dic)
>   copying .///calctrans/anthy.trans_info (trans_info)
>   copying .///calctrans/anthy.cand_info (cand_info)
>   copying .///calctrans/anthy.weak_words (weak_words)
>   copying .///calctrans/anthy.corpus_bucket (corpus_bucket)
>   copying .///calctrans/anthy.corpus_array (corpus_array)
> /usr/bin/mkfiledic done.
> done.
> librime-data-luna-pinyin (0.35-1) 설정하는 중입니다 ...
> Processing triggers for hicolor-icon-theme (0.17-1) ...
> libqt4-xml:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt5core5a:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> libqt5dbus5:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> libqt5network5:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> libqt4-sql:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libchewing3:amd64 (0.5.1-1) 설정하는 중입니다 ...
> librime-data (0.35-1) 설정하는 중입니다 ...
> librime1 (1.2.9+dfsg1-1build1) 설정하는 중입니다 ...
> libqt5gui5:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> qt5-gtk-platformtheme:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> libqtdbus4:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt5widgets5:amd64 (5.9.1+dfsg-10ubuntu1) 설정하는 중입니다 ...
> libqt4-script:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt4-sql-mysql:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> librime-bin (1.2.9+dfsg1-1build1) 설정하는 중입니다 ...
> qdbus (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt5svg5:amd64 (5.9.1-2) 설정하는 중입니다 ...
> libqt4-dbus:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt4-network:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqt4-xmlpatterns:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> libqtgui4:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> qt-at-spi:amd64 (0.4.0-5) 설정하는 중입니다 ...
> nimf (2017.08.20.1~artful) 설정하는 중입니다 ...
> libqt4-declarative:amd64 (4:4.8.7+dfsg-7ubuntu1) 설정하는 중입니다 ...
> Processing triggers for libc-bin (2.26-0ubuntu2) ...
> Log ended: 2017-10-21  01:22:29

> 
> $ gedit /var/log/apt/term.log
> 
> (gedit:1801): nimf-CRITICAL **: nimf-client.c:263: nimf_client_constructed: 연결할 수 없습니다: 연결이 거부됨
> 
> (gedit:1801): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed
> 
> (gedit:1801): nimf-WARNING **: socket is closed
> 
> (gedit:1801): nimf-CRITICAL **: nimf-client.c:263: nimf_client_constructed: 연결할 수 없습니다: 연결이 거부됨
> 
> (gedit:1801): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed
> 
> (gedit:1801): nimf-WARNING **: socket is closed
> 
> (gedit:1801): nimf-CRITICAL **: nimf-client.c:263: nimf_client_constructed: 연결할 수 없습니다: 연결이 거부됨
> 
> (gedit:1801): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed
> 
> (gedit:1801): nimf-WARNING **: socket is closed
> 
> (gedit:1801): GLib-GIO-CRITICAL **: g_socket_connection_get_socket: assertion 'G_IS_SOCKET_CONNECTION (connection)' failed
> 
> (gedit:1801): nimf-WARNING **: socket is closed
>

**Comment by 5HARK** [comment]
> sudo apt purge nimf

를 통해 님프 삭제시 시스템이 느려지는 현상은 없어졌습니다.

**Comment by cogniti** [comment]
nimf 는 동기화 방식의 입력기입니다.
nimf-daemon 이 실행되지 않아서 nimf-daemon 서버에 접속되기를 기다리기 때문에 느려지는 것입니다. 그렇다고 해서 비동기 방식으로 변경하면 프로그램 실행하자마자 곧바로 입력할 때 영문 글자가 나오다가 한글이 나오는 현상이 발생할 수 있습니다.

우분투 17.10 은 xorg 가 아닌 xwayland 가 사용됩니다. 기존의 설정 방식이 작동되지 않습니다.
어떻게 nimf-daemon 을 자동 실행하는 것이 적절한 방법인지 충분히 고려한 후에 스크립트를 수정하도록 하겠습니다.

일단 아래 링크 참고하셔서 해결하시기 바랍니다.

https://wiki.archlinux.org/index.php/autostarting

**Comment by cogniti** [comment]
아래 내용을 `nimf.desktop` 파일로 저장합니다.

```
[Desktop Entry]
Name=Nimf
GenericName=Input Method
Comment=Start Input Method
Exec=nimf-daemon
Icon=nimf-logo
Terminal=false
Type=Application
Categories=System;Utility;
StartupNotify=false
X-GNOME-AutoRestart=false
X-GNOME-Autostart-Notify=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false
```

`/etc/xdg/autostart/` 에 `nimf.desktop` 파일을 복사하세요.

**Comment by nemonein** [comment]
안녕하세요. 일부러 홈페이지까지 와주셔서 고맙습니다.
결론부터 말씀드리면, 제 문제는 이 문제와는 큰 연관은 없어보입니다. 저 문제는 Wayland 와 연관이 있어보이는데요, 쿠분투는 17.10 에서도 X 를 사용하기 때문에 Nimf 작동엔 전혀 문제가 없습니다.

다른 분들이 보실까 하여 설명을 드리면..

쿠분투 17.04 를 사용 중이다가, 쿠분투 17.10 으로 판올림을 하였습니다.
그러고 나니, Nimf 알리미(Indicator)가 쿠분투 패널 시스템 트레이에서 사라지는 현상이 생겼습니다.
이게 좀 이상한데요. 어떨 땐 보이고, 어떨 땐 사라지고 합니다. 시스템 사용 중에 보였다가 안보였다가 하는 건 아니고, 어떨 때 키면(부팅 시에) 떠있고, 또 어떨 때는 없고 하는 현상이 반복됩니다.

말씀해주신 desktop 파일을 생성/저장(/etc/xdg/autostart 또는 ~/.config/autostart)해봤지만 결과는 동일했습니다.

17.04에서 판올림하지 않고, 17.10 을 바로 설치한 뒤 Nimf 를 설치했을 경우엔 이런 현상이 생기지 않는 걸 보면, 업그레이드 되면서 뭔가 문제가 생긴 듯 합니다.
Indicator 가 보이든, 보이지 않든, Nimf Daemon 이 뜨고 실행되는데는 아무 지장이 없습니다. 그저 알리미가 보이지 않을 뿐이죠. nimf-settings 도 이상없이 잘 실행됩니다.

그런데, 약간 이상한 점은 있습니다. 17.04 -> 17.10 인 PC에서, 간헐적으로 Nimf 아이콘이 뜰 때, System Tray 에서 모양이 조금 달라보입니다.
![nimf-icon](https://user-images.githubusercontent.com/5688288/31984320-1dc61284-b99c-11e7-8fa8-17bd4be2f8a1.jpg)
17.04 에서는 각 모서리에 테두리(?)로 보이는 굵은 선이 없었는데 말이죠.

17.10 에선 이렇지 않고 정상으로 보이는 듯 합니다.
현재 시스템은 17.04 에서 판올림한 것이고, 17.10을 새로 설치한 건 시험용으로만 잠깐 사용해봤기 때문에, 다른 문제가 또 있는지는 모르겠습니다.

아무튼.
Nimf 가 오작동을 하거나 작동을 안한다면 모를까, 제 문젠 별 거 아니니 굳이 신경 안쓰셔도 됩니다. ^^
고맙습니다.

추가로,
VBox 에서 설치한 Ubuntu 17.10 에선, 위 방법으로 Nimf 가 잘 작동합니다.
저는 ~/.config/autostart 에 파일을 넣어서 시험해봤습니다.

**Comment by cogniti** [comment]
상세한 답변 고맙습니다.
