### ISSUE TITLE
wine에서 입력시 nimf가 disable됩니다(fedora 26)

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#67]
fedora26에서 카카오톡을 설치 후 사용중인데, 영어 입력에는 아무런 문제가 없으나, 한글 입력은 안됩니다.
제 생각에는 wine에서 nimf가 완전히 disable돼고, gnome의 기본 입력기로 입력이 되는 것으로 보고 있는데, 오류 수정 부탁드립니다.

**Comment by cogniti** [comment]
안녕하세요. wine 외에 다른 프로그램에서는 한글이 입력되나요?

**Comment by Hong-SeJung** [comment]
네
wine의 notepad에서도 확인을 해보았지만, 입력이 되지 않습니다.

**Comment by cogniti** [comment]
`export XMODIFIERS="@im=nimf"` 설정이 되어 있나요?

**Comment by Hong-SeJung** [comment]
어떤 파일에요?

**Comment by cogniti** [comment]
아마 설정 문제 같은데 rpm 패키지를 제가 만드는게 아니라서 https://copr.fedorainfracloud.org/coprs/workman729/nimf/ 에 문의해 주세요

**Comment by Hong-SeJung** [comment]
네

**Comment by cogniti** [comment]
페도라 27에서 확인해봤습니다.
터미널에서 아래처럼 실행했는데 한글 입력 잘 됩니다.

```
env XMODIFIERS="@im=nimf" WINEPREFIX="/home/hodong/.wine" /usr/bin/wine C:\\\\windows\\\\command\\\\start.exe /Unix "/home/hodong/.wine/dosdevices/C:\Program Files (x86)\Kakao\KakaoTalk\KakaoTalk.exe"
```

**Comment by Hong-SeJung** [comment]
그렇군요
