### ISSUE TITLE
wine issue with Kakaotalk on Arch Linux

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#68]
nimf로 kakaotalk을 wine으로 실행해 입력할 때, 네모상자는 나오는데 입력은 안되는 현상이 있습니다

**Comment by cogniti** [comment]
아치 리눅스에 nimf, wine, kakaotalk 설치하여 확인해봤는데 한글 입력 잘 되네요.
글자가 네모로 나오면 한글 폰트 설정을 해보세요.
![20171218_063214](https://user-images.githubusercontent.com/17453239/34084046-77c36b2e-e3bd-11e7-846f-594c130759cd.jpg)
