### ISSUE TITLE
 언어를 바꿀수 없고 언어 설정이 안되는 문제

### ISSUE THREAD

**Issue by Ehztot** [cogniti/nimf#69]
안녕하세요 일반사용자로 nimf를 감사하게 사용하고 있습니다. 
다름이 아니라 이번에 시스템을 업데이트 하고 나서 다음과 같은 문제가 생겨 글을 작성하게 되었습니다.

1. 영어에서 다른 언어로 전환이 되지 않음
2. 설정에서 언어와 관련한 다른 항목이 보이지 않음 

제가 뭘 잘못 건드린 걸까요?
가능한 해결책이 있다면 부탁드리겠습니다. 

![2017-12-20 00-38-44](https://user-images.githubusercontent.com/26058269/34165177-e661f5de-e51e-11e7-9672-9451cc8a6e70.png)

우분투 16.04.3 lts
커널 x86_64 Linux 4.4.0-105-generic
데스크톱 환경 gnome 3

감사합니다.

**Comment by cogniti** [comment]
안녕하세요.
기존에 하나였던 패키지를 언어별로 여러 개로 나눠었습니다.

한글 입력이 안 되시면 nimf-libhangul 를 설치해주세요

`sudo apt install nimf-libhangul`

nimf-anthy: Japanese input module for Nimf, based on anthy
nimf-chewing: Chinese input module for Nimf, based on chewing
nimf-libhangul: Korean input module for Nimf, based on libhangul
nimf-rime: Chinese input module for Nimf, based on rime
nimf-sunpinyin: Chinese input module for Nimf, based on sunpinyin
