### ISSUE TITLE
hook-gdk-event-key 관련, Terminator 에서 Broadcating 이 되지 않는 문제.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#7]
안녕하세요, 오랜만에 인사드립니다.
#2 에서도 이와 관련한 문의를 드렸었는데요.
오늘 좀 이상한 현상을 발견하여 질문드리고자 합니다.

Terminator(http://gnometerminator.blogspot.kr/p/introduction.html) 에는 터미널을 분할하여 같은 명령을 동시에 내려줄 수 있는 기능이 있습니다. 이것을 Broadcast 라고 하는데요.

hook-gdk-event-key 가 True 로 되어 있으면 이 기능이 작동하지 않습니다.
'엔터' 키는 작동하는데.. 그외 일반 키들은 한쪽에만 입력이 되네요.

시간 되실 때 살펴봐주시길 부탁드립니다.
고맙습니다.

**Comment by cogniti** [comment]
문제점을 확인했습니다.
`hook-gdk-event-key` 가 `true` 로 되어 있을 때 Broadcast 가 작동하지 않는 것은 nimf 에서 어찌할 수 있는 방법이 없습니다. ibus, fcitx, imhangul, uim 은 `gtk_key_snooper_install()` 을 사용하여 후킹하고 있으므로 마찬가지 현상이 나타날 것입니다. ibus, fcitx, imhangul, uim 은 실행 중에 후킹을 on/off 할 수 있는 옵션이 없습니다.

그런데 nimf 에서 `hook-gdk-event-key` 옵션을 끄면 동시 입력할 때 한글이 정상적으로 입력되지 않는 문제가 있습니다.
Terminator 에서 Broadcast 기능은 키보드 두 개를 동시에 입력하는 것과 동일한 상황이 됩니다.
nimf 설계할 때 키보드 두 개를 입력하는 상황을 전혀 고려하지 않았고 키보드 1개로만 입력하는 상황만을 고려하여 엔진을 싱글톤(singleton) 방식으로 설계하였습니다.
nimf 에서 이 문제를 해결하기 위해서는 엔진 인스턴스를 여러 개 생성할 수 있는 옵션을 추가해야 합니다.
두 가지 상이한 방식이 공존해야 하는데 많은 테스트를 필요로 하는 작업이므로 이 문제를 해결하는데에는 오랜 시간이 걸릴 것 같습니다. 감사합니다.

**Comment by nemonein** [comment]
확인해주셔서 고맙습니다.

말씀하신 것 중, fcitx(우분투 16.04) 로는 Terminator Brodcast 기능이 이상없이 작동합니다. 아울러 Double Commander 에서 입력도 잘 됩니다. 다른 입력기로는 확인해보지 못했습니다.

(앞으로 나올) 설정프로그램에서 hook-gdk-event-key 을 좀 더 쉽게 켜고 끌 수 있다면 이 문제를 살짝 피해갈 수 있을 것도 같습니다. 지금처럼 Dconf-editor 를 열기엔 좀 번거롭거든요.

생각해보니.. 터미네이터에서 바로 명령어를 사용해서 hook-gdk-event-key 를 꺼도 되겠네요.
(gsettings set org.nimf.clients.gtk hook-gdk-event-key false)
자주 쓸 거라면 alias 를 이용하면 될 것 같습니다.

**Comment by cogniti** [comment]
nimf-settings 가 이번달 릴리즈에 포함될 예정입니다.
후킹 상태일 때, 타 입력기가 어떻게 작동하는지 확인해 보겠습니다.
싱글톤 방식은 두 명이 두 개의 키보드로 동시 입력할 때 부작용이 필연적으로 발생합니다.
시간이 다소 걸리더라도 이 문제를 해결할 수 있는 정상적인 방식을 도입하여 두 방식이 공존할 수 있도록 하겠습니다. 감사합니다.
2016. 6. 1. 오후 12:00에 "JH" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
릴리즈했습니다. https://github.com/cogniti/nimf/releases/tag/2016.06.02
nimf-settings 가 포함되었습니다.
hook-gdk-event-key 설정은 아래 그림을 참고하세요.

nimf 표시기를 클릭하면 Settings 라는 메뉴가 나옵니다. 그걸 클릭하세요.
(터미널에서 nimf-settings 를 실행하셔도 됩니다.)
![screenshot from 2016-06-02 01 42 00](https://cloud.githubusercontent.com/assets/17453239/15717776/77223f18-2863-11e6-8b25-21cb9afb08c8.png)

왼쯕에 GTK+ 를 클릭하시고 오른쪽에 hooking gdk key events 를 on / off 하시면 되겠습니다.
![screenshot from 2016-06-02 01 42 17](https://cloud.githubusercontent.com/assets/17453239/15717784/7f5a5044-2863-11e6-884f-68085ae0e052.png)

총 5번의 클릭으로 설정할 수 있습니다.
`hook-gdk-event-key` 기능을 서브 메뉴로 만들면 2번만 클릭할 수 있겠지만, 그렇게는 하지 않겠습니다.
응용 어플리케이션을 수정하는 것이 바람직한 방법입니다.
사실 싱글톤 방식을 사용하는 이유도 버그 어플이 너무 많아서 그렇습니다.
일례로 이클립스를 사용하면 최소 30개~1000개 이상의 im context 를 호출을 하는데 싱글톤 방식에서는 서버측에 1개의 엔진 인스턴스가 생성되지만, 싱글톤 방식이 아닌 보통의 방식에서는 30개~1000개의 엔진 인스턴스가 생성됩니다. 엔진에서 소비하는 메모리가 최소 30메가~ 1GB 이상 소비가 되겠죠. 하지만 싱글톤 방식에서는 3메가 정도만 소비합니다. 중국어 또는 일본어 쪽은 메모리 소비가 더 많이 발생합니다.
따라서 싱글톤 방식이 아닌 보통 방식은 얻을 수 있는 잇점이 거의 없으므로
다른 일정들을 우선적으로 해결한 후에 구현하겠습니다. 감사합니다.

**Comment by cogniti** [comment]
그리고 키 이름이 변경되었으므로  키 설정을 다시 하셔야 합니다.
어떻게 변경되었는지는 아래 링크 참고하세요.
http://cogniti-works.blogspot.kr/2016/05/nimf_30.html

**Comment by nemonein** [comment]
고맙습니다!

**Comment by nemonein** [comment]
고생하셨습니다!
잘 쓰겠습니다. 고맙습니다.
