### ISSUE TITLE
KDE 에서 좌상귀를 클릭했을 때 Nimf 설정이 뜨는 경우가 있습니다.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#70]
안녕하세요.
언어별로 구분된 새 판이 올라왔네요.
새롭게 만들어 주셔서 고맙습니다.

오늘 드릴 말씀은 이전 판(2017.08)부터 있었던 문제입니다.
KDE 데스크탑(정확하게는 쿠분투 17.10)에서 님프를 사용할 경우, 데스크탑 좌상귀--그냥 빈공간을 클릭했을 때 님프 설정이 뜨는 현상이 있습니다. 쿠분투 17.04까지는 이런 현상이 없었습니다.
또, 제가 최근엔 KDE 만 사용하기에, Gnome 기반 배포판에서도 이런 일이 있는 지는 모르겠습니다.

제가 사용하는 데스크탑/노트북에선 항상 이 현상이 나타나고, VirtualBox 를 사용한 가상 머신에서는 매번은 아니고 간헐적으로 나타납니다. 모두 KDE 17.10 환경입니다.

![kde-nimf-setting](https://user-images.githubusercontent.com/5688288/34206828-7663bb20-e5cb-11e7-8f30-cfd73316a34b.jpg)

위 그림에서 보시는 것처럼, 왼쪽 위 빈공간을 클릭(왼클릭)했는데 님프 설정이 뜨는 현상이 있습니다.
이것을 막으려면, 실제 Nimf Indicator (위 그림에서는 화면 아래쪽에 있는 회색 아이콘) 을 우클릭해서 Nimf 메뉴를 한번이라도 열어야 합니다. 일단 한번 열리고 나면 그 다음부터는 좌상귀를 클릭해도 님프 메뉴가 뜨지 않습니다.

추운 겨울 건강하게 보내시기 바라며,
시간 되실 때 한번 살펴봐 주시면 좋겠습니다.
고맙습니다.

**Comment by cogniti** [comment]
kde 에 screem edge 기능에 버그가 있는 것 같은데 kde 측에 문의해주세요.

**Comment by cogniti** [comment]
appindicator 라이브러리 관련해서도 코드를 검토해보겠습니다.

**Comment by nemonein** [comment]
고맙습니다.
결과 주시면 쿠분투/KDE 쪽에 문의해보도록 하겠습니다.

**Comment by cogniti** [comment]
레노버 이슈 때문에 쿠분투 17.10 을 다운로드할 수 없습니다.

> The download of Kubuntu 17.10 is currently discouraged due to an issue on certain Lenovo laptops. Once fixed this download will be enabled again.

https://github.com/cogniti/nimf/blob/a366dd7c286d4ba19d276f55be103a370e7c8d74/modules/services/indicator/nimf-indicator.c#L226

`gtk_widget_show_all (menu_shell);`을 삭제하고 컴파일한 후 설치후 테스트 해보세요.

컴파일 방법은 아래 링크를 참고하세요.
https://cogniti.github.io/nimf/ko/support.html

**Comment by nemonein** [comment]
알려주신대로 gtk_widget_show_all (menu_shell); 을 삭제하고 빌드하여 실행해봤습니다.

그런데, 이렇게 해도 문제는 동일합니다.
다만, 아예 님프 설정 메뉴가 나타나지 않고 작은 막대만 보입니다.
![kde-nimf-setting-2](https://user-images.githubusercontent.com/5688288/34316846-b59c1530-e7e2-11e7-9b2b-ba8f024b3e64.jpg)
위 그림은 Nimf Indicator 를 클릭(KDE 에서는 오른클릭)했을 때 나타나는 메뉴를 갈무리한 것입니다.

마찬가지로, 화면 좌상귀 빈 곳을 클릭했을 때도 동일한 막대가 보입니다.
![kde-nimf-setting-1](https://user-images.githubusercontent.com/5688288/34316850-e4cd9b9e-e7e2-11e7-976d-cac4daba69e4.jpg)

의견 부탁드립니다.

**Comment by cogniti** [comment]
nimf-indicator 코드에 이상한 점을 찾지 못했습니다.

인디케이터를 제공하는 어플들이 많이 있습니다.
https://packages.ubuntu.com/search?lang=en&suite=artful&searchon=names&keywords=indicator
다른 인디케이터에서도 이러한 현상이 나타나는지 확인해보겠습니다.
그리고 manjaro kde 환경, debian kde 환경에서 어떠한지 확인해보겠습니다.
타 환경에서 문제가 없다면 kubuntu 문제로 볼 수 있고,
타 환경에서도 문제가 발생한다면 appindicator 의 문제라고 볼 수 있습니다. 그 경우 libayatana-appindicator 라이브러리로 교체를 할 것이고, 그렇게 해도 문제가 해결되지 않으면 다른 라이브러리를 알아보거나 직접 구현하겠습니다.

**Comment by nemonein** [comment]
살펴봐 주셔서 고맙습니다.
제가 사용하는 인디케이터류만 해도 여러 개인데요. 위 그림에 나와있는 걸로만 보면 CopyQ, Autokey-py3, Insync 정도를 들 수 있습니다. 이 중에서 같은 현상을 보이는 것은 없습니다. 정확한 테스트를 위해서는 님프를 사용하지 않은 상태에서 다른 것들을 사용해봐야겠으나..

관련은 없을 듯 하지만, 아이콘에 대해서 말씀드려야겠습니다.
17.10 부터 Nimf 아이콘(위 두번째 그림)이 테두리에 검은 선이 있는 모양으로 뜹니다. 첫번째 그림에 있는 건 안그렇긴 합니다. 첫번째 그림은 VBox 가상머신이고, 두번째는 Intel 그래픽을 사용하는 노트북입니다. (데스크탑에서도 마찬가지로 테두리가 있는 아이콘이 뜹니다.)
17.04 때는 그놈에서 보이는 원래 모양 그대로였는데요. 17.10 부터 이런 현상이 생겼습니다.
또 한가지, 17.04 에서 17.10 으로 업그레이드한 시스템은, 가끔 인디케이터가 아예 뜨지 않는 현상이 있습니다.그럼에도 Nimf 작동에는 이상이 없습니다.
17.10 을 새로 설치한 시스템에선 인디케이터가 안 뜨는 현상은 없습니다.

제가 쿠분투는 17.04 부터 사용하고 있기 때문에, 그 전엔 어땠는지는 모르겠습니다.

원인을 밝히시는데 도움되실까 하여 글 올렸습니다.

**Comment by cogniti** [comment]
/usr/share/im-config/data/70_nimf.rc 파일에
nimf-daemon 라인을 삭제후 다시 테스트 해보세요.
/etc/xdg/autostart/nimf-daemon.desktop 파일로 인하여 nimf-daemon 이 자동실행하기 때문에
/usr/share/im-config/data/70_nimf.rc 파일에서
nimf-daemon 라인을 삭제하여도 무방합니다.
그렇게 하면 KDE panel 이 구동된 다음에 nimf-daemon 이 실행될 겁니다.
그렇게 해도 동일 현상이 나타나면
appindicator 대신에 libayatana-appindicator 라이브러리로 교체하여 테스트를 할 것이고, 그렇게 해도 문제가 해결되지 않으면 다른 라이브러리를 알아보거나 직접 구현하겠습니다.
인디케이터는 nimf-indicator 에서 그림을 그리는 것이 아니라, nimf-indicator 와 데스크탑 패널이 dbus 통신을 하여 데스크탑 패널이 인디케이터를 그려주는 것인데, KDE 패널에 indicator 를 표시해주는 코드에 버그가 있거나, appindicator 라이브러리에 버그가 있으면 뭔가가 서로 맞지 않으면 그러한 현상이 나타날 수 있습니다. 그리고 아이콘 문제는 KDE 환경에서만 발생합니다. nimf-indicator 가 아이콘을 그리지 않습니다. 아이콘 문제는 KDE 문제입니다.

**Comment by cogniti** [comment]
그리고 말씀하신 아이콘 문제는 2016년에 Kubuntu KDE, Manjaro KDE 환경에서도 마찬가지 문제가 발생합니다. 아이콘 관련해서는 제가 할 수 있는 방법이 없습니다.

**Comment by nemonein** [comment]
설명해주신대로 실행해봤습니다.

먼저, `/usr/share/im-config/data/70_nimf.rc `에서, 다음 3개 행을 주석처리하고 실행했습니다.
```
if [ "$IM_CONFIG_PHASE" = 2 ]; then
   nimf-daemon
fi
```

이렇게 하면, 해결되는 문제도 있고, 새로운 문제도 생겨납니다.

**해결된 문제** :

1. 좌상귀 클릭 시 님프 메뉴가 뜨는 현상 : 사라졌습니다.
2. 님프 아이콘에 검은 테두리가 보이는 현상 : 사라졌습니다.
3. 님프 아이콘이 간헐적으로 뜨지 않는 현상 : 사라졌습니다.

위만 보면 아주 성공이라 할 수 있는데요. 새로운 문제점이 또 보입니다.

**발생한 문제** :

1. 부팅 지연 현상
로그인 시에, 사용자 비밀번호를 치고, 데스크탑이 보이는 시점까지 시간을 재보았습니다.

- 기존 방식 (70_nimf.rc 수정 전) : 9.68 초
- 새로운 방식 (70_nimf.rc 수정 후) : 36.56 초
체감으로나, 수치로나 상당한 시간 차가 있습니다.

2. 메모 위젯에서 한국어 입력 전환 불가.
KDE 메모 위젯(바탕화면에 올려놓는 메모 프로그램)에서 한국어 전환이 되지 않습니다.
제가 주로 사용하는 프로그램들은 모두 잘 되는데(구글 크롬, Kate, Konsole 등등), 메모에선 안되네요.
기존 방식으로 했을 땐 문제가 없었는데요.
혹시 if 부분을 모두 삭제해서 그런 현상이 나타나는 걸까요?
하지만 nimf-daemon 만 삭제했을 경우, 로그인 화면에서 비밀번호를 넣었을 때, 다시 로그인 화면으로 되돌아오는 현상이 있습니다.

의견 부탁드립니다.
고맙습니다.

**Comment by cogniti** [comment]
테스트 감사합니다.
문제점을 정확하게 파악했습니다.
nimf 는 GUI 가 없는 server 와,
GUI 가 있는 indicator 모듈, GUI 가 있는 candidate 모듈 등으로 구성되어 있습니다.
말씀하신 문제점들은 실행 순서 때문에 발생하는 것입니다.

nimf-server, kde panel, nimf-indicator, nimf-candicate 이런 순서로 실행시킬 수 있는 방법을 마련하겠습니다.

**Comment by cogniti** [comment]
`--start-indicator` 옵션을 만들겠습니다.
그리고 기존 `nimf-daemon` 이름을 `nimf` 로 변경하겠습니다.

im-config data 파일에 `nimf` 명령을 넣을 것이고,
70_nimf.rc 에 `nimf --start-indicator` 명령을 넣을 것입니다.
70_nimf.* 파일 이름을 23_nimf.* 로 변경하겠습니다.

기존 nimf-daemon 은 없애거나 또는 wrapper 로 교체하겠습니다.

**Comment by cogniti** [comment]
글 작성에 실수가 있었습니다.
xdg autostart 파일에 `nimf --start-indicator` 명령을 넣을 것입니다.
`nimf` 이렇게 명령하면 server daemon 이 실행되지만 indicator 가 실행되지 않을 것이고,

`nimf --start-indicator` 이렇게 명령하면
1. server daemon 이 실행 중이 아닐 때에는 server daemon 을 실행시키고 indicator 모듈을 실행시킬 것이고,
2. server daemon 이 이미 실행 중일 때는 indicator 모듈만 실행시킬 것입니다.

업데이트는 우분투 18.04 버전 출시 전에 있을 예정입니다.

**Comment by nemonein** [comment]
고맙습니다.
잘은 모르지만, 뭔가 손이 많이가는 작업이 될 듯 하군요.
지금도 사용하는데 문제가 있는 건 아니므로, 천천히 작업해주세요.
건강 잘 챙기시고, 좋은 결과 기대하겠습니다.

연말 마무리 잘 하시길 기원합니다.

**Comment by cogniti** [comment]
간단한 작업입니다. 이미 머리 속에서 코딩이 끝났습니다. 손이 많이 가는 작업은 아닙니다.
리눅스, nimf 와 함께 오늘도 즐거운 하루 보내세요.

**Comment by cogniti** [comment]
## `nimf-daemon` 이름을 `nimf` 로 변경하려 하였으나,
## 혼란이 발생할 것으로 예상됨에 따라
## 기존 이름 `nimf-daemon`을 그대로 사용하기로 했습니다.

**Comment by nemonein** [comment]
작업이 빨리 끝나셨네요.
새 판 적용해봤는데, 이번엔 인디케이터가 아예 뜨질 않습니다.
쿠분투 17.10, 데스크탑/노트북/VirtualBox 모두 동일 증상입니다.

우분투 17.10 에선 잘 작동하는 걸로 봐서, KDE 와 약간 문제가 있는 모양입니다.
`nimf-daemon --start-indicator` 라고 실행해봐도 아무런 반응이 없습니다.

확인 부탁드립니다.

**Comment by cogniti** [comment]
데드락 문제가 있었는데 이번에 모듈 만들면서 알았습니다. 벌써 해결했고 곧 업데이트 가능하실 겁니다.

**Comment by cogniti** [comment]
2017.12.28 버전 설치 후 어떤지 알려주세요.

**Comment by nemonein** [comment]
nimf - 2017.12.28.1~artful 을 설치했습니다. (nimf 와 nimf-libhangul 만 설치했습니다.)
그러나 똑같은 증상이 반복됩니다.

인디케이터가 뜨지 않고, `nimf-daemon --start-indicator` 도 반응이 없습니다.
데스크탑(PC), VBox 에서 시험해봤습니다.

**Comment by cogniti** [comment]
업그레이드 후에 안 된다는 이슈 #74 올라왔습니다.
같은 글을 이중으로 작성하기 번거로우니 #74 에서 논의합시다.
