### ISSUE TITLE
12월 18일자로 업데이트 후 한글 입력이 안돼요

### ISSUE THREAD

**Issue by GabBong** [cogniti/nimf#71]
우분투 17.10 사용자입니다.
12월 18일자로 업데이트 된후에 한글 입력이 안됩니다.
님프 설정화면을 보면 한국어 관련 설정이 아예 빠져 있더군요
수정 부탁드립니다.

**Comment by cogniti** [comment]
nimf-libhangul 설치해주세요.

```
sudo apt install nimf-libhangul
```

https://m.facebook.com/groups/164700266901162?view=permalink&id=1519183671452808
