### ISSUE TITLE
nimf 일본어 입력시 히라가나 가타카나 변환 안됨

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#72]
히라가나와 가타카나를 변환할 때 쓰는 키인 F6, F7, F8을 포함해 로마자와 일어 변환 키인 F9, F10을 눌러도 변환이 되지 않습니다.

**Comment by cogniti** [comment]
안녕하세요.
다른 입력기에서 어떻게 동작하는지, nimf 에서는 어떤 동작을 원하시는지 상세하게 작성해주세요

**Comment by cogniti** [comment]
다른 일본어 입력기가 어떻게 작동하는지 조사할 시간이 없습니다.
그리고 어떤 방법이 많이 사용되는지도 잘 모릅니다.
nimf 로 입력을 하면 히라가나로 입력되고, 스페이스키를 누르면 가타카나 변환창이 뜹니다.
좋은 방법이 있으면 작동 방법과 UI 를 작성해주시기 바랍니다.
nimf 에서 히라가나, 가타카나 입력이 가능하므로 이 이슈는 nimf 버그가 아닙니다.
따라서 이슈를 닫겠습니다.
![1514367293645](https://user-images.githubusercontent.com/17453239/34377585-0a4e63c6-eb35-11e7-85fc-3ace29643d20.jpg)
