### ISSUE TITLE
nimf 일본어 입력에 대한 건의 사항

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#73]
전에 "nimf 일본어 입력시 히라가나 가타카나 변환 안됨" 이란 제목으로 제보한 적이 있었는데, 부탁하신 내용과 약간의 수정을 가해 올립니다.

첫번째로, 전에 올렸던 문제입니다. 히라가나와 가타카나를 변환할 때 쓰는 키인 F6, F7, F8와 로마자와 가나 변환 키인 F9, F10을 눌러도 변환이 되지 않습니다. 근본적으로 anthy에서는 이 기능을 지원합니다. anthy를 기본 앤진으로 사용하는 다른 입력기, 예를 들면 ibus, fcitx 등에서는 이 기능이 지원됩니다. 그리고 space바를 누르면 가타가나로 변환이 가능한 건 사실입니다만, 만약 그 단어를 한자로 변환할 수 있을 경우, 가타카나의 순위가 밀려 가장 아래로 밀려나 선택을 하려면 가장 아래로 내려야 합니다. 애초에 일본어 입력기에서 space바가 한자 변환 키인 것을 감안하면 당연한 것입니다. 이러한 문제 때문에 function 키를 사용하는 것이고, 이 기능이 없으면 사용이 많이 어려워집니다.

두번째로, anthy의 gui 설정 기능이 없습니다. 이 기능 중 단어 추가 기능은 따로 구현이 필요 없고 kasumi라는 세팅 툴이 있습니다. 이 툴을 nimf 패키지에 넣어주셨으면 합니다. 그리고 고급 설정 기능도 있는데, 이는 특별한 일 아니면 쓰는 있이 거의 없습니다(온전히 저의 주관적인 생각입니다). 만약 설계하실 계획이 있으시다면 fcitx의 anthy 설정 툴을 모티브로 삼으면 좋을 것 같습니다. 그리고 이건 좀 죄송한 이야기일 수도 있는데, 개발이 끝난 anthy보다는 개발중인 mozc를 사용해보시는 것도 검토해주시면 감사하겠습니다.

제가 입력기에 대한 지식이 그리 많지 않아서 이것밖에는 작성하지 못하겠더군요... 이에 대해서는 양해 부탁드립니다.

**Comment by cogniti** [comment]
fcitx의 펑션키를 확인해보겠습니다.
kasumi 는 GPL 라이선스라 nimf 에 넣을 수 없습니다. nimf 는 LGPL 라이선스입니다.
mozc 는 개발 파일을 제공하지 않으므로 nimf-mozc 개발에 많은 시간이 소요될 것으로 보입니다.
생활비가 있어야 개발 시간을 확보할 수 있는데, 돈이 없어서 nimf-mozc 는 개발하지 않겠습니다.

**Comment by Hong-SeJung** [comment]
답변 감사드립니다. 라이선스 문제가 있었군요.

**Comment by cogniti** [comment]
anthy 라이브러리에서 히라가나, 가타카나 변환 기능을 제공하지만, api 가 좀 이상하게 되어 있어서
あああああああ 을 입력하여 가타카나 변환시키면 ア 이렇게 여러 개로 쪼개져서 반환되어 그걸 다시 하나로 합쳐야 되고, 버퍼를 2중, 3중, 4중으로 여러 개를 사용해야 됩니다.
일본어 입력 관련 라이브러리를 알아봤는데 마땅한 것이 없습니다.
anthy 라이브러리를 이용한 타 입력기를 보더라도 일본어 입력할 때 변환 방법 및 UI 가 불편하긴 마찬가지입니다. 오십보, 백보 차이일 뿐.
위 기능을 억지로 집어넣기보다는 일본어 입력 방법 및 UI 를 새롭게 구상하는 것이 좋을 것 같습니다.
일단, 조합 중인 상태일 때 페이지 다운키를 누르면 후보창이 열리고 마지막 아이템으로 바로 이동되는 기능을 추가하겠습니다.

**Comment by cogniti** [comment]
nimf-rime 중국어 입력을 보면 잘 되어 있습니다.
https://youtu.be/kVAbW8qPMts

일본어도 이런 식으로 직관적으로 입력할 수 있어야 한다고 생각합니다.
후에 시간이 난다면 UI 를 제설계하겠습니다.

**Comment by cogniti** [comment]
anthy 라이브러리 api 를 상세히 테스트 및 확인해봤는데, 원본 text 에 대한 offset 이 없어서 rime 처럼 활용하기는 굉장히 어렵습니다. 예를 들어 AああB 를  A于B 로 변환할 때, 글자 길이가 달라지기 때문에 그렇습니다.
그래서 기존 방법을 편리하게 하는 방법으로 개선하겠습니다.

**Comment by cogniti** [comment]
nimf-anthy 를 재설계했습니다.
실제로 쓸만한 수준이라고 예상하고 있습니다.
그리고 히라가나 변환키 F6 으로 기본 설정해 놓았고
가타카나 변환기 F7 로 기본 설정해 놓았습니다.
그외 말씀하신 로마자 변환 기능은 효용성이 떨어질 것으로 예상되어 넣지 않았습니다.
그리고 제가 시간이 없는 관계로 충분한 테스트를 하지 못한 상태에서 릴리즈 했습니다. 많은 이용 바라며 문제가 있거나 개선이 필요하면 새로 이슈를 열어 주시기 바랍니다.

**Comment by Hong-SeJung** [comment]
감사합니다. 그럼 내일 테스트 해보겠습니다.

**Comment by cogniti** [comment]
ppa 빌드가 아직까지 안 되고 있네요.
https://launchpad.net/~hodong/+archive/ubuntu/nimf/+packages
https://answers.launchpad.net/launchpad/+question/662545
https://twitter.com/launchpadstatus/status/948688233029881856
최근 심각한 보안 취약점을 완화하기 위해 launchpad 빌드 기능을 비활성화했다고 하네요.

deb 패키지 만드는 방법이 https://cogniti.github.io/nimf/ko/support.html 에 있으니 이용에 참고하시기 바랍니다.

**Comment by Hong-SeJung** [comment]
방금 일본어 입력 테스트해보았습니다.
아직 신분이 학생이라 늦은 점 양해 부탁드립니다.
일단 입력시 바로 한자로 나오더라고요.
보통은 히라가나를 더 많이 사용하기 때문에 히라가나가 나오고 스페이스바를 누르면 한자로 변환되는 구조입니다.
이런 식으로 바꿔주시면 감사하겠습니다.

**Comment by cogniti** [comment]
그 부분은 논의가 필요할 것 같습니다.
새로 이슈를 올려주시기 바랍니다.
https://github.com/cogniti/nimf/issues/new

**Comment by cogniti** [comment]
http://phrasebook.naver.com/?targetLanguage=jp 에 예문으로 입력 과정을 보여드리겠습니다.
유튜브 영상 링크입니다. https://youtu.be/9li1LCVoR1I
저는 딱히 불편하다는 느낌을 받지 못하고 있습니다.
아래 romaji (영문)을 연이어 입력하면 anthy 라이브러리가 자동으로 변환해줍니다.
다 입력한 후에 그냥 엔터 누르면 됩니다.
꼭 기존 ibus-anthy, uim-anthy, fcitx-anthy 등의 UI 및 입력 방법을 따라할 필요는 없다고 생각합니다.
오히려 nimf-anthy 의 방식이 직관적이고 편리하다고 생각합니다.
```
チェックイン、お願いします。どなたのお名前で予約なさいましたか。
chextukuinn, onegaishimasu. Donata no onamae de yoyaku nasaimashita ka.
```

**Comment by Hong-SeJung** [comment]
제가 했던 말의 의도는 물론 nimf의 입력 방식 또한 직관적이고 편리하지만, 현재 일본어 입력기로서 ibus, fcitx, uim 사용자들이 nimf 사용자들보다 많으며, ibus 등의 사용자들이 nimf로 넘어오면서 입력에 어려움을 겪을 수 있다는 뜻이었습니다.
아마 전달이 잘 되지 않은 것 같군요. 기분나빠하시지 않으셨으면 좋겠습니다.

**Comment by cogniti** [comment]
논의는 #76 이슈에서 계속됩니다.
