### ISSUE TITLE
업그레이드 후 indicator가 작동하지 않는 문제 (Linux Mint 18.3 Cinnamon)

### ISSUE THREAD

**Issue by gnucian** [cogniti/nimf#74]
hodong 님의 Ubuntu PPA에서 가장 최근 버전인 2017.12.27.1~xenial로 업그레이드한 후 Cinnamon의 패널에 IM의 indicator가 나타나지 않습니다. (바로 이전 버전까지는 멀쩡히 잘 됐습니다.) Indicator가 나타나지 않을 뿐 아니라 nimf가 작동도 되지 않습니다. System Settings의 Input Method는 nimf로 멀쩡히 잘 세팅돼 있습니다.

혹시 몰라 터미널에서
$ nimf-daemon --start-indicator
를 실행해 봐도 아무런 반응이 없군요. 패널 쪽도, 터미널 쪽도. (터미널 쪽은 무슨 에러 메시지라도 나올 줄 알았는데 그냥 아무것도 없습니다.)

이전 버전과 같이 패널의 'Keyboard' 애플릿은 표시되도록 설정돼 있는데도 뭔가 nimf 쪽 문제인지 Keyboard 애플릿(nimf의 indicator가 표시되던 애플릿임)이 표시되지 않습니다. 혹시 몰라 IM을 Fcitx나 IBus로 바꿔봤는데 애플릿 표시가 잘 되더군요. 물론 작동은 썩 만족스럽지 못했습니다만... (제가 nimf를 선호하는 이유입니다.)

잘은 모르지만 무지한 제 추측으로는 issue #70 을 해결하실 때 변경하신 무언가와 관련이 있지 않을까 합니다. IM이 제대로 작동 안 하니 무척 불편하네요.

**Comment by cogniti** [comment]
네 방금 전에 확인했고 해결했습니다.
G_LOCK 를 잘못 사용해서 데드락이 걸려서 그렇습니다.
곧 릴리즈하겠습니다.

**Comment by cogniti** [comment]
2017.12.28 버전 설치 후 어떤지 알려주세요.

**Comment by gnucian** [comment]
변화가 없습니다만...

**Comment by cogniti** [comment]
@nemonein @gnucian 인디케이터가 뜨지 않은 상태에서 한글 입력은 되나요?

**Comment by gnucian** [comment]
되지 않습니다.

**Comment by cogniti** [comment]
@nemonein @gnucian 테스트해 보세요.

artful 64bit
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/14190510

artful 32bit
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/14190511

xenial 64bit
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/14190520

xenial 32bit
https://launchpad.net/~hodong/+archive/ubuntu/testing/+build/14190521

**Comment by cogniti** [comment]
원인은 모르겠고 요즘 im-config 명령이 한 방에 듣지를 않습니다.
im-config -n nimf
im-config -n fcitx
교차하여 명령하면 환경 변수가 제대로 업데이트 되지를 않아 fcitx, ibus 등의 입력기가 동시에 설치되어 있으면 경우에 따라 nimf, fcitx 가 작동하지 않을 수도 있습니다.
터미널 열고
`
export | grep nimf
`
명령으로 nimf 로 환경 설정되어 있는지 확인해야 합니다.

--start-indicator 명령할 때 어떨 때는 되고 어떨 때는 안 되는 현상을 고쳤습니다.

**Comment by nemonein** [comment]
늦은 시간이지만, 결과를 기다리실 듯 하여 결과를 올립니다.

`nimf 12.28.1~artful` 기준:
- Kubuntu : indicator 작동 안함. 언어 전환 작동.
- Ubuntu : indicator, 언어 전환 모두 제대로 작동.

`nimf 12.28.3~artful` 기준:
- Kubuntu : 모두 정상 작동. 메모 위젯(Notes)에서도 한/영 전환 됩니다.
- Ubuntu : 아직 시험해보지 못했습니다.

이상입니다. 잠깐 사용해봤기에, 다른 문제는 찾지 못했습니다.
뭔가 이상한 현상이 보이면 말씀드리도록 하겠습니다.

고생하셨습니다.
고맙습니다.
