### ISSUE TITLE
VS code에서 받침 표시 문제

### ISSUE THREAD

**Issue by partrita** [cogniti/nimf#75]
![screenshot from 2017-12-28 22-43-09](https://user-images.githubusercontent.com/7941072/34412430-8473a076-ec20-11e7-82f0-b38b5130686f.png)

위의 스크린샷에서 보이시는 것 처럼 VS code editor 에서 가의 받침이 똑바로 표시되지 않는 문제가 있습니다.

> 각이 가ㄱ로 보여집니다.

vim에서는 똑바로 표시되고, 실제로는 **각**이라고 정상적으로 보여지는걸 봐서는 VS code에서만의 문제 인것 같습니다.

**Comment by cogniti** [comment]
그거는 폰트 문제이거나 VS 문제입니다. VS 쪽에 문의해주세요.
