### ISSUE TITLE
nimf 일본어 입력기 입력 방법에 관련한 논의

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#76]
현재 anthy에 기반을 하고 있는 nimf 일본어 입력기는 어제(작성 날짜 기준) 히라가나, 가타카나 변환 키 추가를 마쳤습니다.
그 업데이트로 인해 ①일단 히라가나가 입력되고 나서 스페이스바를 누르면 한자 변환창이 뜨고, 가타카나 변환 키를 누르면 가타카나로 변환되는 입력 방식(현재 mozc, anthy 등의 일본어 입력기가 이 방법을 채택하고 있습니다)에서 ②히라가나를 입력하면 일단 한자로 변환되고 히라가나 변환 키를 누르면 히라가나로 변환되고, 가타카나 변환 키를 누르면 가타카나로 변환되는 입력 방식으로 변경되었습니다.
여러분들은 ①과 ② 중에서 무엇을 더 선호하십니까?

**Comment by Hong-SeJung** [comment]
일단 저는 ①을 선호합니다.

**Comment by cogniti** [comment]
http://phrasebook.naver.com/?targetLanguage=jp 의 예문으로 입력 과정을 보여드리겠습니다.
유튜브 영상 링크입니다. https://youtu.be/9li1LCVoR1I
저는 딱히 불편하다는 느낌을 받지 못하고 있습니다.
아래 romaji (영문)을 연이어 입력하면 anthy 라이브러리가 자동으로 변환해줍니다.
다 입력한 후에 그냥 엔터 누르면 됩니다.
꼭 기존 ibus-anthy, uim-anthy, fcitx-anthy 등의 UI 및 입력 방법을 따라할 필요는 없다고 생각합니다.
오히려 nimf-anthy 의 방식이 기존 방법보다 더 직관적이고 편리하다고 생각합니다.
```
チェックイン、お願いします。どなたのお名前で予約なさいましたか。
chextukuinn, onegaishimasu. donata no onamae de yoyaku nasaimashita ka.

**Comment by Hong-SeJung** [comment]
제가 했던 말의 의도는 물론 nimf의 입력 방식 또한 직관적이고 편리하지만, 현재 일본어 입력기로서 ibus, fcitx, uim 사용자들이 nimf 사용자들보다 많으며, ibus 등의 사용자들이 nimf로 넘어오면서 입력에 어려움을 겪을 수 있다는 뜻이었습니다.
아마 전달이 잘 되지 않은 것 같군요. 기분나빠하시지 않으셨으면 좋겠습니다.

**Comment by cogniti** [comment]
변환기를 누를 필요없이 그냥 아래의
`chextukuinn, onegaishimasu. donata no onamae de yoyaku nasaimashita ka.` 만 입력하면
`チェックイン、お願いします。どなたのお名前で予約なさいましたか。` 이게 출력됩니다.
nimf-anthy 는 변환되는 과정을 보여주고 있습니다.
기존 방법은 일단 입력을 다한 후에 스페이스를 누르고 좌우 방향키를 눌러서 사람이 문장을 처음부터 다시 확인하는 과정을 거치게 되는데 nimf-anthy 는 변환되는 과정을 보여줌으로여 다시 처음으로 가서 확인할 필요가 없어졌습니다. 물론 좌우 방향키로 좌측, 우측으로 이동하여 후보를 선택할 수 있는 기능이 있습니다.
https://youtu.be/9li1LCVoR1I 유튜브 영상에서 확인하실 수 있습니다.
그리고, anthy 라이브러리가 학습을 하기 때문에 계속 사용하다보면 적중률이 상승합니다.
a 를 눌렀는데 あ 이게 안나오고 한자가 나온다고 해서 당황해하실 필요 없습니다.
a 를 눌렀을 때 스페이스 키로 あ 를 선택하면 첫번째 후보로 あ가 나오게 됩니다.

**Comment by cogniti** [comment]
> ②히라가나를 입력하면 일단 한자로 변환되고 히라가나 변환 키를 누르면 히라가나로 변환되고, 가타카나 변환 키를 누르면 가타카나로 변환되는 입력 방식으로 변경되었습니다.

이렇게 말씀하셨는데, 오해하고 계신 거에요. nimf-anthy 는 그런 방식이 아닙니다.
konnnichiwa 를 입력하면 최종적으로 `こんにちわ` 가 출력됩니다. 히라가나 키, 가타카나 키를 누를 필요없이요.

**Comment by Hong-SeJung** [comment]
그렇군요. 제가 착각하고있었나봅니다. 그럼 이 이슈는 닫도록 하겠습니다.
