### ISSUE TITLE
데비안에서 컴파일 시 QtGui

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#77]
데비안에서 컴파일 시 QtGui를 찾을 수 없다고 나옵니다.
그래서 여러군데에서 찾아보았으나, 찾을 수 없었습니다.
어떤 것을 설치해야할까요?

**Comment by cogniti** [comment]
에러 메시지를 카피해서 올려주세요

**Comment by Hong-SeJung** [comment]
checking for /usr/share/anthy/anthy.dic... no
checking for NIMF_QT4_DEPS... no
configure: error: Package requirements (QtGui) were not met:

No package 'QtGui' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NIMF_QT4_DEPS_CFLAGS
and NIMF_QT4_DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by cogniti** [comment]
`libqt4-dev` 설치하세요

**Comment by Hong-SeJung** [comment]
checking for NIMF_QT5_DEPS... no
configure: error: Package requirements (Qt5Core Qt5Gui Qt5Widgets) were not met:

No package 'Qt5Core' found
No package 'Qt5Gui' found
No package 'Qt5Widgets' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NIMF_QT5_DEPS_CFLAGS
and NIMF_QT5_DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

같은 방법으로 libqt5-dev 를 설치하려 했으나 패키지가 없다고 하네요
그래서 apt install *qt5* 를 했으나 오류는 고쳐지지 않았습니다.
혹시나 해서 리부팅도 해보았으나, 소용이 없더군요...

**Comment by cogniti** [comment]
`qtbase5-dev` 설치하세요
