### ISSUE TITLE
debian에서 source compile 후 에러

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#78]
debian에서 소스 컴파일까지 되었으나, nimf-daemon을 실행시
nimf-daemon: error while loading shared libraries: libnimf.so.0: cannot open shared object file: No such file or directory
라는 오류가 뜹니다.

**Comment by cogniti** [comment]
루트 권한으로 ldconfig 하셨나요?

**Comment by Hong-SeJung** [comment]
아뇨, 방금 했습니다. 다시 리부팅 해보겠습니다

**Comment by cogniti** [comment]
리부팅 안 하셔도 되요
