### ISSUE TITLE
nimf가 debian에서 소스 컴파일 후 im-config에 뜨지 않습니다

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#79]
nimf가 debian에서 소스 컴파일 후 im-config에 뜨지 않습니다

**Comment by cogniti** [comment]
im-config data 가 설치 안 되어서 그래요.
컴파일 하실 때,
`./autogen.sh --with-im-config-data` 옵션을 주고 컴파일하시면 `make install` 할 때
`nimf/data/im-config/23_nimf.*` 파일이 `/usr/share/im-config/data` 디렉토리에 복사됩니다.
`--with-im-config-data` 옵션없이 컴파일 하셨다면,
`cp`명령으로 `nimf/data/im-config/23_nimf.*` 파일을 `/usr/share/im-config/data` 디렉토리에 복사하시면 되겠습니다.

**Comment by Hong-SeJung** [comment]
말씀처럼 하니 되네요. 항상 친절한 답변 감사드립니다.
