### ISSUE TITLE
단축키를 통한 엔진 변경 및 표시기 관련 이슈

### ISSUE THREAD

**Issue by sukso96100** [cogniti/nimf#8]
1. 엔진 전환 단축키로 엔진 전환이 잘 안되는 것 같습니다.
 -  단축키로 하려면 표시기에서 한번 다른 엔진 선택해줘야만 되네요.
 - 저는 영어, 한국어, 중국어 엔진 켜놓고 쓰는데, 이게 표시기에서 한국어를 선택 하면 영-한 전환만 되고, 이후에 중국어도 한번 표시기에서 선택하면 그제서야 영-한-중 전환이 됩니다.
2. `nimf-settings`활성화된 엔진만 표시기에 나와야 하는것이 아닌가 싶은데. 생각과 다르게 엔진을 꺼도 여전히 표시기 메뉴에 나타나는 것 같습니다.
 - 예를 들어 한국어만 켠 경우, 한국어/시스템 키보드만 표시기 메뉴에 나타나야 하는데 중국어가 여전에 메뉴에 나타나 있습니다. `nimf-indicator`를 종료후 다시 시작해도 마찬기지 인 것 같습니다.

환경은 아치리눅스 64bit 에 GNOME 3.20 에 `nimf-git` 패키지 사용 중입니다.
`nimf-git`패키지는 AUR 에 있습니다.

**Comment by cogniti** [comment]
1번은 키 이름이 변경되어 그렇습니다.
아래 참고하시고요.. 키설정을 다시 해주세요.

http://cogniti-works.blogspot.kr/2016/05/nimf_30.html?m=1

그리고 엔진 단에서 한/영 또는 중/영 단환되는 것은 정상이나 불편한 점이 있습니다.
보다 나은 방법을 고려할 필요가 있습니다.
예를 들자면 엔진 윗단에서 중/한 전환.

2번은 인지하고 있습니다. 고칠 예정입니다.
2016. 6. 1. 오후 2:25에 "Youngbin Han" <notifications@github.com>님이 작성:

**Comment by sukso96100** [comment]
1번이 저의 경우 키 이름 변경 전부터 단축키 전환이 먹히지 않았어요. 단축키를 눌러서 영/한 전환 하는것도 안되는 것 같아요.

**Comment by cogniti** [comment]
모든 키가 다 되는 것은 아니고
<Control> space, <Shift> space, Hangul, F1~F12 으로는 작동되어야 합니다.
그 키가 작동되지 않는다면 GNOME 컨트롤 센터에 들어가셔서 키보드, 지역, 언어 설정 등에 단축키가 이미 등록되어 있는지 확인하세요.
그리고 ibus 또는 fcitx 설치되어 있다면 그쪽에 등록된 키도 확인해보셔야 합니다.
그외 alt키, super키 등과 조합할 경우 전환이 되지 않는 nimf 버그가 있습니다. 조만간 고칠 예정입니다.
2016. 6. 1. 오후 2:49에 "Youngbin Han" <notifications@github.com>님이 작성:

**Comment by cogniti** [comment]
GNOME 설정(gnome-control-center) 들어가셔서 nimf 에 사용할 단축키가 등록되어 있다면 해제시켜주세요.
gnome-control-center 에 설정된 단축키는 nimf 로 전달되지 않습니다.

GNOME 말고 다른 환경(예를 들자면 KDE, Unity 등)을 사용 중이시면 그것도 마찬가지로 단축키가 뭘로 등록되어 있는지 확인해보셔야 됩니다.
nimf-settings 에서 GNOME 또는 KDE 등에 등록된 단축키를 검색해주면 좋겠지만, GNOME, KDE, Unity 등 지원해야 하는 환경이 많은데다가 그 환경들이 버전이 올라갈 때마다 코드를 확인해야 하는 부담감 때문에 nimf-settings 에서  GNOME, KDE, Unity 등의 환경에 등록되어 있는 단축키를 검색하는 기능을 추가하지는 못합니다. 죄송합니다.

![screenshot from 2016-06-01 18 51 18](https://cloud.githubusercontent.com/assets/17453239/15705379/0586710a-282a-11e6-83d4-32b9e639c664.png)

**Comment by cogniti** [comment]
ibus, fcitx, nimf 의 엔진 전환 방식을 한국어를 예를 들어 설명드리겠습니다.
서버에서 키를 받아서 엔진 전환키인지 체크하여 해당하는 언어 엔진을 선택 후, (엔진 전환키를 제외한) 키값들을 언어 엔진으로 보냅니다.
그 다음 언어 엔진에서 한글키인지, 한자키인지 체크하는 방식입니다.
이러한 방식이 불편하므로,
엔진 전환하는 방법을 다음처럼 바꿀 예정입니다.
(hotkey, trigger, shortcut 키는 유사한 의미입니다.)

중국어 trigger 키 -- key1, ke2
한국어 trigger 키 -- key3, key4

를 설정하도록 변경할 것입니다.
trigger 키는 toggle 키로 작동합니다.
중국어 trigger키를 한번 누르면 현재 엔진이 중국어가 아닐 경우, 중국어 선택, 또 한번 누르면 시스템 키보드(영어) 선택,
한국어 trigger키를 한번 누르면 현재 엔진이 한국어가 아닐 경우, 한국어 선택, 또 한번 누르면 시스템 키보드(영어) 선택.
이러한 방식으로 작동되도록 수정하겠습니다.
작년 nimf 설계 때 생각했었던 것인데 기존의 방법과 달라서 혼동 또는 불편이 초래될까봐서 도입하지 못했었는데 때마침 이슈가 들어와서 이러한 방식을 도입하겠습니다.

**Comment by cogniti** [comment]
모두 고친 것 같습니다. 확인해보세요.

**Comment by sukso96100** [comment]
감사합니다 :) 엔진 전환 핫키 지우고, 한국어 엔진에 `<Mod4><Super>k` 중국어 엔진에 `<Mod><Super>c` 설정해서 사용 중인데 잘 작동하네요.

**Comment by sukso96100** [comment]
지금 엔진 전환 핫키만 `Hangul` 로 하고, 나머지 한국어/시스템 핫키랑 중국어/시스템 핫키 지우고 전환 잘되나 보고 있는데. 이제 표시기에서 선택 안해줘도 엔진 전환이 잘 작동하네요. 감사합니다 :)

**Comment by sukso96100** [comment]
그냥 궁금해서 여쭤보는 거긴 한데, 2번 문제는 아직 안된거죠?

**Comment by cogniti** [comment]
해결되었습니다.

**Comment by cogniti** [comment]
제가 잘못 이해한 것 같습니다.
제가 고친 것은 아래 그림 보시면 오른쪽에 `Defalut language engine` 콤보 박스가 보이실텐데..
그걸 고친 겁니다. 엔진을 on / off 하면 `Defalut language engine` 콤보 박스 아이템이 변경됩니다.
![screenshot from 2016-06-07 02 14 49](https://cloud.githubusercontent.com/assets/17453239/15830895/9d6be728-2c55-11e6-852d-aaa9cfc1beee.png)

nimf-settings 에서 왼쪽 메뉴에는 설치된 엔진 모듈이 나옵니다. 엔진을 비활성화(off) 했을 때에도 표시됩니다.
왜냐하면 비활성화(off) 했을 때 왼쪽 메뉴에서 없애면 활성화(on)를 할 수 없습니다.
![screenshot from 2016-06-07 02 17 39](https://cloud.githubusercontent.com/assets/17453239/15830974/180560ea-2c56-11e6-89d8-641ab5ff70c3.png)
이러한 동작은 다른 프로그램들(geany, gedit, firefox 등)도 마찬가지입니다.
사용하지 않는 엔진을 왼쪽 메뉴에서 표시되지 않게 하는 것이 목적이라면 그 엔진 모듈을 삭제하시면 됩니다.
사용하시는 환경에 따라서 위치가 다르니 다음을 참고하셔서 .so 파일과 그에 해당하는 설정 파일 .xml 을 삭제하시면 되겠습니다.
```
/usr/lib/nimf/modules/libnimf-libhangul.so
/usr/share/glib-2.0/schemas/org.nimf.engines.nimf-libhangul.gschema.xml

/usr/lib/nimf/modules/libnimf-sunpinyin.so
/usr/share/glib-2.0/schemas/org.nimf.engines.nimf-sunpinyin.gschema.xml

/usr/lib/nimf/modules/libnimf-anthy.so
/usr/share/glib-2.0/schemas/org.nimf.engines.nimf-anthy.gschema.xml
```

**Comment by sukso96100** [comment]
방금 확인해 보았는데,  2번 문제도 잘 해결된 것 같네요. 수고 많으셨습니다 :)

![2016-06-07 08-02-18](https://cloud.githubusercontent.com/assets/1916739/15840695/87b1f932-2c86-11e6-8bd0-bd6e10aae7e2.png)
