### ISSUE TITLE
nimf가 소스 컴파일 후 작동하지 않습니다

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#80]
indicator에도 뜨고, autostart에 추가도 하고 im-config로 설정도 했으나, 작동하지 않습니다

**Comment by cogniti** [comment]
루트 권한으로 `make update-gtk-im-cache` 하셨나요?
안 하셨으면,
nimf 디렉토리도 들어가셔서
`make update-gtk-im-cache` 해주세요.

**Comment by Hong-SeJung** [comment]
오옷! 되는군요! 다시 한번 감사드립니다
