### ISSUE TITLE
nimf 일본어 입력(ん, っ) 건의사항

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#81]
일본어 입력시 ん이 들어가는 것들을 칠 때(예시 : 韓国, kann ko ku) n을 두 번 입력해야 입력됩니다.
따라서 제 건의 사항은 n 다음에 자음이 뒤에 오거나, n이 가장 마지막에 오는 경우 ん으로 인식되게 해주셨으면 합니다.
또한, っ가 들어가는 것들을 칠 때(예시 : 日本, nixtu ponn) xtu를 입력해야 합니다.
여기에서의 건의사항은, 여러 일본어 입력기에서 지원하는 기능이기도 하고, 무엇보다 매우 편리한 기능입니다. っ 뒤에 모음이 나오는건 어쩔 수 없지만, 뒤에 자음이 나올 경우에는 그 자음 앞글자를 입력하면 되는 기능입니다. 그러니까 日本을 칠 때 아까처럼 치지 않고, nippon을 치면 되는 것이죠.

**Comment by cogniti** [comment]
ん 는 받침 같아서 말씀하신데로 하면 될 것 같아요.
그런데 っ의 경우 말씀하신 설명으로는 어떤 규칙성이 있는지 이해가 안 됩니다.

**Comment by Hong-SeJung** [comment]
일본어로 ぽ를 입력할 때 po라고 입력합니다. 그리고 っぽ를 입력할 때 xtupo를 입력합니다.
제가 건의한 사항은 か(ka), さ(sa),た(ta) 등 모음 앞에 자음이 붙는 글자들을 입력할 때 그 자음을 한번 더 누르면 그 앞에 っ가 입력되는 것입니다.

예시)
っか : kka
っさ : ssa
った : tta

그리고 이 경우가 아닌 것들(あ(a), い(i), う(u)) 등의 것들은 전 방식대로 xtu를 입력하는 쪽으로 해주셨으면 합니다.

예시)
っあ : xtua
っい : xtui
っう : xtuu

**Comment by cogniti** [comment]
그러니까... ppo 입력했을 때, っぽ 이렇게 출력되어야 한다는 말씀이시죠?
다른 입력기들은 어떠한가요? 일반적인 방법의 입력법인가요?

**Comment by cogniti** [comment]
아... 제가 일본어를 몰라서 질문드리는 겁니다.

**Comment by Hong-SeJung** [comment]
네, 가장 일반적인 방법입니다. 다른 입력기들도 같은 방법을 사용합니다.

**Comment by cogniti** [comment]
nimf-anthy 에 대한 많은 관심에 감사드립니다.
의견을 수용하겠습니다.

**Comment by cogniti** [comment]
말씀하신대로 구현을 해봤는데 n 의 경우 문제가 발생합니다.
kon ni chi wa
konn i chi wa
이렇게 두가지로 해석되기 때문에...
nn 입력했을 때 ん이 출력되는 규칙을 삭제해야 합니다.

**Comment by cogniti** [comment]
っ는 적용했습니다. ん의 경우는 규칙에 모호성이 있어서 일단 보류합니다.
입력기에서 일반적으로 nn을 입력하면 ん을 출력합니다. 이 규칙은 모호성이 없이 정확하기 때문에,
nn 입력했을 때, ん 출력 규칙을 삭제하지 않겠습니다. 이 규칙을 삭제하면 ん을 명확하게 입력하는 방법이 없어지기 때문입니다.
こんにちわ 입력할 때 어떻게 입력해야 할까요?
현재 방법은 konn ni chi wa 를 입력하면 됩니다.
그렇다면 n + 자음일 때, ん자음을 출력하는 방법을 사용하면,
kon ni chi wa
konn i chi wa
어떻게 모호성을 제거해야할 까요?
제가 이런거 연구할 시간이 없습니다.
일본어 사용자분들은 이런 경우 어떻게 해야 하는지 더욱 정확한 규칙을 연구하셔서
명확하고 정확한 규칙을 알려주시기 바랍니다.
이슈는 여기서 닫겠습니다.

**Comment by cogniti** [comment]
다른 입력기들은
konnichiwa
konnnichiwa
두 경우에 대하여 어떻게 출력해주나요?

**Comment by Hong-SeJung** [comment]
1번 : こんいちわ(ko nn i chi wa)
2번 : こんにちわ(ko nn ni chi wa)
으로 되네요.
