### ISSUE TITLE
nimf 일본어 히라가나 변환시 장음부호가 하이폰으로 변경됩니다.

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#82]
nimf로 일본어 입력을 할 때 하이폰이 입력되면 자동으로 장음부호로 변환되는 기능이 있더군요. 이게 그냥 입력하거나 가타카나를 입력할 때는 상관 없지만, 히라가나 변환시 장음부호가 하이폰으로 바뀌는 현상이 있습니다.

예시)
no-to(노트)
のー戸 (그냥 입력시)
の-と (히라가나로 변환시)
ノート (가타카나로 변환시)

**Comment by cogniti** [comment]
우선, 제가 일본어를 모르는 점 양해 부탁드립니다.
히라가나로 `の-と`가 아니라 `のーと` 이렇게 출력되어야 하는 건가요?

**Comment by Hong-SeJung** [comment]
네

**Comment by cogniti** [comment]
혹시 쉼표, 마침표, 작은 따옴표, 큰 따옴표 등도 다르게 나와야 되나요? 한번 해보고 알려주세요

**Comment by Hong-SeJung** [comment]
작은 따옴표는 「」, 큰따옴표는 『』, 쉼표는 、, 마침표는 。네요.
다른건 같은 것 같습니다.
