### ISSUE TITLE
한국어 한자 입력 시 조판 위치 in GNOME

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#83]
GNOME에서 한국어 한자 입력 시 조판 위치가 글자 아래에 나타나지 않고 다른 곳에 나타납니다.
제가 지금 듀얼모니터를 사용하고 있는데, Desktop 2에서 조판을 띄우면 Desktop 1에서 조판이 나타나지만, Desktop 1에서 조판을 띄우면 정상적으로 문자 아래에 나타납니다. 참고로 일본어 입력시에는 조판이 문자 아래에 정상적으로 나타납니다.

**Comment by cogniti** [comment]
모든 언어 엔진이 하나의 candidate window 를 공유하여 사용하고 있습니다. 모니터가 없어서 듀얼 모니터
 상황을 고려하지 않았습니다.
이것은 nimf 버그인 것 같은데 그 버그를 고치기 위해서는 100만원 정도 비용이 소비되므로 고치지 않겠습니다. 양해 바랍니다.
