### ISSUE TITLE
nimf-anthy 가나 자판 지원 계획

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#84]
혹시 nimf-anthy 가나 자판 지원 계획이 있으신지요
![800px-kb_japanese-on-104 svg](https://user-images.githubusercontent.com/25530915/34964378-2f860cce-fa45-11e7-84b8-75e773aa4463.png)
   출처 : [http://vintagemonday.tistory.com/44](http://vintagemonday.tistory.com/44)

**Comment by cogniti** [comment]
말씀하신 자판을 지원할 계획이 없습니다.

**Comment by Hong-SeJung** [comment]
그렇군요...

**Comment by cogniti** [comment]
맵핑만 하면 되므로 구현하는 것은 쉽지만, 회사를 며칠 쉬고 개발해야 하거나,
퇴근 후 쉬지도 못하고 개발해야 하므로, 금전 손실이 약 50만원 정도 발생할 것으로 보이고, 건강에 당연히 문제가 생기고 병원비 지출이 생깁니다. 자질구레한 옵션 추가, 버그 패치 등의 유지보수는 계속하겠지만, 일본어 신규 자판 추가라던가, 베트남 언어 지원이라던가, 한국어 신규 엔진 개발 등 이러한 것들은 앞으로 하지 않으니 양해 부탁드립니다. 만약 하게 된다면 유상으로 제공합니다.

**Comment by cogniti** [comment]
일본어 키보드 OADG 109A 를 부분적으로 지원하겠습니다.
제가 일본어를 모르는데에다 일본어 키보드가 없어서 완전한 지원은 어렵습니다.
완전한 지원을 원하시는 분은 작동 방법에 대해 상세히 설명해 주시기 바랍니다.
https://ko.wikipedia.org/wiki/%EC%96%B8%EC%96%B4_%EC%9E%85%EB%A0%A5_%ED%82%A4#/media/File:KB_Japanese.svg

**Comment by cogniti** [comment]
일본어 키보드를 사용하기 위해서는
![2018-01-19 07-15-24](https://user-images.githubusercontent.com/17453239/35124225-af612c58-fce8-11e7-889b-4bef5ab18703.png)
일본어 입력 모드 옵션에서 `일본어 키보드 OADG 109A`를 선택하시면 되고,
기존 romaji 방법으로 사용하기 위해서는 `로마지`를 선택하시면 되겠습니다.
`일본어 키보드 OADG 109A`를 부분적으로 지원하는 것이며, 완전한 지원을 위해서는 저에게 `일본어 키보드 OADG 109A`가 있어야 하며, 각 키들(英数, 전각, 반각, 구두점, 한자가 쓰여진 키 등)이 무엇을 의미하는지를 알아야 하는데 제가 알 길이 없으므로 부분적으로 나마 지원합니다.
완전한 지원을 원하시면 저에게 일본어 키보드를 구해 주시고, 구현되지 않은 키 기능에 대해 상세히 설명해 주시면 완전한 지원을 고려해보겠습니다. 제가 할 수 있는 부분은 여기까지입니다.

**Comment by Hong-SeJung** [comment]
OADG-109A 모델은 일본에서만 쓰이는 모델입니다. 그렇기 때문에 일본어 자판에만 있는 키가 몇 개가 있습니다. 따라서 미국과 같은 나라들이 보통 우리가 말하는 qwerty 자판에 맞게 매핑한 모델이 있습니다.
![a9bd4a1b7b75d89b22f184e3cfd3a109](https://user-images.githubusercontent.com/25530915/35130528-a9420ee8-fd04-11e7-9d37-35d84c9466e2.jpg)
http://www.ranoma.com/hard/57266
참고해주시기 바랍니다.

**Comment by Hong-SeJung** [comment]
좌측 상단에 보시면 큰따옴표를 거꾸로 쓴 듯한 것이 있는데 그건 탁음이라고 합니다. 그걸 치면 글자 위에 그 표시가 나타나게 됩니다.
k => g
s => z
t => d
h => b
예시)
か(ka) => が(ga)
さ(sa) => ざ(za)
た(ta) => だ(da)
は(ha) => ば(ba)

그리고 그 옆에 있는 동그라미 표시는 반탁음이라고 합니다. 이것을 치면 마찬가지로 위에 반탁음 표시가 나타나게 됩니다.
h => p
예시)
は(ha) => ぱ(pa)

**Comment by Hong-SeJung** [comment]
참고로 좌측 상단에 ほ 위에 ー를 한일(一)로 착각하시는 분들이 생각보다 많으신데, 그 기호는 장음부호입니다.

**Comment by cogniti** [comment]
처음에 이슈 작성하실 때 상세하게 작성해 주시지...
제가 시간이 없어서 이슈 하나 처리하려면 회사를 하루씩 쉬어야 가능합니다. 자금까지 그렇게 유지보수 해왔습니다. 그렇지 않으면 이슈 처리가 불가하고 이슈 게시판 운영의 의미가 없습니다.
다음부터는 작성하실 때 한번에 상세히 작성해주시가 바랍니다.

**Comment by cogniti** [comment]
109A 의 실물이 있어야 완성할 수 있는데 실물을 구하기 어렵기 때문에 장기간 미완성 상태(버그 상태)로 남겨주고 싶지 않습니다. 따라서 OADG-109A 는 삭제하고 일반적인 키보드 방식을 추가하겠습니다.

**Comment by cogniti** [comment]
그리고 그 키보드 배열(keyboard layout)의 정확한 이름을 아시나요?

**Comment by cogniti** [comment]
MS윈도7에서 이름을 확인해봤는데 마땅히 이름이 없습니다. 109A 를 삭제하고 일반적인 us 키보드 레이아웃을 등록하려 했었지만, MS윈도가 OADG 109A 를 일반 us usb키보드에 맵핑한 결과인지, 일반 us usb키보드용 일본어 배열이 따로 있는지 모르겠습니다.

**Comment by Hong-SeJung** [comment]
키맵 이름은
MS-IME
입니다.
fcitx-mozc에서 확인 했습니다.

**Comment by cogniti** [comment]
일본어 키보드 하나 샀습니다.
이 키보드가 109A 인지 아닌지 그것까지는 모르겠고, 이 키보드를 지원할 예정입니다.
![1516348770402](https://user-images.githubusercontent.com/17453239/35140352-42a2dbd2-fd3a-11e7-8a78-2815c483a8ba.jpg)

**Comment by Hong-SeJung** [comment]
전에 업로드하신 키맵 사진과 비교하면 OADG-109A가 맞는 듯 합니다.
그리고 ms-ime 지원은 없는거군요.

**Comment by cogniti** [comment]
그건 아직 모르겠습니다.
예를 들자면 한국어 입력을 지원한다면 한글 키보드를 지원하는 것처럼 일본어 키보드를 지원하려면 us 키보드보다는 109A 또는 점유율 높은 키보드를 우선 지원하고 싶습니다.

**Comment by Hong-SeJung** [comment]
알겠습니다.
그럼 약간 키맵에 어긋나긴 하지만, 만약 esc키가 따로 없다면, 일반 qwerty 키보드 사용자를 위해서 esc에 ろ(ro)를 추가해주십시오. 일반 qwerty 키보드에서는 ro를 입력하지 못합니다.
그리고 f6, f7 등의 변환 기능은 남겨주십시오.

**Comment by cogniti** [comment]
Caps Lock 영수英数키가 뭔지 아세요?

**Comment by Hong-SeJung** [comment]
영어 일본어 변환 키 입니다

**Comment by cogniti** [comment]
MS 가나 입력 모드에서는 변화가 없습니다.
로마지 입력 모드에서요?

**Comment by Hong-SeJung** [comment]
아뇨

**Comment by cogniti** [comment]
그러면요? 설명을 해줘야 알죠

**Comment by cogniti** [comment]
MS윈도7에서 테스트 중인데 영수키는 로마지 입력 모드 및 가나 입력 모드에서 반응이 없습니다.

**Comment by cogniti** [comment]
제가 손실을 무릅쓰고 한번에 개발하려고 하니 한꺼번에 알려주세요. 찔끔찔끔씩 며칠 간격으로 알려주시면 업무에 집중 못하고 시간 및 금전 손실이 더 크고 스트레스 많이 받습니다.

**Comment by Hong-SeJung** [comment]
제가 찾아본 바로는 영수키가 가나 입력 모드 및 로마자 모드에서 일단 글자를 입력한 후 누르는 것으로 되어 있습니다.
예를 들어, a를 누르면 ち가 나옵니다. 그리고 영수 키를 누르면 a가 되는 방식이라고 나와있네요.

--참고--
[http://vintagemonday.tistory.com/44](http://vintagemonday.tistory.com/44)
[http://www.kbdmania.net/xe/best_article/8393651](http://www.kbdmania.net/xe/best_article/8393651)

--추가--
[https://ko.wikipedia.org/wiki/%EC%96%B8%EC%96%B4_%EC%9E%85%EB%A0%A5_%ED%82%A4#%EB%AC%B4%EB%B3%80%ED%99%98_%ED%82%A4](https://ko.wikipedia.org/wiki/%EC%96%B8%EC%96%B4_%EC%9E%85%EB%A0%A5_%ED%82%A4#%EB%AC%B4%EB%B3%80%ED%99%98_%ED%82%A4)

**Comment by cogniti** [comment]
키의 모든 기능을 확인 완료했습니다.
영수(英数)키는 영문 모드로 전환하는 키입니다.

http://m.blog.daum.net/skcej67/16677640

http://iotown.com/board_view.php?data=aWR4PTE0NTcmcGFnZWNudD0mbGV0dGVyX25vPSZvZmZzZXQ9JnNlYXJjaD0mc2VhcmNoc3RyaW5nPSZwcmVzZW50X251bT0=||&boardIndex=3377

작업량이 많아서 하루 이틀로는 부족하고 천천히 개발하겠습니다.

ろ(ro) 문자는 us 키보드에서는 키 코드 49
일본어 키보드에서는 키 코드  97 이 나옵니다
각각 다른 레이아웃이며 두 레이아웃을 지원하겠습니다.

**Comment by cogniti** [comment]
메뉴에서 `영문 키보드로 가나 입력 (pc104)` 선택하여 사용하시면 되겠습니다.

![screenshot from 2018-01-21 18-21-59](https://user-images.githubusercontent.com/17453239/35192546-027a4280-fed8-11e7-9ca7-1727aa679175.png)

**Comment by cogniti** [comment]
업데이트하면서 버그 생겼네요.
끝글자 체크를 잘못했네요. 이렇게 해야 하는 것 같은데..

```
if (g_str_has_suffix (anthy->preedit1->str, "か"))
  g_string_overwrite (anthy->preedit1, anthy->preedit1->len - strlen ("か"), "が");
```

**Comment by cogniti** [comment]
https://github.com/cogniti/nimf/commit/266073061bc7145ec2e38a531f720c469d01a6f1

**Comment by cogniti** [comment]
OADG 109A 일본어 키보드를 완전하게 지원하려 했었지만 시간이 없는 관계로 삭제하였습니다. 죄송합니다.
Removed Japanese Keyboard (OADG 109A) https://github.com/cogniti/nimf/commit/e969d63b7bc04ee182aed7f47f8f17107999dce2
