### ISSUE TITLE
일본어 ん 입력에 대한 기준

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#85]
1. 모음 앞에서는 n을 2번 누른다.
예시)
いんい, i nn i
2. 자음 앞에서는 n을 1번 누른다. 단, 그 자음이 n일 경우에는 n을 2번 누른다.
예시)
かんこく, ka n ko ku
こんにちわ, ko nn ni chi wa

**Comment by cogniti** [comment]
그 방법은 일관성이 없어서 수용하지 않겠습니다.

**Comment by cogniti** [comment]
ん 입력 방법 변경 예정입니다.
추가적인 의견은
https://github.com/cogniti/nimf/issues/86
에 말씀해주세요.

**Comment by cogniti** [comment]
말씀하신 방법이 맞네요!
제가 잘못 알았습니다.
ini 의 경우,
in i 인지, 아니면 i ni 인지 알 수 없기 때문에 inn i 이렇게 입력하는 거군요.
