### ISSUE TITLE
ん 입력 방법 변경 예정

### ISSUE THREAD

**Issue by cogniti** [cogniti/nimf#86]
안녕하세요.
우선 제가 일본어를 모르는 점 양해 바랍니다.
현재는 `ん`을 입력할 때  `nn`을 누릅니다.
그런데, 이 방법이 불편한가 봅니다.

https://github.com/cogniti/nimf/issues/85
https://github.com/cogniti/nimf/issues/81

그래서 `ん` 입력 방법 변경을 고려하고 있습니다.
변경하고자 하는 방법은 다음과 같습니다.

우선 현재 규칙인 `nn` 입력했을 때 `ん`를 출력하는 규칙을 제거합니다.

`n`을 입력하면 일단 `ん`를 출력합니다.
다음에 모음(a e i o u)이 오면 `ん`를 삭제하고
na ne ni no nu 에 해당하는 글자를 출력합니다.
도깨비불 현상을 허용하는 방법입니다.

かんこく kan ko ku
こんにちわ kon ni chi wa
かん kan
ん n
んん nn

**Comment by cogniti** [comment]
@sudo0272  ん 입력 방법 변경 예정입니다.

**Comment by cogniti** [comment]
`kka`를 입력하면 `っか`출력됩니다.
`nna`를 입력하면 `っな` 이렇게 출력해야 하나요?

**Comment by Hong-SeJung** [comment]
아니요, 그 경우에는 んあ(nn a)를 출력합니다.

**Comment by Hong-SeJung** [comment]
이건 어떤가요?
n 입력이 들어오면 일단 먼저 n을 출력하고 그 다음에 자음이 올 경우에는 ん, 모음이 올 경우에는 な、に、ぬ、ね、の를 출력합니다.
그렇게 되면 뒤에 무슨 입력이 오든지 신경 쓰지 않아도 될 듯 합니다

**Comment by cogniti** [comment]
그렇게 하면 맨 마지막에 n 입력할 경우(예: kan) `かn` 이 되어 버립니다. n 값이 결정되지 않기 때문입니다.
기존 입력기들은 스페이스를 누르는 순간 마지막 n 이 ん으로 변할거에요. 그점에서 nimf 와 다릅니다.

**Comment by Hong-SeJung** [comment]
그건 생각치 못했군요.

**Comment by cogniti** [comment]
ini 입력 방법 때문에 nn 규칙을 삭제하지 않겠습니다.
따라서 kon nni chi wa 이렇게 입력해야 될 겁니다.
일단, 릴리즈하겠습니다.

**Comment by cogniti** [comment]
제가 착각했습니다.
다음 처럼 입력하는 것으로 변경됩니다.
かんこく kan ko ku
こんにちわ konn ni chi wa
かん kan
ん n
ん nn
いんい inn i
