### ISSUE TITLE
nimf can't working in kde neon(wayland) - kde 네온 wayland 에서 한글입력이 안되는 현상

### ISSUE THREAD

**Issue by illust00** [cogniti/nimf#87]
ubuntu ppa 에서 제공해 주시는 패키지라고 생각하는데요.

kde neon 에서 wayland 로 서버를 실행하면, nimf daemon은 실행이 되는데, 실제 한글 입력이 되지 않습니다.
chrome 이나 firefox 같은 GTK(?) 프로그램은 한글 입력이 되더라구요.
KDE 어플은 실행이 되지 않습니다. 제가 /etc/environment 파일에 export 로 시작하는 환경변수를 넣으니
정상 작동합니다.

/etc/environment 파일에 부가적으로 환경변수를 넣어서 패키지를 만들어 주셨으면 감사하겠습니다.

I would appreciate it if you could add environment variables to the /etc/environment file to create the package.

``
$ apt list nimf
``
nimf/now 2017.12.28.1~xenial amd64 [installed,local]
``
$ cat /etc/environment 
``
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
export GTK_IM_MODULE=nimf
export QT4_IM_MODULE="nimf"
export QT_IM_MODULE=nimf
export XMODIFIERS="@im=nimf"
``
$ cat /etc/xdg/autostart/nimf-daemon.desktop 
``
[Desktop Entry]
Name=Nimf
GenericName=Input Method
Comment=Start Input Method
Exec=nimf-daemon --start-indicator
Icon=nimf-logo
Terminal=false
Type=Application
Categories=System;Utility;
StartupNotify=false
X-GNOME-AutoRestart=false
X-GNOME-Autostart-Notify=false
X-KDE-autostart-after=panel
X-KDE-StartupNotify=false

**Comment by cogniti** [comment]
일단 nimf 버그는 아니고요.

`im-config -n nimf` 명령한 후에 로그아웃/로그인 후에도 작동이 안 되는지요?

**Comment by cogniti** [comment]
`/etc/environment` 는 시스템 전체 사용자에게 영향이 가는 설정 파일입니다. nimf 를 설치할 때 그 파일을 변경하도록 하는 것은 부적절하다고 생각합니다.

`im-config -n nimf` 명령을 하여도 환경 변수가 제대로 설정되지 않는다면, 
https://www.freedesktop.org/software/systemd/man/environment.d.html 을 참고하셔서 설정해 보시기 바랍니다.

**Comment by illust00** [comment]
im-config -n nimf 를 실행하여도 안됩니다. 

도움 주셔서 감사합니다.
