### ISSUE TITLE
libreoffice 끝글자 버그 in kubuntu 17.10

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#88]
libreoffice에서 한글 입력시 끝글자가 마우스를 따라다니는 에러가 있습니다.

예시)
| : 커서
안녕하세ㅇ|
안녕하세요|
안녕요|하세

하지만
안녕하세ㅇ|
안녕하세요|
아무 키나 클릭
안녕|하세요

**Comment by cogniti** [comment]
libreoffice-gnome 패키지가 설치되어 있는지 확인하세요

**Comment by cogniti** [comment]
libreoffice-gnome 설치하시면 끝글자 버그 없이 잘 될거에요. libreoffice-gnome 설치하지 않고 사용하시려면 libreoffice 프로젝트에 보고해주세요. nimf 버그는 아닙니다.

**Comment by Hong-SeJung** [comment]
일부는 해결이 되었지만, 아직 해결되지 않은 것이 있습니다.
libreoffice에서 다른 프로그램과의 끝글자 버그는 사라졌지만, libreoffice상에서의 끝글자 버그는 아직 사라지지 않았습니다. 혹시 libreoffice 버그인가요?

**Comment by cogniti** [comment]
무슨 말씀이신지 이해가 잘 안 됩니다. libreoffice 프로젝트 측에 말씀해 주세요.
nimf 버그가 아닙니다.
