### ISSUE TITLE
Cantata(Qt5 응용프로그램)에서 한/영전환이 안됩니다.

### ISSUE THREAD

**Issue by nemonein** [cogniti/nimf#9]
안녕하세요.
Nimf 20160602, 우분투 16.04를 사용하고 있고, 한영 전환은 Shift Space 로 하고 있습니다. Hangul 키는 설정에서 삭제한 상태입니다.

제가 Cantata(https://github.com/CDrummond/cantata)라는 프로그램을 쓰는데, 여기서 한영 전환이 되질 않네요. 제 기억이 확실하지는 않지만, 이전 판에선 이런 문제가 없었던 것 같습니다.
Nimf 이전 판으로 확인이 불가하여, 다솜 최근판으로 확인해봤는데 한영 전환이 잘 되는데요.

Qt4/Qt5 Diable fallback filter On/Off 에 관계없이 작동이 안되네요.
Cantata 는 우분투 저장소에 있긴 한데 거기 있는 것은 (아마도) KDE 판이고, Qt 용은 따로 빌드를 해야해서, 제가 만든 꾸러미를 올려놓겠습니다. (우분투 16.04 용입니다.)
[cantata_2.0.50~xenial~git.491474c_amd64.zip](https://github.com/cogniti/nimf/files/295192/cantata_2.0.50.xenial.git.491474c_amd64.zip)

또는, (공식은 아니지만) 다음 PPA 를 이용하셔도 됩니다.
https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata

아직까진 이것 외에 다른 Qt 용 프로그램에서 오작동 하는 것은 못찾았습니다.
시간 되실 때 한번 확인해주시면 좋겠습니다.
고맙습니다!

**Comment by cogniti** [comment]
cantata_2.0.50~xenial~git.491474c_amd64.zip 이것을 설치하여 실행하면 한/영 전환이 되지 않습니다.
nimf 에 한/영 전환에 문제가 있는 것이 아니라 cantata_2.0.50~xenial~git.491474c_amd64.zip 에서 /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-nimf.so 을 로딩하지 않는 것 같습니다.

https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata 이것은 정상적으로 한/영 전환이 됩니다.

우분투 기본 저장소에 있는 http://packages.ubuntu.com/xenial/cantata 도 정상적으로 한/영 전환이 됩니다.

따라서 우분투 기본 저장소에 있는 cantata 를 사용하시면 되겠습니다.
감사합니다.

**Comment by nemonein** [comment]
그랬군요. 죄송합니다.
다솜에선 되길래 이번 판에 뭔가 변경이 있었나 하는 생각이 들어서 질문 드렸습니다.

고맙습니다!

**Comment by nemonein** [comment]
얼떨결에 이상한 현상을 발견했습니다.

먼저, 제가 위에 올린 PPA 주소가 잘못되어 있었네요.
https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/cantata-qt
여기가 맞습니다. 위에 올린 것은 KDE 용이고, 제가 말씀드린 것은 Qt 용이었는데.. 

아무튼, 이게 중요한 건 아니구요.
우분투에 있는 Sound Indicator 에서 Qt 로 된 프로그램을 실행할 경우, 한/영 전환이 되지 않는 현상이 있습니다.
Nimf(및 다솜)만이 아니고 Fcitx 에서도 같은 현상입니다.

확인한 프로그램은 Cantata(Qt 용; 새로 올린 PPA에 있는 버전)와 VLC(2.2.2; 우분투 저장소에 있는 것)입니다.
우분투 런처에서 실행하면 한/영 전환이 정상적으로 되지만, Sound Indicator 에서 실행하면 이상하게도 안되네요.
![sound-indicator](https://cloud.githubusercontent.com/assets/5688288/15749412/413251f8-291d-11e6-8333-b31f3368840f.jpg)

입력기와는 관계없는 Qt, 또는 Unity 버그가 아닐지.. 짐작만 해봅니다.
혹시나 같은 현상을 겪는 분이 계실까해서 글 남겨놓습니다.

**Comment by cogniti** [comment]
Qt 어플에서 한/중/일 등의 입력이 가능하려면
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-nimf.so
/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods/libqt4im-nimf.so
이런 파일이 로딩되어야 합니다.
ibus, fcitx 도 마찬가지입니다.
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts
/usr/lib/x86_64-linux-gnu/qt4/plugins/inputmethods
ibus, fcitx 를 설치했을 경우, 디렉토리 들어가서 ls 하시면 ibus, fcitx 용 .so 파일들도 보이실 겁니다.

우분투 16.04에서 kate 를 실행시키면,
kate 를 ibus, fcitx, nimf 등 중에서 어떤 입력 모듈(.so)을 로딩할지 결정해야 하는데...
```
hodong@debian:~$ export | grep QT
17:declare -x QT4_IM_MODULE="nimf"
18:declare -x QT_IM_MODULE="nimf"
hodong@debian:~$ export | grep GTK
9:declare -x GTK_IM_MODULE="nimf"
```
이런 값들을 볼 수 있습니다.
그렇다면 kate 는 Qt 어플이므로 `QT_IM_MODULE` 환경 변수를 읽습니다. 값이 `nimf`로 되어있으므로
`/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-nim.so`
를 로딩합니다.
kate(또는 Qt 툴킷)는 qt im api  를 호출합니다. libqt5im-nim.so 안에는 qt im api 를 구현해 놓은 것들이 들어있고, 그것들이 nimf 서버와 통신을 수행하고 결과값을 받아서 kate 출력되는 과정을 거칩니다.
원리는 단순합니다.
그렇다면
우분투에 있는 Sound Indicator 에서 환경변수를 읽어 들이지 않을 것이라는 추측을 할 수 있는데,
우분투에 있는 Sound Indicator 에서 smplayer 을 실행시킬 경우 한/영 전환이 된다고 하십니다.
그래서 http://packages.ubuntu.com/xenial/smplayer 을 찾아보니 qt5 어플입니다.
그렇다면 Sound Indicator 에서 `QT_IM_MODULE` 환경 변수를 정상적으로 읽어들인다고 볼 수 있고,
한/영 전환 안되는 Qt 어플이 문제일 것이라고 봅니다.
사실 한/영 전환이 안 된다기보다는 위에 말씀드린,
/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-nimf.so
이런 qt 모듈을 Qt 어플이 로딩하지 못하여 발생하는 현상으로 볼 수 있는데,
Qt 툴킷 자체 문제보다는 즉, Qt 링크를 잘못했다던가.. Qt 를 스태틱 링크를 했다던가..
등의 문제가 있을 것 같습니다.
그러한 유형의 프로그램으로 telegram 이 있습니다.
아무튼 정확한 원인을 조사하려면 해당 Qt 어플의 소스코드를 보고 확인해야 하는데,
제가 시간이 없어서 해당 Qt 어플의 소스코드를 확인해 볼 수가 없습니다. 죄송합니다.

**Comment by nemonein** [comment]
고맙습니다.
말씀해주신 것에서 힌트를 얻어 왜 이런 일이 생기는지 파악할 수 있었습니다.
Sound Indicator 를 통해 실행된 Qt5 프로그램이 시동될 때, 환경 변수가 제대로 뜨지 않는 것 같습니다.

참고로, 제가 설치한 SMPlayer 는 우분투 저장소에 있는 Qt5 용이 아니고, PPA(https://launchpad.net/~rvm/+archive/ubuntu/smplayer)에 있는 Qt4 어플리케이션입니다.

또, 이 문제는 우분투 15.10 에선 발생하지 않습니다. 14.04 에선 확인해보지 않았지만, 16.04 에 국한된 문제일 것 같습니다. 즉, 우분투 16.04 버그라고 보여집니다.

......................................
이 문제를 회피하려면, 다음과 같인 편법이 있을 수 있겠는데요.

Qt5 에 국한된 문제인지를 확인하기 위해, Qt5 용인 Notepadqq 를 Sound Indicator 메뉴에 강제로 등록시켜서 실험해봤습니다.
그 결과, Qt5 문제임을 확인할 수 있었고 회피법도 찾긴 했습니다.

Notepadqq 는 그냥 실행시켰을 때는 한영 전환에 문제가 없습니다.
그러나 S.I 에 강제등록 후 실행하니 한영 전환이 되질 않았습니다.
.desktop 파일을 수정하여 환경변수를 인식시켜준 후 실행해보니 한영 전환 문제가 없어진 것을 확인할 수 있었습니다.

정리하자면 이렇습니다.
1. /usr/share/applications/notepadqq.desktop 파일을 수정합니다.
`Exec=bash -c "export QT_IM_MODULE=nimf; export XMODIFIERS='@im=nimf'; /usr/bin/notepadqq %U"`

2. dconf-editor 에서 notepadqq.desktop 을 Sound Indicator 메뉴에 등록합니다.
`com.canonical.indicator.sound interested-media-players 에 notepadqq.desktop 등록.`

이러고 나서 실행하면, 그냥 등록했을 때는 되지 않던 것이 잘 되는 것을 확인해볼 수 있었습니다.
물론, 이 글을 올릴 때 문제가 됐던 Cantata 도 마찬가지로 잘 작동합니다.

제 블로그에도 정리해놓긴 했습니다만, 굳이 이렇게까지 해서 이 문제를 회피해야 할 지?
한영 전환이 필요할 땐 그냥 런처에서 실행하게 하는 편이 좋겠습니다.

어쨌든, @cogniti 님 덕분에 또 하나 배워갑니다.
고맙습니다.
