### ISSUE TITLE
간혹 nimf-daemon이 죽습니다.

### ISSUE THREAD

**Issue by memnoth** [cogniti/nimf#92]
정확하게 어떤 작업을 하면 죽는지는 잘 모르겠습니다만 사용하다가 어느순간 한/영 변환이 안되어 확인해보면 님프 데몬이 죽어있고 dmesg에는 다음과 같은 로그가 찍혀 있습니다.
```
nimf-daemon[687] general protection ip:7fb0e501d957 sp:7ffce6263d90 error:0 in libnimf-xim.so[7fb0e5017000+16000]
```
OS는 Arch 기반의 Antergos를 이용중이며 현재 커널 버전은 다음과 같습니다. Linux ant 4.15.8-1-ARCH
테스트 및 로그를 저장하는 방법을 알려주시면 증상이 다시 나타났을때 로그를 첨부하도록 하겠습니다.

감사합니다.

**Comment by cogniti** [comment]
안녕하세요.
버그를 재현하기 위해, nimf-daemon 이 죽었을 당시, 사용하시던 X 윈도용 프로그램이 어떤 건지 알고 싶습니다.

**Comment by memnoth** [comment]
그간 총 2번 발생했으며 처음 발생했을 때는 gnome-terminal에서 neovim(0.2.2) + spacevim을 이용하였고, 어제는 구글 크로미움(버전 65.0.3325.162(개발자 빌드) (64비트)) 과 visual-studio code(1.21.0)을 이용하고 있었습니다.

**Comment by cogniti** [comment]
`nimf-daemon --debug` 이렇게 실행시키면 상세한 debug 로그가 생성됩니다. 그 상태로 계속 사용하시면 용량이 매우 커지니 주기적으로 로그 파일을 삭제하시면 되겠습니다.
추후 재현되면 알려주세요. visual-studio code 를 한번 사용해보겠습니다.

**Comment by cogniti** [comment]
visual-studio code 를 잠시 사용해봤는데 GTK 입력 모듈을 사용합니다. visual-studio code 와 nimf 죽은 것과는 관련이 없을 것 같습니다.
libreoffice 라던가, wine 라던가 XIM 을 사용하는 X윈도용 프로그램을 사용하면서 nimf 가 죽었을 것 같습니다.
재현하기 위해  Antergos를 설치하려 하였지만, wifi 를 잡지 못해서 설치하지 못하였습니다.
추후 재현 방법을 확인하시면 알려주세요.

**Comment by cogniti** [comment]
제가 깜박하고 `--start-indicator` 옵션을 빼먹었네요.
```
  nimf-daemon --start-indicator --debug
  tail -f /var/log/daemon.log

  export GTK_IM_MODULE="nimf"
  export QT4_IM_MODULE="nimf"
  export QT_IM_MODULE="nimf"
  export XMODIFIERS="@im=nimf"
  export G_MESSAGES_DEBUG=nimf
```
이렇게 하시면 debug 메시지가 로그 파일에 출력됩니다.
export 부분은 환경 변수 설정입니다.
README 파일에 나와 있으니 참고하세요.

**Comment by memnoth** [comment]
커널 문제인 것 같습니다.
해당 커널에서 기타 다른 프로그램도 비슷하게 죽는 현상이 있었고 LTS 커널로 내리니 증상이 없습니다.
혹여나 다시 발생하거나 기타 다른 이유가 발견되면 해당 이슈를 다시 열겠습니다.

감사합니다.
