### ISSUE TITLE
kakaotalk 실행시 글자 에러

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#93]
안녕하세요.
Arch linux에서 Wine 3.4로 kakaotalk을 돌리고있습니다.
글자를 칠 때 친 글자가 카카오톡의 보내는 곳에 이상하게 뜹니다.
나눔고딕으로 바꿨을 때는 그러지 않는데, 다른 폰트를 적용하면 이상하게 뜨네요.
폰트 문제인 것 같기도 하지만, nimf의 문제일 가능성도 있을 것 같아 올려봅니다.
아니면 혹시 wine문제이거나 kakaotalk문제인가요?

**Comment by cogniti** [comment]
안녕하세요. nimf 문제가 아닙니다.

**Comment by Hong-SeJung** [comment]
그렇군요. 답변 감사드립니다
