### ISSUE TITLE
한글 2014에서 한/글 입력 문제

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#94]
안녕하세요.
한/글 2014에서 한글을 입력할 때 입력이 되지 않습니다.
wine에서 nimf를 실행시키면 어떤 창이 나오고 거기에 글자를 입력하면 그 글자가 들어가는데(정확한 명칭을 모르겠군요), 그 창에서 글자가 입력되지 않습니다.
아마도 한/글 2014가 독자적인 입력기를 사용해서 그 입력기와 충돌하는 것 같은데, 해결 부탁드립니다.

**Comment by cogniti** [comment]
한/글 2014에 내장된 입력기를 끌 수 있는 기능이 있다면 끄고 사용하세요.
아니면 한글2014 사용하기 전에,

```
export XMODIFIERS="@im=none"
```

으로 설정하고 실행하세요.

**Comment by cogniti** [comment]
nimf 버그가 아니며 nimf 에서 해결할 수 없습니다. 한컴이나 wine에 문의해주세요

**Comment by Hong-SeJung** [comment]
답변 감사드립니다.
그런데 만약에 
`export XMODIFIERS="@im=none"`
으로 설정하면 한/글 사용 후 다시 실행시켜야하나요?

**Comment by cogniti** [comment]
한글2014 사용하기 전에 환경 변수를
`export XMODIFIERS="@im=none"` 으로 설정하시고 사용하시면 되겠습니다.

**Comment by cogniti** [comment]
nimf 문제가 아닙니다.
wine 프로젝트 또는 한컴사에 문의해 주세요.
