### ISSUE TITLE
nimf 한글 입력 버그

### ISSUE THREAD

**Issue by Hong-SeJung** [cogniti/nimf#97]
안녕하세요.
nimf에서 한글을 입력하고
엔터키를 칩니다.
그리고 가운데 버튼(마우스 가운데 버튼)을 누르면 엔터키 치기 전 글자가 나타납니다.

예시)
안녕하세요[ENTER]
[가운데 버튼]요

안녕하세요.[ENTER]
[가운데버튼]요

안녕하세요...[ENTER]
[가운데 버튼]요

일본어 입력시에도 같은 현상이 일어납니다.
혹시 제가 시도해보지 않은 언어가 있으면 알려주십시오.
시도해본 언어는 한국어, 일본어입니다.

**Comment by cogniti** [comment]
gnome-terminal, firefox, gedit, geany 에서 재현되지 않습니다.
참고로 마우스 가운데 버튼을 누르면 복사된 텍스트가 출력됩니다.
임의의 텍스트를 마우스로 드래그 하여 복사한 후 가운데 버튼을 누르면 복사(copy)된 문자열이 출력됩니다.
어떤 어플로 테스트하셨나요?

**Comment by Hong-SeJung** [comment]
chrome, libreoffice입니다

**Comment by cogniti** [comment]
확인해봤는데 libreoffice 에서는 발생하지 않고, chrome 에서 발생합니다.
chrome 에서 입력할 때 조합(편집) 중인 문자가 클립보드에 복사되는 것 같습니다.
nimf 는 문자열을 클립보드에 복사하지 않습니다.
nimf 버그가 아닙니다. chrome 프로젝트에 문의하시기 바랍니다.

**Comment by Hong-SeJung** [comment]
답변 감사드립니다. 말씀하신대로 chrome에 문의해보겠습니다

**Comment by Hong-SeJung** [comment]
그런데 ctrl v를 누르면 복사된 문자가 제대로 나옵니다. 혹시 다른 메모리인가요?

**Comment by cogniti** [comment]
제가 설명을 잘못 드린 부분이 있습니다.

마우스로 드래그하셔 텍스트를 선택하면 그 텍스트가 PRIMARY 에 복사합니다.
마우스 가운데 버튼을 클릭하면 PRIMARY 에 있는 텍스트가 출력됩니다.

마우스로 드래그하셔 텍스트를 선택한 후 복사하기(copy)를 클릭하거나 CTRL + C 를 누르면 CLIPBOARD 에 복사됩니다. CTRL + V 하면 CLIPBOARD 에 있는 텍스트가 출력됩니다.

제가 시간이 없는 관계로 nimf 관련 문의만 받습니다.

https://developer.gnome.org/gtk3/stable/gtk3-Clipboards.html#gtk-clipboard-get-selection

https://specifications.freedesktop.org/clipboards-spec/clipboards-0.1.txt

X has a thing called "selections" which are just clipboards,
essentially (implemented with an asynchronous protocol so you don't
actually copy data to them). There are three standard selections
defined in the ICCCM: PRIMARY, SECONDARY, and CLIPBOARD.
