### ISSUE TITLE
Capslock을 한영키로 쓸 때

### ISSUE THREAD

**Issue by 0xrgb** [cogniti/nimf#98]
안녕하세요. nimf와 nimf-libhangul을 데비안에 설치해서 사용하고 있는 유저입니다. 
버전은 master의 가장 최신인 f9721a6를 사용하고 있습니다.

현재 Capslock과 Shift + space를 모두 한영키로 이용하고 있는데요,

아무 프로그램이나 켜고 (e.g. `bash`) 처음으로 글을 쓸 때 한글 상태에서 Capslock을 누르면 영어 (대문자)로
한글 상태에서 Shift+ space를 누르면 영어 (소문자)로 변경됩니다.

영어 (대문자) 상태에서 Alt+Capslock등으로 Capslock을 끄면, 그 이후에는 Capslock으로 전환해도 멀쩡히 영어 (소문자)로 변경됩니다.

실 사용에는 큰 불편이 없지만 (프로그램을 켜고 Capslock -> Alt+Capslock 누르면 해결됩니다) 무언가 로직에 이상이 있는 것 같아 Issue를 남깁니다.

ps. 정말 좋은 프로그램 만들어주셔서 감사합니다. 덕분에 리눅스에서 한글쓰는게 훨씬 편하네요.

**EDIT.**
기본 언어 엔진을 `libhangul`에서 `시스템 키보드`로 변경했더니 해결되었습니다.

**Comment by cogniti** [comment]
> 아무 프로그램이나 켜고 (e.g. bash) 처음으로 글을 쓸 때 한글 상태에서 Capslock을 누르면 영어 (대문자)로
한글 상태에서 Shift+ space를 누르면 영어 (소문자)로 변경됩니다.

그렇게 되는게 맞습니다.

> 영어 (대문자) 상태에서 Alt+Capslock등으로 Capslock을 끄면, 그 이후에는 Capslock으로 전환해도 멀쩡히 영어 (소문자)로 변경됩니다.

영어 (대문자) 상태에서 Capslock을 끄면 한글로 전환됩니다. 로직이 맞습니다.
한글 상태에서 Shift+ space 으로 다시 영어로 전환하면 소문자로 나옵니다. 로직이 맞습니다.
